### ISSUE TITLE
no-fits2fits option missing

### ISSUE THREAD

**Issue by wtgee** [dstndstn/astrometry.net#100]
Installing the latest from source and the `--no-fits2fits` option has disappeared. When performing the fits2fits we get all other errors (documented elsewhere) so we just want to skip this verification step. I can't find anything in the changelog or any mention of this option disappearing. Should this still be allowed?

Thanks!

**Comment by dstndstn** [comment]
In 7529b4b I removed the --no-fits2fits option, making it the default; as you say, fits2fits was causing more problems than it was solving.  Just forgot to update the changelog.

**Comment by wtgee** [comment]
Ok, I see that now, thanks. Small PR to remove a few places it is mentioned in the docs.
