### ISSUE TITLE
Use OpenNGC catalog instead of ngc2000

### ISSUE THREAD

**Issue by lupinix** [dstndstn/astrometry.net#108]
Hi,

@mattiaverga made the nice work to create a new license-friendly NGC/IC catalog: https://github.com/mattiaverga/OpenNGC . astrometry uses a copy of ngc2000 right now, which is for non commercial use only and thus not distributable for many Linux distributions like Fedora (for which I'm working). Therefore it would be nice if astrometry could use OpenNGC instead of ngc2000. What is required to get that working? Would like to help with that :)

Greetings,
Christian

**Comment by dstndstn** [comment]
Hi,

This would be great!  @olebole, Debian maintainer, will be interested too.

What it would take: for a relatively painless switch-over, we would require two things:
* replacement of catalogs/ngc2000.h, which lists the NGC/IC objects, AND has common names for them (NGC 224 = M31)
* FITS tables to replace https://github.com/dstndstn/astrometry.net/blob/master/catalogs/ngc2000.fits and ic2000.fits

The first provides compiled-in access to the catalog for C code, the second provides dynamic access for Python code.

There is also the detail of the ngcic-accurate module, which brings in more accurate positions for some objects -- this would just have to be removed from the code.

If it were hard to produce the C version for some reason, another option would be to only provide the FITS tables, and then modify the code to make that uses the C API instead use the FITS tables, or indeed, switch solve-field from using C plot-constellations to python plotann.py.

I would be happy to make the code modifications if you can work on the data files!

cheers,
--dustin

**Comment by lupinix** [comment]
Nice! So I have to create the two FITS tables. Anything else? What is the source for ngc2000names.dat? Is that from ngc2000 too or from a free source?

Greetings,
Christian

**Comment by dstndstn** [comment]
ngc2000names.dat also comes from the NGC2000 catalog distribution
ftp://cdsarc.u-strasbg.fr/cats/VII/118/names.dat

If you can make the FITS tables, I can do the rest -- producing a drop-in replacement for the file "catalogs/ngc2000entries.c":

{ .is_ngc = FALSE,
  .id = 5370,
  .classification = "Gx",
  .ra = 0.025,
  .dec = 32.75,
  .size = 0.7,
  .constellation = "And",
  .mag = 15.,
},
{ .is_ngc = FALSE,
  .id = 5371,
  .classification = "",
  .ra = 0.05,
  .dec = 32.8167,
  .size = 0,
  .constellation = "And",
  .mag = -99,
},
...

cheers,
--dustin

**Comment by lupinix** [comment]
OK, I'll create drop-in replacements for the FITS tables. Does astrometry use the classification anywhere? If yes I have to map the labels of OpenNGC classification to the labels of NGC 2000.0 classification or the code using the classification may require minor adaptions.

**Comment by dstndstn** [comment]
Hi,

I don't think anything in the main astrometry.net code uses the classifications.  It would be good to have classifications (eg, I'm using them in http://twitter.com/LegacySurveyBot), but they don't need to be the same as in the NGC2000 catalog.

By the way, there is a "text2fits" program in the astrometry.net code, so if it's easier to produce a CSV or other text format file, that's fine too.

thanks!
--dustin

**Comment by lupinix** [comment]
Creating FITS tables is quite easy for me, I use astropy for that (for example here to create index files from "source" https://github.com/lupinix/astrometry-tycho2 ), so this is fine. I'll take the classification from OpenNGC "as is", description is in https://github.com/mattiaverga/OpenNGC/blob/master/README.md

**Comment by lupinix** [comment]
Better description: https://github.com/mattiaverga/OpenNGC/blob/master/NGC_guide.txt

**Comment by lupinix** [comment]
I'm working on that here and have FITS tables now: openngc_ic.fits (similar to ic2000.fits) and openngc_ngc.fits (similar to ngc2000.fits). Not yet done: replacement for ngc2000names.fits

**Comment by mattiaverga** [comment]
@lupinix any progress on this?
If it can help in your effort to create a replacement for ngc2000names.fits, I've created a Python interface to OpenNGC database data: https://github.com/mattiaverga/PyOngc
This is my first Python project, so it may be quite awful, but with the listObjects method you can filter out objects with common names and then with getIdentifiers you can get a list of common names for the object.

**Comment by lupinix** [comment]
@mattiaverga Currently quite busy but I still have the project on my todo.

**Comment by olebole** [comment]
@lupinix triggered by a thread in the astrometry.net mailing list: any news here?
