### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by hannorein** [dstndstn/astrometry.net#111]
Looks like the hard disk is full on nova?

<img width="730" alt="screen shot 2017-05-29 at 11 10 26 pm" src="https://cloud.githubusercontent.com/assets/53376/26566812/0badb63a-44c4-11e7-919b-8780c8888807.png">

**Comment by dstndstn** [comment]
Thanks for the note!  I cleared up a few hundred GB, so it should be okay for a while...
