### ISSUE TITLE
augment_xylist not installed

### ISSUE THREAD

**Issue by gitj** [dstndstn/astrometry.net#115]
Hi,
To solve a text file of x,y locations, I find it necessary to run text2fits -> augment_xylist -> solve_field
However, augment_xylist seems to not be installed (it's listed in "NOT_INSTALLED _PIPELINE").
Is this intentional? Is there a better way of solving from an x,y text file, or should augment_xylist be added to the executables to install.
Thanks!

**Comment by dstndstn** [comment]
Hi,
Is it not possible to run text2fits -> solve-field directly?

**Comment by gitj** [comment]
I didn't have luck with that so far, but if you can suggest an incantation,
that would be great.
I started using augment_xylist after failing to figure out how to get
solve_field to work directly and saw that it was used on nova.astrometry
when submitting a text xy list.

Thanks,
Glenn

**Comment by dstndstn** [comment]
Hi,

I tried this and it worked:

* Generate an example text x,y list:

> tablist -r demo/apod4.xyls"[col x;y]" > apod4.txt
> head -n 3 apod4.txt
       129.168        147.613
       444.982        183.983
       552.240        13.4566

* Convert text to FITS table of x,y positions.  Note the "-f ff" -- tell it that the two columns should be read as floating-point; and '-H "x y"' -- tell it that the two columns should be named "x" and "y".

> text2fits -f ff -H "x y" apod4.txt apod4.xy
Reading file apod4.txt
[...]

Here's the result:

> liststruc apod4.xy

HDU #1  Array:  NAXIS = 0,  BITPIX = 16

HDU #2  Binary Table:  2 columns x 1724 rows
 COL NAME             FORMAT
   1 x                E
   2 y                E

The "E"s say that they are floating-point numbers.

* Solve-field:

> solve-field --config 99.cfg apod4.xy --continue --width 700 --height 500
Reading input file 1 of 1: "apod4.xy"...
(null): Error reading magic number from Netpbm image stream.  Most often, this means your input file is empty.
(null): Error reading magic number from Netpbm image stream.  Most often, this means your input file is empty.
solve-field.c:326:plot_source_overlay Plotting command failed
 solve-field.c:132:run_command Command was: "/usr/local/bin/plotxy -I /tmp/tmp.ppm.oOl9Kc -i ./apod4.axy -C red -w 2 -N 50 -x 1 -y 1 -P | /usr/local/bin/plotxy -i ./apod4.axy -I - -w 2 -r 3 -C red -n 50 -N 200 -x 1 -y 1 > ./apod4-objs.png"

 solve-field.c:131:run_command Command exited with exit status 1
Solving...
Reading file "./apod4.axy"...
  log-odds ratio 162.629 (4.25549e+70), 30 match, 1 conflict, 84 distractors, 35 index.
  RA,Dec = (186.472,56.9984), pixel scale 170.547 arcsec/pix.
  Hit/miss:   Hit/miss: ++++++-+++++++-++++------++----++-+-----++-----+--+-------+------------------------+------------+---
Field 1: solved with index index-9918.fits.
Field 1 solved: writing to file ./apod4.solved to indicate this.
Field: apod4.xy
Field center: (RA,Dec) = (186.488205, 57.009171) deg.
Field center: (RA H:M:S, Dec D:M:S) = (12:25:57.169, +57:00:33.014).
Field size: 32.3206 x 23.4229 degrees
Field rotation angle: up is 59.3689 degrees E of N
Field parity: neg


That first batch of failures is from trying to create the plots; plotting for x,y lists is broken.  But it then goes on to get a successful solution.

(The 99.cfg file was created with:
> build-astrometry-index -d 3 -o index-9918.fits -P 18 -S mag -B 0.1 -s 0 -r 1 -I 9918 -M -i demo/tycho2-mag6.fits
> echo -e 'add_path .\ninparallel\nindex index-9918.fits' > 99.cfg
)

Hope that helps... if not, could you please post an example text x,y file that you're using?

thanks,
--dustin

**Comment by gitj** [comment]
OK that does seem to work, not sure why I was having trouble with it before. I'll go ahead and close this then. Thank you for the help!
