### ISSUE TITLE
Get 500-Error on Annotations-Api

### ISSUE THREAD

**Issue by dominikmatt** [dstndstn/astrometry.net#117]
#### Actual Behavior
When i call the annoation-api example with the jobId `1493115` i get a 500-Error with following message: (http://nova.astrometry.net/api/jobs/1493115/annotations/)

## ERROR OUTPUT
AttributeError at /api/jobs/1493115/annotations/

'module' object has no attribute 'kdtree_get_positions'

**Request Method:** 	GET
**Request URL:** 	http://nova.astrometry.net/api/jobs/1493115/annotations/
    **Django Version:** 	1.11.2
**Exception Type:** AttributeError
**Exception Value:** 'module' object has no attribute 'kdtree_get_positions'

**Exception Location:** 	/home/nova/nova/astrometry/blind/plotann.py in match_kdtree_catalog, line 34
**Python Executable:** 	/usr/bin/python
**Python Version:** 	2.7.12
**Python Path:**

    ['/usr/local/django-1.11.2/lib/python/Django-1.11.2-py2.7.egg',
        '/usr/local/pyfits-3.1.1/lib/python',
        '/usr/local/django-1.11.2/lib/python',
        '/usr/local/lib/python2.7/dist-packages/distribute-0.7.3-py2.7.egg',
        '/usr/local/lib/python2.7/dist-packages/setuptools-7.0-py2.7.egg',
        '/usr/local/lib/python2.7/dist-packages/PyJWT-1.4.0-py2.7.egg',
        '/usr/local/pyfits-3.1.2/lib/python',
        '/usr/local/fitsio/lib/python',
        '/usr/lib/python2.7',
        '/usr/lib/python2.7/plat-x86_64-linux-gnu',
        '/usr/lib/python2.7/lib-tk',
        '/usr/lib/python2.7/lib-old',
        '/usr/lib/python2.7/lib-dynload',
        '/usr/local/lib/python2.7/dist-packages',
        '/usr/lib/python2.7/dist-packages',
        '/usr/lib/python2.7/dist-packages/PILcompat',
        '/usr/lib/python2.7/dist-packages/gtk-2.0',
        '/usr/lib/pymodules/python2.7',
        '/home/nova/nova/net',
        '/home/nova/nova']

Server time: 	Sun, 20 Aug 2017 08:48:16 -0400

**Comment by dstndstn** [comment]
Thank you for the bug report!  This was due to a change in the kd-tree code that I missed updating in the annotation code.  I believe it's now fixed (9d94dc6b) and I updated the web site; the 500 error on your example URL is gone.  If you find further related problems please re-open this ticket.

Thanks again for the clear bug report!
