### ISSUE TITLE
qfits_card.c:238]: (style) Array index 'i' is used before limits check.

### ISSUE THREAD

**Issue by dcb314** [dstndstn/astrometry.net#119]
Source code is

    while (line[i]!='=' && i<80) i++;

Plenty of duplicates in the same file:

[qfits_card.c:308]: (style) Array index 'i' is used before limits check.
[qfits_card.c:316]: (style) Array index 'i' is used before limits check.
[qfits_card.c:399]: (style) Array index 'i' is used before limits check.
[qfits_card.c:238]: (style) Array index 'i' is used before limits check.
[qfits_card.c:308]: (style) Array index 'i' is used before limits check.
[qfits_card.c:316]: (style) Array index 'i' is used before limits check.
[qfits_card.c:399]: (style) Array index 'i' is used before limits check.

**Comment by dstndstn** [comment]
What tool are you using here?

I'm not sure, but it's possible that these are not actually problems due to higher-level guarantees (eg, calling code knows there is an '=' in the string).

**Comment by dcb314** [comment]
>What tool are you using here?

cppcheck, a static analyser for C and C++

**Comment by dstndstn** [comment]
Thank you -- fixed in 7b732f5a
