### ISSUE TITLE
#!env python   on mac

### ISSUE THREAD

**Issue by jtkifa** [dstndstn/astrometry.net#120]
I found that "#! env python" in the bin directory scripts finds the official apple python (2.7.7 I think) but one might prefer to use a newer python, like in macports.  Perhaps libs like pyfits don't even work with the old one (unless I'm missing something), and macports installation of astropy works only on its own python.  Generally, a machine may have numerous python versions in many places.

It might be nice if the version of python were fully configurable.  Changing it in utils/makefile.common doesn't seem to affect the one the scripts use.  I couldn't find a way to do it without a manual edit of all py scripts.

**Comment by dstndstn** [comment]
Hi,
The point of using the env command to do this is it supposed to run whatever version of python would be run if you typed 'python' in your shell.  I was under the impression that if you want to run a specific python, you could achieve that by putting it first in your PATH variable in your shell's initialization script (eg, ~/.bash_profile, ~/.bashrc, or whatever).
The env command exists, as far as I understand, for exactly this purpose.
cheers,
--dustin

**Comment by jtkifa** [comment]
Understood; however one could also argue that the default python in the shell (in this case, the OS-X system default, in /usr/bin) might not always be the python one wants for one particular application. Further,  another application might also apply the same reasoning and use env, but need a different python, so the 'env' solution can put different applications using it into conflict.    Anyway, I changed it to 'env python3.4.'  

Another solution would have been to wrap the main routine in a script that redefines the PATH.  The greatest difficulty was discovering the source of the problem, and that changing utils/makefile.common did not in fact change the python version used.

**Comment by dstndstn** [comment]
Fair enough!
So, implementing this would require re-writing the files in bin/ when installing, is that right?  Could be implemented with, eg, a sed script in the Makefile's install step?
thx

**Comment by moustakas** [comment]
Or one could simply create a dedicated `conda` environment and install whatever version of python is desired...

**Comment by jtkifa** [comment]
yes, I ended up implementing a sed script for the /bin directory.

Concerning the conda environment, that be more of a challenge from perspective of users.

A 90% solution would be to mention it prominently in the installation docs, something like:  _'NOTE: by default, astrometry.net uses the python accessible in your PATH as "python" - to change this, edit each file in ./bin and replace #! env python with the full path to the python of your choice.'_

**Comment by dstndstn** [comment]
With 6ab339c9 you can now do:

    make install INSTALL_DIR=/tmp/an PYTHON_SCRIPT="/usr/bin/env python3.6"

to set the script used in the "shebang" line of the python scripts.

**Comment by wtgee** [comment]
Sorry to jump on this late, but I just saw the 0.73 release with this feature. As @dstndstn points out, this is exactly why using 'env' exists.

> Understood; however one could also argue that the default python in the shell (in this case, the OS-X system default, in /usr/bin) might not always be the python one wants for one particular application. Further, another application might also apply the same reasoning and use env, but need a different python, so the 'env' solution can put different applications using it into conflict. Anyway, I changed it to 'env python3.4.'

The answer to this is to change your environment via something like anaconda and run astrometry.net in a different environment, which you should probably be doing anyway. It is bad practice to install thing into your default OS environment these days.

**Comment by jtkifa** [comment]
From a user’s perspective, I think the current solution is nice because  it keeps the old way as a default (so anaconda is still a viable possibility), but it also allows users, if they wish, to do the fast and easy thing and pick their own python (which I did, manually, and astrometry.net <http://astrometry.net/> runs great now).     Experts who use anaconda can do the technically better thing at no extra cost.

As a non-expert in python, the hardest part for me was identifying the issue.   I kept installing python packages in macports and astrometry.net <http://astrometry.net/> didn’t see them because it was using the default system python.  And I kept thinking “there must be a way to specify which python to use, just like I can specify CC”.    

Whatever the solution is, I think it would be good for the documentation to mention this issue with python versions.

For example http://astrometry.net/doc/build.html#build <http://astrometry.net/doc/build.html#build>

could say 

“astrometry.net <http://astrometry.net/> scripts use the python obtained from the environment using ‘env python’.  To override the use of the default python on your system and use pythonX.Y instead, you may use  Anaconda, or specify 
'make install INSTALL_DIR=/your/install/directory   PYTHON_SCRIPT="/usr/bin/env pythonX.Y"'

Best regards,  and many thanks to everyone who created astrometry.net
Jan

**Comment by wtgee** [comment]
@jtkifa Agreed that updating docs is a good thing to reflect that. I would also encourage you to look into Anaconda as make installation and tracking versions easy is its whole purpose and it really does a great job.

In general I think getting astrometry.net easily installable via anaconda cloud would alleviate pain for a lot of people. I know the LSST folks were trying to do something similar but had to abandon for lack of resources. 

Of course, it's easy for me to demand @dstndstn do something without actually contributing. ;)

**Comment by dstndstn** [comment]
Thanks for the text -- I just added that to the docs :)
