### ISSUE TITLE
installation issue ubuntu 16.04

### ISSUE THREAD

**Issue by masoudline** [dstndstn/astrometry.net#121]
Hi, 
I want to setup astrometry on Linux Ubuntu 16.04 LTS but I have some problem:
`make -C qfits-an

make[1]: Entering directory '/home/roxo/Downloads/astrometry.net-0.72/qfits-an'
make[1]: Nothing to be done for 'all'.

make[1]: Leaving directory '/home/roxo/Downloads/astrometry.net-0.72/qfits-an'

make -C gsl-an

make[1]: Entering directory '/home/roxo/Downloads/astrometry.net-0.72/gsl-an'

make[1]: Nothing to be done for 'all'.

make[1]: Leaving directory '/home/roxo/Downloads/astrometry.net-0.72/gsl-an'

make -C util

make[1]: Entering directory '/home/roxo/Downloads/astrometry.net-0.72/util'

make[1]: Nothing to be done for 'all'.

make[1]: Leaving directory '/home/roxo/Downloads/astrometry.net-0.72/util'

make -C catalogs

make[1]: Entering directory '/home/roxo/Downloads/astrometry.net-0.72/catalogs'

make[1]: Nothing to be done for 'all'.

make[1]: Leaving directory '/home/roxo/Downloads/astrometry.net-0.72/catalogs'

make -C libkd

make[1]: Entering directory '/home/roxo/Downloads/astrometry.net-0.72/libkd'

make[1]: Nothing to be done for 'all'.

make[1]: Leaving directory '/home/roxo/Downloads/astrometry.net-0.72/libkd'

make -C blind

make[1]: Entering directory '/home/roxo/Downloads/astrometry.net-0.72/blind'

make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/roxo/Downloads/astrometry.net-0.72/blind'`

i setup below packages:

1. libastro-fits-cfitsio-perl - Perl extension for using the cfitsio library
2. libastro-fits-header-perl - module for reading, modifying and writing FITS headers
3. libccfits-dev - static library for I/O with FITS format data files
4. libccfits-doc - documentation for CCfits
5. libccfits0v5 - shared library for I/O with FITS format data files
6. libcfitsio-bin - CFITSIO based utilities
7. libcfitsio-dev - library for I/O with FITS format data files (development files)
8. libcfitsio-doc - documentation for CFITSIO
9. libcfitsio2 - shared library for I/O with FITS format data files
10. libcfitsio2-dbg - library for I/O with FITS format data files (debugging symbols)
11. libcfitsio3-dev - Transitional package for libcfitsio-dev
12. slang-cfitsio - read and write FITS files from S-Lang
13. tcl-fitstcl - Tcl interface to FITS files

The Cfitsio-dev package not exists at ubuntu 16.04
and when i manual set Cfitsio those error still exist:
`make CFITS_INC="-I/home/roxo/cfitsio/include/" CFITS_SLIB="/home/roxo/cfitsio/lib/libcfitsio.a"`

**Comment by dstndstn** [comment]
Hi,

I don't see an error here.  The message "make[1]: Nothing to be done for 'all'." means that the programs are already built; the "make" program is telling you that its job is already done.

Let's go back to bug-reporting basics:
- what did you run / type
- what did you expect to happen
- what actually happened

Thanks!
--dustin

**Comment by masoudline** [comment]
ok thanks
I want access to plotaan.py , how can do it?
when I make successfully your package, I will expect that file exist at usr/local/astrometry/blind but I can't see it.

**Comment by masoudline** [comment]
thanks for your answer
i run my code and below errors exists:
i install astrometry on default folder: /usr/local/astrometry 

solve-field.c:518:run_engine engine failed.  Command that failed was:
  /usr/bin/astrometry-engine /home/roxo/unh-startracker-master/analysisAndPlots/maps/dataset//DSC_0058_NEF_embedded.axy
 ioutils.c:567:run_command_get_outputs Command failed: return value 255
wcsFile ========= DSC_0058_NEF_embedded.wcs 
command is ['/usr/local/astrometry/bin/plotann.py', '--brightcat', '/home/roxo/unh-startracker-master/astrometry/catalogs/brightstars.fits', '/home/roxo/unh-startracker-master/analysisAndPlots/maps/dataset/DSC_0058_NEF_embedded.wcs']
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/usr/local/astrometry/bin/plotann.py", line 16, in <module>
    from astrometry.blind.plotstuff import *
  File "/usr/local/astrometry/lib/python/astrometry/blind/plotstuff.py", line 3, in <module>
    from plotstuff_c import *
  File "/usr/local/astrometry/lib/python/astrometry/blind/plotstuff_c.py", line 17, in <module>
    _plotstuff_c = swig_import_helper()
  File "/usr/local/astrometry/lib/python/astrometry/blind/plotstuff_c.py", line 16, in swig_import_helper
    return importlib.import_module('_plotstuff_c')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 310, in <module>
    runCenterPixelMethod()  
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 293, in runCenterPixelMethod
    starList = getStarDict(wcsFile)
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 128, in getStarDict
    starDict = json.loads(starDict)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Process finished with exit code 1

**Comment by dstndstn** [comment]
Hi,

The problem is:
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
when loading the "plotstuff" module.  It says that it was compiled with numpy version "b" but the numpy version available is "a".

You could try, in the astrometry source directory,

make py
make install

to see if it rebuilds the "plotstuff" library (blind/_plotstuff_c.so).  Or do a "make clean && make && make py && make install" to rebuild everything.

**Comment by masoudline** [comment]
i run your note and those errors change to:


solve-field.c:518:run_engine engine failed.  Command that failed was:

---------------------------------------------------------------------
  /usr/bin/astrometry-engine /home/roxo/unh-startracker-master/analysisAndPlots/maps/dataset//DSC_0058_NEF_embedded.axy
You must list at least one index in the config file (/usr/bin/../etc/astrometry.cfg)

 ioutils.c:567:run_command_get_outputs Command failed: return value 255
See http://astrometry.net/use.html about how to get some index files.
---------------------------------------------------------------------

wcsFile ========= DSC_0058_NEF_embedded.wcs 
command is ['/usr/local/astrometry/bin/plotann.py', '--brightcat', '/home/roxo/unh-startracker-master/astrometry/catalogs/brightstars.fits', '/home/roxo/unh-startracker-master/analysisAndPlots/maps/dataset/DSC_0058_NEF_embedded.wcs']
anwcs.c:1039:anwcs_open_wcslib: Wcslib support was not compiled in
anwcs.c:1061:anwcs_open_wcstools: WCStools support was not compiled in
Traceback (most recent call last):
  File "/usr/local/astrometry/bin/plotann.py", line 316, in <module>
    jobjs = get_annotations_for_wcs(wcs, opt)
  File "/usr/local/astrometry/bin/plotann.py", line 140, in get_annotations_for_wcs
    if not wcs.is_inside(r, d):
  File "/usr/local/astrometry/lib/python/astrometry/util/util.py", line 1218, in is_inside
    return _util.anwcs_t_is_inside(self, ra, dec)
TypeError: in method 'anwcs_t_is_inside', argument 1 of type 'struct anwcs_t *'
Traceback (most recent call last):
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 310, in <module>
    runCenterPixelMethod()  
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 293, in runCenterPixelMethod
    starList = getStarDict(wcsFile)
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 128, in getStarDict
    starDict = json.loads(starDict)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by dstndstn** [comment]
Okay, so now the problem is
"Wcslib support was not compiled in"

Try:
sudo apt-get install wcslib-dev

and then
make reconfig
make
make py
make install

**Comment by masoudline** [comment]
i run your note but these errors exists still:

solve-field.c:518:run_engine engine failed.  Command that failed was:
  /usr/bin/astrometry-engine /home/roxo/unh-startracker-master/analysisAndPlots/maps/dataset//DSC_0058_NEF_embedded.axy
 ioutils.c:567:run_command_get_outputs Command failed: return value 255
wcsFile ========= DSC_0058_NEF_embedded.wcs 
command is ['/usr/local/astrometry/bin/plotann.py', '--brightcat', '/home/roxo/unh-startracker-master/astrometry/catalogs/brightstars.fits', '/home/roxo/unh-startracker-master/analysisAndPlots/maps/dataset/DSC_0058_NEF_embedded.wcs']
anwcs.c:917:getheader: Failed to open file /home/roxo/unh-startracker-master/analysisAndPlots/maps/dataset/DSC_0058_NEF_embedded.wcs
anwcs.c:1061:anwcs_open_wcstools: WCStools support was not compiled in
Traceback (most recent call last):
  File "/usr/local/astrometry/bin/plotann.py", line 316, in <module>
    jobjs = get_annotations_for_wcs(wcs, opt)
  File "/usr/local/astrometry/bin/plotann.py", line 140, in get_annotations_for_wcs
    if not wcs.is_inside(r, d):
  File "/usr/local/astrometry/lib/python/astrometry/util/util.py", line 1218, in is_inside
    return _util.anwcs_t_is_inside(self, ra, dec)
TypeError: in method 'anwcs_t_is_inside', argument 1 of type 'struct anwcs_t *'
Traceback (most recent call last):
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 310, in <module>
    runCenterPixelMethod()  
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 293, in runCenterPixelMethod
    starList = getStarDict(wcsFile)
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 128, in getStarDict
    starDict = json.loads(starDict)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by lupinix** [comment]
Why don't you use the astrometry.net package that Ubuntu provides? sudo apt-get install astrometry.net

**Comment by masoudline** [comment]
i setup this package and these error show:

Usage: image2pnm.py [options]

image2pnm.py: error: no such option: --sanitized-fits-outfile
augment-xylist.c:588:backtick Failed to run command: /usr/bin/python -m astrometry.util.image2pnm --sanitized-fits-outfile /tmp/tmp.sanitized.NKas9M --fix-sdss --infile /home/roxo/unh-startracker-master/analysisAndPlots/maps/dataset/DSC_0031_NEF_embedded.jpg --uncompressed-outfile /tmp/tmp.uncompressed.uJEHGi --outfile /tmp/tmp.ppm.TleXdO --ppm
 ioutils.c:567:run_command_get_outputs Command failed: return value 2
wcsFile ========= DSC_0031_NEF_embedded.wcs 
command is ['/usr/local/astrometry/bin/plotann.py', '--brightcat', '/home/roxo/unh-startracker-master/astrometry/catalogs/brightstars.fits', '/home/roxo/unh-startracker-master/analysisAndPlots/maps/dataset/DSC_0031_NEF_embedded.wcs']
anwcs.c:917:getheader: Failed to open file /home/roxo/unh-startracker-master/analysisAndPlots/maps/dataset/DSC_0031_NEF_embedded.wcs
anwcs.c:1061:anwcs_open_wcstools: WCStools support was not compiled in
Traceback (most recent call last):
  File "/usr/local/astrometry/bin/plotann.py", line 316, in <module>
    jobjs = get_annotations_for_wcs(wcs, opt)
  File "/usr/local/astrometry/bin/plotann.py", line 140, in get_annotations_for_wcs
    if not wcs.is_inside(r, d):
  File "/usr/local/astrometry/lib/python/astrometry/util/util.py", line 1218, in is_inside
    return _util.anwcs_t_is_inside(self, ra, dec)
TypeError: in method 'anwcs_t_is_inside', argument 1 of type 'struct anwcs_t *'
Traceback (most recent call last):
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 310, in <module>
    runCenterPixelMethod()  
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 293, in runCenterPixelMethod
    starList = getStarDict(wcsFile)
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 128, in getStarDict
    starDict = json.loads(starDict)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by lupinix** [comment]
The error message has contents like "/usr/local/astrometry/bin/plotann.py" which means it is *not* the Ubuntu package here. Also the Ubuntu package is compiled with WCS support, another hint that you're using something different.

**Comment by dstndstn** [comment]
Yes, if you use the ubuntu package, be sure to remove your local install from /usr/local/astrometry, otherwise there will be conflicts.

**Comment by dstndstn** [comment]
Also: could you please also include the solve-field command you are running -- I am having trouble understanding what is going on in your tracebacks.

It looks like it is having trouble reading: the file: DSC_0058_NEF_embedded.wcs

so if that file exists, could you please attach it?

Thanks!

**Comment by masoudline** [comment]
Hi
thanks for your answers
I installed sudo apt-get astrometry.net and these error show:
Usage: image2pnm.py [options]

image2pnm.py: error: no such option: --sanitized-fits-outfile
augment-xylist.c:588:backtick Failed to run command: /usr/bin/python -m astrometry.util.image2pnm --sanitized-fits-outfile /tmp/tmp.sanitized.kC6ajK --fix-sdss --infile /home/roxo/unh-startracker-master/dataset/DSC_0031_NEF_embedded.jpg --uncompressed-outfile /tmp/tmp.uncompressed.WPFD0y --outfile /tmp/tmp.ppm.6Ym6Hn --ppm
 ioutils.c:567:run_command_get_outputs Command failed: return value 2

The DSC_0058_NEF_embedded.jpg is a picture of night sky that convert to wcs

i want debugging basic errors

**Comment by masoudline** [comment]
how can i downgrade CFITSIO version?
what's appropriate version?

**Comment by dstndstn** [comment]
Hi,
On my Ubuntu 16.04 box I have these packages installed:

*  libcfitsio-dev:amd64              3.370-5
*  libcfitsio-doc                    3.370-5
*  libcfitsio2:amd64                 3.370-5
*  libcfitsio3-dev                   3.370-5

**Comment by masoudline** [comment]
Hi,
All of these package installed on my Ubunto 16.04 but that error exist still

**Comment by dstndstn** [comment]
you did a "make clean; make"?

This error is saying that the fitsio.h and libcfitsio.so files do not match.

**Comment by masoudline** [comment]
yes i do.
i first make clean and then make but error still exist.

**Comment by dstndstn** [comment]
I would do:
* remove /home/roxo/cfitsio
* remove all cfits-related apt packages except for the ones I listed

**Comment by masoudline** [comment]
i remove that folder and these packages:
```
Removing astrometry.net (0.67+dfsg-1) ...
Removing libcfitsio-bin (3.370-5) ...
Removing libcfitsio3-dev (3.370-5) ...
Removing libcfitsio-dev:amd64 (3.370-5) ...
Removing libcfitsio-doc (3.370-5) ...
Removing python-pyfits (1:3.4-1) ...
Removing python-astrometry (0.67+dfsg-1) ...
Removing python-astropy (1.1.1-3) ...
Removing libcfitsio2:amd64 (3.370-5) ...
Processing triggers for man-db (2.7.5-1) ...

```

**Comment by dstndstn** [comment]
in your original message you said you installed a bunch of other cfits-related packages.  I would remove:

*    libastro-fits-cfitsio-perl - Perl extension for using the cfitsio library
*    libastro-fits-header-perl - module for reading, modifying and writing FITS headers
*   libccfits-dev - static library for I/O with FITS format data files
*    libccfits-doc - documentation for CCfits
*    libccfits0v5 - shared library for I/O with FITS format data files
*    libcfitsio-bin - CFITSIO based utilities
*    libcfitsio2-dbg - library for I/O with FITS format data files (debugging symbols)
*    slang-cfitsio - read and write FITS files from S-Lang
*    tcl-fitstcl - Tcl interface to FITS files

**Comment by masoudline** [comment]
yes. but now i remove all packages

**Comment by dstndstn** [comment]
o...k... and does it work now?

**Comment by masoudline** [comment]
now these errors appeared:
```
Traceback (most recent call last):
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 308, in <module>
    runCenterPixelMethod()  
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 287, in runCenterPixelMethod
    makeWcsFiles(image)
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 115, in makeWcsFiles
    subprocess.call(['solve-field', '-p', '--overwrite', '--scale-units','degwidth', '--scale-low', '25', '--scale-high', '35','--downsample', '2', '-D', dataDir, image])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

and these errors belongs to below function:

```
def makeWcsFiles(image):
    # this function calls astrometry with certain options and puts a .wcs file
    # in the directory specified after '-D'
    subprocess.call(['solve-field', '-p', '--overwrite', '--scale-units',
                    'degwidth', '--scale-low', '25', '--scale-high', '35',
                    '--downsample', '2', '-D', dataDir, image])
```

**Comment by dstndstn** [comment]
Okay, so now run in the shell,

solve-field -p --overwrite --scale-units degwidth --scale-low 25 --scale-high 35 --downsample 2 IMAGE.jpg --verbose

with your IMAGE.jpg

and report what it says.  Please paste THE WHOLE LOG.  Yet, it should be long.

**Comment by masoudline** [comment]
do i correctly add --verbose to my function? I'm confused 
```
    subprocess.call(['solve-field', '-p', '--overwrite', '--scale-units',
                    'degwidth', '--scale-low', '25', '--scale-high', '35',
                    '--downsample', '2', '-D', dataDir, image, '--verbose'], shell=True) 

```

**Comment by dstndstn** [comment]
No, I mean, do not try to run solve-field from inside your script, try to run it from the command line.

**Comment by masoudline** [comment]
when i run these command:
```
solve-field -p --overwrite --scale-units degwidth --scale-low 25 --scale-high 35 --downsample 2 apod2.jpg --verbose
Reading input file 1 of 1: "apod2.jpg"...
Base: "./apod2", basefile "apod2.jpg", basedir ".", suffix "jpg"
Checking if file "apod2.jpg" ext 0 is xylist or image: image
  (not xyls because: Failed to open FITS table apod2.jpg: Failed to open FITS file "apod2.jpg")
Running: /usr/bin/python -m astrometry.util.image2pnm --sanitized-fits-outfile /tmp/tmp.sanitized.VIinoq --fix-sdss --infile apod2.jpg --uncompressed-outfile /tmp/tmp.uncompressed.und99q --outfile /tmp/tmp.ppm.eXgVVr --ppm
Usage: image2pnm.py [options]

image2pnm.py: error: no such option: --sanitized-fits-outfile
augment-xylist.c:588:backtick Failed to run command: /usr/bin/python -m astrometry.util.image2pnm --sanitized-fits-outfile /tmp/tmp.sanitized.VIinoq --fix-sdss --infile apod2.jpg --uncompressed-outfile /tmp/tmp.uncompressed.und99q --outfile /tmp/tmp.ppm.eXgVVr --ppm
 ioutils.c:567:run_command_get_outputs Command failed: return value 2

```

**Comment by dstndstn** [comment]
You still have some mixed up set of versions of the code.  I think you must have an old version of solve-field and a new version of the image2pnm.py script.

**Comment by masoudline** [comment]
ok that's right but i don't know how can i do it?

**Comment by masoudline** [comment]
I added one index-4200-27.fits to /usr/local/astrometry/data !!
what's new error? 
```
solve-field.c:518:run_engine engine failed.  Command that failed was:
  /usr/bin/astrometry-engine /home/roxo/unh-startracker-master/dataset//apod2.axy
 ioutils.c:567:run_command_get_outputs Command failed: return value 255
---------------------------------------------------------------------
You must list at least one index in the config file (/usr/bin/../etc/astrometry.cfg)

See http://astrometry.net/use.html about how to get some index files.
```

**Comment by dstndstn** [comment]
Look in the file /usr/etc/astrometry.cfg
You should see a line like

# In which directories should we search for indices?
add_path /usr/data/

either move the index file to that directory, or edit /usr/etc/astrometry.cfg to look in /usr/local/astrometry/data

An index file is like a map of the sky.

**Comment by dstndstn** [comment]
Note, index-4200-27 will not work to solve an image that is 25 degrees wide.  Instead, use index-4219.fits, index-4218.fits, ..., index-4215.fits.

**Comment by masoudline** [comment]
OK, that's right. thanks for your support
i have a question: 
which index file appropriate for celestial navigation from an camera images that put it on fix place?

**Comment by dstndstn** [comment]
The index files are described here:
http://astrometry.net/doc/readme.html#getting-index-files

The most important property of the image is how wide (in angle) it is.

If you want advice about your images, please post one to nova.astrometry.net and send a link to it.  Thanks.

**Comment by masoudline** [comment]
thanks for your answer. i can solve this issue. but i have some other problem:
when i want use plotaan.py with this command:
```
wcsString # this is a valid wcs string
command = '/usr/local/astrometry/bin/plotann.py --brightcat /home/roxo/unh-startracker-master/astrometry1/catalogs/brightstars.fits '+ wcsString
    print 'command is %s' %command
    sdProc = os.popen(command)
    starDict = sdProc.read()
    # put the dictionary in dictionary (instead of string) form
    starDict = json.loads(starDict)
    print "star dictionary == %s"%type(starDict)
    print starDict
```
output of Bight Catalog shown:
```
Bright-star catalog:  
Bright-star catalog: \u03b7 Ser 
Bright-star catalog: 59Ser 
Bright-star catalog: 60Ser 
Bright-star catalog: 61Ser 
Bright-star catalog: \u03b1 Sct 
Bright-star catalog:  
Bright-star catalog:  
Bright-star catalog:  
Bright-star catalog:  
Bright-star catalog: \u03b4 Sct 
Bright-star catalog: \u03b5 Sct 
Bright-star catalog: 4Aql 
Bright-star catalog:  
Bright-star catalog:  
Bright-star catalog: 5Aql 
Bright-star catalog: \u03b2 Sct 
Bright-star catalog:  
Bright-star catalog:  
Bright-star catalog:  
Bright-star catalog:  
Bright-star catalog: \u03b8 1Ser Alya
Bright-star catalog: \u03b8 2Ser 
Bright-star catalog: \u03b7 Sct 
Bright-star catalog: 64Ser 
Bright-star catalog:  
Bright-star catalog: 12Aql 
Bright-star catalog: 14Aql 
Bright-star catalog:  
Bright-star catalog: 15Aql 
Bright-star catalog: \u03bb Aql 
Bright-star catalog: 20Aql 
Bright-star catalog:  
Bright-star catalog: 21Aql 
Bright-star catalog: 23Aql 
Bright-star catalog: 26Aql 
Bright-star catalog: 27Aql 
Bright-star catalog: \u03c5 Sgr 
Bright-star catalog:  
Bright-star catalog:  
Bright-star catalog:  
Bright-star catalog: \u03bd Aql 
Bright-star catalog: 35Aql 
Bright-star catalog: 36Aql 
Bright-star catalog: 37Aql 
Bright-star catalog: \u03ba Aql 
Bright-star catalog: \u03b9 Aql 
Bright-star catalog:  
Bright-star catalog: 42Aql 
Bright-star catalog: 45Aql 
Bright-star catalog:  
[{"radius": 0.0, "names": ["\u03b7 Ser"], "pixelx": 3443.6442605851516, "pixely": 1955.096858341861, "vmag": 3.2000000000000002, "type": "bright"}, {"radius": 0.0, "names": ["59Ser"], "pixelx": 3484.7158520668045, "pixely": 1438.1923108581775, "vmag": 5.2000000000000002, "type": "bright"}, {"radius": 0.0, "names": ["60Ser"], "pixelx": 3236.2561747212826, "pixely": 1675.5427322848664, "vmag": 5.2999999999999998, "type": "bright"}, {"radius": 0.0, "names": ["61Ser"], "pixelx": 3236.1922381918957, "pixely": 1504.8895123054856, "vmag": 5.9000000000000004, "type": "bright"}, {"radius": 0.0, "names": ["\u03b1 Sct"], "pixelx": 2581.883065346984, "pixely": 2382.1931224112436, "vmag": 3.7999999999999998, "type": "bright"}, {"radius": 0.0, "names": ["\u03b4 Sct"], "pixelx": 2293.8099436196067, "pixely": 2352.8040360952596, "vmag": 4.7000000000000002, "type": "bright"}, {"radius": 0.0, "names": ["\u03b5 Sct"], "pixelx": 2312.3543819277947, "pixely": 2228.281644846741, "vmag": 4.9000000000000004, "type": "bright"}, {"radius": 0.0, "names": ["4Aql"], "pixelx": 3044.888688413234, "pixely": 865.1130536636905, "vmag": 5.0, "type": "bright"}, {"radius": 0.0, "names": ["5Aql"], "pixelx": 2764.1128492035195, "pixely": 1227.5633657497672, "vmag": 5.9000000000000004, "type": "bright"}, {"radius": 0.0, "names": ["\u03b2 Sct"], "pixelx": 2458.839967346989, "pixely": 1703.6344338970125, "vmag": 4.2000000000000002, "type": "bright"}, {"radius": 0.0, "names": ["\u03b8 1Ser", "Alya"], "pixelx": 2834.461880076679, "pixely": 373.2421959237647, "vmag": 4.5999999999999996, "type": "bright"}, {"radius": 0.0, "names": ["\u03b8 2Ser"], "pixelx": 2833.5760362364654, "pixely": 373.037478059117, "vmag": 4.9000000000000004, "type": "bright"}, {"radius": 0.0, "names": ["\u03b7 Sct"], "pixelx": 2059.287722730574, "pixely": 1661.9899228993918, "vmag": 4.7999999999999998, "type": "bright"}, {"radius": 0.0, "names": ["64Ser"], "pixelx": 2674.4641399644306, "pixely": 572.7798270850371, "vmag": 5.5, "type": "bright"}, {"radius": 0.0, "names": ["12Aql"], "pixelx": 1918.9400068110247, "pixely": 1563.1558220249367, "vmag": 4.0, "type": "bright"}, {"radius": 0.0, "names": ["14Aql"], "pixelx": 2029.8340739278194, "pixely": 1277.3200562148527, "vmag": 5.4000000000000004, "type": "bright"}, {"radius": 0.0, "names": ["15Aql"], "pixelx": 1939.278860028278, "pixely": 1282.5473752674175, "vmag": 5.4000000000000004, "type": "bright"}, {"radius": 0.0, "names": ["\u03bb Aql"], "pixelx": 1835.190150874494, "pixely": 1368.799411435231, "vmag": 3.3999999999999999, "type": "bright"}, {"radius": 0.0, "names": ["20Aql"], "pixelx": 1403.5467695661985, "pixely": 1647.1854888593548, "vmag": 5.2999999999999998, "type": "bright"}, {"radius": 0.0, "names": ["21Aql"], "pixelx": 2122.6149563587046, "pixely": 300.03840221317023, "vmag": 5.0999999999999996, "type": "bright"}, {"radius": 0.0, "names": ["23Aql"], "pixelx": 1876.2965399064262, "pixely": 368.46844881539425, "vmag": 5.0999999999999996, "type": "bright"}, {"radius": 0.0, "names": ["26Aql"], "pixelx": 1334.6299770600701, "pixely": 1176.7622061501784, "vmag": 5.0, "type": "bright"}, {"radius": 0.0, "names": ["27Aql"], "pixelx": 1664.1331911454054, "pixely": 588.4171305007536, "vmag": 5.4000000000000004, "type": "bright"}, {"radius": 0.0, "names": ["\u03c5 Sgr"], "pixelx": 513.7224167097368, "pixely": 2544.5971052011946, "vmag": 4.5999999999999996, "type": "bright"}, {"radius": 0.0, "names": ["\u03bd Aql"], "pixelx": 1561.4970836724833, "pixely": 317.7042970728021, "vmag": 4.5999999999999996, "type": "bright"}, {"radius": 0.0, "names": ["35Aql"], "pixelx": 1598.4768461166705, "pixely": 59.00849180774685, "vmag": 5.7999999999999998, "type": "bright"}, {"radius": 0.0, "names": ["36Aql"], "pixelx": 1196.997848151937, "pixely": 649.7100174307371, "vmag": 5.0, "type": "bright"}, {"radius": 0.0, "names": ["37Aql"], "pixelx": 481.6265327907606, "pixely": 1588.0307785676534, "vmag": 5.0999999999999996, "type": "bright"}, {"radius": 0.0, "names": ["\u03ba Aql"], "pixelx": 682.780452440767, "pixely": 1090.5452385264598, "vmag": 4.9000000000000004, "type": "bright"}, {"radius": 0.0, "names": ["\u03b9 Aql"], "pixelx": 1107.614073575668, "pixely": 340.4156415351082, "vmag": 4.2999999999999998, "type": "bright"}, {"radius": 0.0, "names": ["42Aql"], "pixelx": 826.9737175890116, "pixely": 761.8136745824778, "vmag": 5.4000000000000004, "type": "bright"}, {"radius": 0.0, "names": ["45Aql"], "pixelx": 1023.9858204245359, "pixely": 177.68786487623254, "vmag": 5.5999999999999996, "type": "bright"}]
```
but when i want run this code error appeared because json format is not valid.
and error:
```
  File "/home/roxo/unh-startracker-master/analysisAndPlots/maps/CPM.py", line 144, in getStarDict
    starDict = json.loads(starDict)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
can you help me?

**Comment by dstndstn** [comment]
Oops, this is a bug in plotann.py -- it shouldn't print those "Bright catalog" lines.

You could replace your /usr/local/astrometry/bin/plotann.py with the master version,
https://github.com/dstndstn/astrometry.net/blob/master/blind/plotann.py
or just comment-out line 138 that prints the "Bright catalog" lines.

**Comment by masoudline** [comment]
ok thanks.
i have another question.
i want to build a celestial navigation system and use it on my boat. so i will be used a camera and take a picture from night sky, i can't connect to internet and nova.astrometry.net website for search index-xx number and download it! 
how can i estimate index-xx number for search on taken picture from camea!???

special thanks for your favor and answer.

**Comment by dstndstn** [comment]
Hi,

The wide-field index files like index-4217.fits cover the whole sky, and each file covers a range of angular scales.

If you send an example image (or upload to nova.astrometry.net and send a link) I can give you specific advice.

**Comment by masoudline** [comment]
many images taken by the camera and I want to search for all images. how can I do it without internet !!

my project is real-time with variant images that taken with the camera!

**Comment by dstndstn** [comment]
Run the solve-field program on each image.

**Comment by masoudline** [comment]
I run send all images to solve-field but i dont know what index suitble?
In some image solve-field not found any object with index 4217

**Comment by dstndstn** [comment]
Like I said before, try using all files index-4215 to index-4219, if your images are ~20 degrees wide.
