### ISSUE TITLE
Invalid blocksize when creating a catalog

### ISSUE THREAD

**Issue by olebole** [dstndstn/astrometry.net#128]
Hi Dustin,

I am trying to create my own, specific catalog for a small field. Doing this, I found a memory problem; however I do not understand the code here completely: 
 * In `uniformize-catalog.c`, the `intmap_t* starlists` is [created with a block size 0](https://github.com/dstndstn/astrometry.net/blob/588ccb289983b615f0b784354114e7d7550c8e45/blind/uniformize-catalog.c#L228).
 * This is later used to [create an `bl *lst`](https://github.com/dstndstn/astrometry.net/blob/588ccb289983b615f0b784354114e7d7550c8e45/blind/uniformize-catalog.c#L257) with the same block size (0).
 * When later something is [added to `lst`](https://github.com/dstndstn/astrometry.net/blob/588ccb289983b615f0b784354114e7d7550c8e45/blind/uniformize-catalog.c#L282), this results in (first) a [wrong allocation](https://github.com/dstndstn/astrometry.net/blob/588ccb289983b615f0b784354114e7d7550c8e45/util/bl.c#L394) (just the node itself, but no space for data), followed by [copying](https://github.com/dstndstn/astrometry.net/blob/588ccb289983b615f0b784354114e7d7550c8e45/util/bl.c#L439) an `int32` to the data area. 

This may be reproduced by using valgrind, or with `CFLAGS`/`LDFLAGS` set to `-fsanitize=address`.

At least, this corrupts the data. I see a `free(): corrupted unsorted chunks` abort of `build-astrometry-index` with my data. I also will continue debugging...

I hope this is not too confusing and can help you :-)

**Comment by dstndstn** [comment]
Apologies for the year-long delay!

It looks like if an intmap is initialized with blocksize=0, it defaults to 4096:
https://github.com/dstndstn/astrometry.net/blob/master/util/intmap.c#L19

Would you be able to send an example data set + command line that was showing this?

**Comment by olebole** [comment]
Sorry, I finally solved this by implementing my own algorithm (based on kd-match from J.S. Heyl), and so I removed the data set since then...

**Comment by dstndstn** [comment]
okay, sorry for the trouble!
