### ISSUE TITLE
tmp files not removed when solve-field exit code != 0

### ISSUE THREAD

**Issue by Zlika** [dstndstn/astrometry.net#130]
Hi!

This issue is linked to #45.
I use version 0.74.
When processing some bad quality images (clouds, wrong exposition...), sometimes solve-field exits with a non-zero exit code. In these situations, it seems that solve-field "forgets" to remove its temporary files  (tmp.uncompressed.xxxx, tmp.ppm.xxxx, tmp.xyls.xxxx, tmp.removelines.xxxx) from the /tmp folder.

For example on one of the images I have the following result:
```Extracting sources...
simplexy: found 1 sources.
/usr/local/astrometry/lib/python/astrometry/util/removelines.py:23: RuntimeWarning: divide by zero encountered in log
  logpoisson = k*np.log(mean) - mean - np.array([sum(np.arange(kk)) for kk in k])
/usr/local/astrometry/lib/python/astrometry/util/removelines.py:23: RuntimeWarning: invalid value encountered in multiply
  logpoisson = k*np.log(mean) - mean - np.array([sum(np.arange(kk)) for kk in k])
Traceback (most recent call last):
  File "/usr/local/astrometry/bin/removelines", line 15, in <module>
    sys.exit(main())
  File "/usr/local/astrometry/lib/python/astrometry/util/removelines.py", line 76, in main
    cut=opt.cut, ext=opt.ext)
  File "/usr/local/astrometry/lib/python/astrometry/util/removelines.py", line 45, in removelines
    iy = hist_remove_lines(T.get(ycol), 1, 0.5, logcut=-cut)
  File "/usr/local/astrometry/lib/python/astrometry/util/removelines.py", line 22, in hist_remove_lines
    mean = sum(k) / float(noccupied)
ZeroDivisionError: float division by zero
augment-xylist.c:589:backtick Failed to run command: /usr/local/astrometry/bin/removelines /tmp/tmp.xyls.mqkdFy /tmp/tmp.removelines.DtNqdV
 ioutils.c:567:run_command_get_outputs Command failed: return value 1
```
I know that the origin of the problem is that the image I try to analyze is not correct, but I process lots of images in an automated way, so it would be nice if solve-field could properly handle these non nominal cases.

Regards

**Comment by dstndstn** [comment]
Thanks for this bug report.  Could you please post an example image?  From the stack trace (thank you!) I can see what is probably going wrong, but it is always nice to be able to reproduce the bug, fix the problem, and see the bug go away.

(My guess is that no stars are being detected.)

**Comment by dstndstn** [comment]
or alternatively, could you please pull from master and see if the commit I just made fixes it?
thx

**Comment by dstndstn** [comment]
Thanks!
