### ISSUE TITLE
Cannot post JSON request to astrometry.net API

### ISSUE THREAD

**Issue by PawelPleskaczynski** [dstndstn/astrometry.net#131]
Hello, I'm making a React app that uses astrometry.net API, and I can't post any JSON request. My code looks like this:
```
fetch("https://cors-anywhere.herokuapp.com/http://nova.astrometry.net/api/login", {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      apikey: key
    }),
  })
  .then(function(res) {
    return res.json();
  })
  .then(function(data) {
    console.log(data)
  });
```
and I'm getting this response in console: `{status: "error", errormessage: "no json"}`. I don't know what am I doing wrong, is there any way to make it work? Thanks

**Comment by dstndstn** [comment]
You skipped step 2 in the list at the top of 
http://astrometry.net/doc/net/api.html

1. Form the JSON object:
      {"apikey": "XXXXXX"}

2. Form the x-www-form-encoded string:
        request-json={"apikey": "XXXXXX"}
    which becomes:
        request-json=%7B%22apikey%22%3A+%22XXXXXX%22%7D

3. Send that to the “login” API URL as a POST request:
            http://nova.astrometry.net/api/login

**Comment by PawelPleskaczynski** [comment]
Ah, I didn't read that part carefully 😅

Thank you!

**Comment by bigansh** [comment]
```
axios({
    method: 'post',
    url: 'http://nova.astrometry.net/api/login',
    data: {
        'request-json': JSON.stringify({ "apikey": "process.env.API_KEY" })
    }
}).then((response) => {
    console.log(response.data)
});
```

I still get ```{ status: 'error', errormessage: 'no json' }```. Why?

**Comment by dstndstn** [comment]
Is your library sending it with *x-www-form-encoded *encoding?  It must be
sent exactly as though it is a text box in a form.
