### ISSUE TITLE
Some general installation questions

### ISSUE THREAD

**Issue by DriftingPig** [dstndstn/astrometry.net#133]
Hi dstndstn,
I'm following [this page](http://astrometry.net/doc/build.html) and the [.travis file](https://github.com/dstndstn/astrometry.net/blob/master/.travis.yml)  to do the installation. I need to do the version with prefix, so I can't do commands like `sudo apt-get install...`. Are there any equivalent commands?
I'm not very familiar with C package installations. Now the issue is that when I try to do the test run in util/test, it says:
```
anwcs.c:959:anwcs_wcslib_from_string: Wcslib support was not compiled in
anwcs.c:1711:anwcs_create_mercator_2: Failed to parse Mercator header string with wcslib
RA,Dec in corners:
Segmentation fault (core dumped)
```
If I link `-I -L` WCS I installed locally on it, it will have failure like the code below:
```
There was 1 failure:
1) test_fitsbin_2: test_fitsbin.c:137: null pointer unexpected

!!!FAILURES!!!
Runs: 122 Passes: 121 Fails: 1
```
and I think using `-I -L` is also not the right way to solve it. 

Can you tell me what to do to install it locally with all the dependent packages (also locally?)

Thanks,
Hui

**Comment by DriftingPig** [comment]
Hi,
I'm finally able to use it with a docker image, but I'm still curious about how to install it without any 'sudo'

**Comment by dstndstn** [comment]
Hi,

It turns out that there was a bug in the code tested by test_fitsbin.c, so that test failing does not necessarily mean that your attempt didn't work!  I pushed a bugfix to the master version of the code -- if you could test that, could you please.

cheers,
--dustin
