### ISSUE TITLE
Support conda?

### ISSUE THREAD

**Issue by jamessynge** [dstndstn/astrometry.net#138]
I'm working with a large set of packages installed using conda, including many required to build astrometry. I'd love to be able to install astrometry with a simple `conda install astrometry` command. Barring that, I'd like to build astrometry using the libraries and programs installed using conda, rather than needing to use apt-get to install them.

Would you support conda directly? Or do you have advice on building with conda libraries?

**Comment by dstndstn** [comment]
I don't really know anything about conda packaging.  How does one go about getting a package into the conda ecosystem?

Maybe this is related?  It's a conda wrapper we use as part of the DESI project:
https://github.com/desihub/desiconda/blob/master/rules/astrometry_net.sh

**Comment by wtgee** [comment]
Hi @dstndstn, I haven't gone through any of the work for doing a C-based package, but basic instructions are at: https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html

Gave a :+1: but I am working on the same project as @jamessynge :).

There are currently three astrometry.net packages out there: https://anaconda.org/search?q=astrometry

One is a recent 0.75 version from someone but when I tried it in a clean environment the libcfitsio libraries seemed to be linking incorrectly.  The other two are from the LSST but are stale. This was a discussion we had somewhat with @timj back in #89. This was pre python3.x so I think it was a show stopper for them and I think LSST ended up doing a separate astrometric solution.

But definitely want to echo that this would be helpful. Python is somewhat de facto for many astronomers, along with the scipy/astropy ecosystem.  Anaconda is becoming a good standard for package management in those communities.

**Comment by timj** [comment]
The LSST conda packages are old eups packages and are not usable if you don't have eups installed. LSST is currently using a version of astrometry.net from git that had enough python3 support to get us through.

**Comment by wtgee** [comment]
Maybe this is a good hack-day topic for AAS in Jan. ;)  

I think many people would benefit from having a conda package available in the astropy channel. That said, it needs to be something that eases burden on @dstndstn, not increases.

Ideally it'd be great to also have the website (nova) removed from the main repo that is responsible for the plate-solving as I think that would ease long-term maintenance and minimize dependencies. But that's for another Issue.

**Comment by juliotux** [comment]
Hello everyone,

@wtgee, I'm the maintener that put that astrometry.net version 0.75 in Anaconda cloud. I know the linking problem (it is linked against my system cfitsio for some unkown reason).

I created a repository containing all the needed recipes for astrometry.net (astrometry.net itself, cfitsio and netpbm). All the other packages can be found in the Anaconda default repositories. The recipe git is  https://github.com/juliotux/astrometry-conda

Basically it should work if you build in your Anaconda and everything needed is there.

Currently, I'm getting a strange compiling error in 2masstofits.c (not founding zlib.h, which is correctly installed). I compiled this in a clean ubuntu 18.10 environment with all dependencies installed via anaconda. Could you test these recipes for me? @jamessynge @timj @dstndstn

To build it, just go to `astrometry.net` directory and run `conda build -c juliotux .`
`netpbm` and `cfitsio` packages are already built without problem in the clean ubuntu environment, so they have to run correctly in your computers.

Please report success or fails in the build!

Thanks

**Comment by juliotux** [comment]
Hello people,

Now, I got my recipes compiling. I uploaded alread a package version to Anaconda cloud. So, to install and test the package, just do `conda install -c juliotux astrometry.net`.

The recipes are in https://github.com/juliotux/astrometry-conda if you want to give an official support.

**Comment by wtgee** [comment]
> Hello people,
> 
> Now, I got my recipes compiling. I uploaded alread a package version to Anaconda cloud. So, to install and test the package, just do `conda install -c juliotux astrometry.net`.
> 
> The recipes are in https://github.com/juliotux/astrometry-conda if you want to give an official support.

Awesome, thanks @juliotux I'll give it a try today. Sorry I didn't get a chance to help you test it earlier.

**Comment by juliotux** [comment]
Just to update. I'm working to put `astrometry.net` in conda-forge. For who want to contribute (specially with the OSX building part) the pull request discussion is: https://github.com/conda-forge/staged-recipes/pull/8879

**Comment by juliotux** [comment]
`astrometry` is now available in `conda-forge` channel!

[![Anaconda-Server Badge](https://anaconda.org/conda-forge/astrometry/badges/installer/conda.svg)](https://conda.anaconda.org/conda-forge) `conda install -c conda-forge astrometry`

**Comment by juliotux** [comment]
Now available for MacOS too in conda-forge.

**Comment by hjmcc** [comment]
Great work @juliotux ! It's fantastic to have an easily-installable version of asrometry.net.  On my mac it works (mostly) fine. No plots are produced, however, it claims that netbpm is not installed: 

```
airoutils.c:715:cairoutils_read_ppm_stream: Netpbm is not available; can't read PPM imagescairoutils.c:715:cairoutils_read_ppm_stream: Netpbm is not av\
ailable; can't read PPM images

cairoutils.c:715:cairoutils_read_ppm_stream: Netpbm is not available; can't read PPM images
cairoutils.c:715:cairoutils_read_ppm_stream: Netpbm is not available; can't read PPM images

```
I have seen this bug mentioned in the astometry.net forums, usually because netbpm is not linked and compile time. But surely this is the case (i see you are maintainter also of netpbm packages). 

Thanks!

**Comment by hjmcc** [comment]
hi again @juliotux just to be sure I tested on one of our linux servers (CentOS Linux release 7.7.1908) and the error message is the same:

```
Running: /home/hjmcc/miniconda3/envs/py36-keras-nogpu/bin/plotxy -I /tmp/tmp.pp\
m.BURHSJ -i ./ACO_1656-001B.axy -C red -w 2 -N 50 -x 1 -y 1 -P | /home/hjmcc/mi\
niconda3/envs/py36-keras-nogpu/bin/plotxy -i ./ACO_1656-001B.axy -I - -w 2 -r 3\
 -C red -n 50 -N 200 -x 1 -y 1 > ./ACO_1656-001B-objs.png
cairoutils.c:715:cairoutils_read_ppm_stream: Netpbm is not available; can't rea\
d PPM images

```
if anyone knows a way of getting the plots it would be great!

**Comment by juliotux** [comment]
Hello guys, I'm investigating the problem. I hope the problem can be solved soon.

**Comment by dstndstn** [comment]
You might have to do, eg,
```
export NETPBM_INC="-I/usr/local/include/netpbm -I/usr/local/include"
export NETPBM_LIB="-L/usr/local/lib -lnetpbm"
```
if you want to tell it which netpbm to use.

**Comment by juliotux** [comment]
@dstndstn @hjmcc I noticed that `astrometry.net` did not recognized `netpbm` installed if `-I/usr/local/include/netpbm` not included (due to `pam.h` instead of `netpbm/pam.h` in source files). This caused `HAVE_NETPBM 0` in `os_features_config.h`, as shown by [build_log:L665](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=118121&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=665), so `plotxy` did not had correct linking. I'm fixing this bug (and others) in https://github.com/conda-forge/astrometry-feedstock/pull/6 and soon it will be at `conda-forge`.

**Comment by juliotux** [comment]
@dstndstn we are having another problem for supporting `astrometry` in Conda-Forge. It looks like that, when compiling in docker/azure, some parts of the code calls illegal instructions due to wrong CPU detection. Is there any way to override `astrometry.net` make CPU detection and/or override `CFLAGS`? I think this is the origin of https://github.com/juliotux/astrometry-conda/issues/2

**Comment by dstndstn** [comment]
Check out the comment here; try setting the ARCH_FLAGS= variable to
override out auto-detection -- which just uses gcc's -march=native option
when available.
https://github.com/dstndstn/astrometry.net/blob/master/util/makefile.common#L165

cheers,
--dustin

**Comment by juliotux** [comment]
@dstndstn thanks for the help. I noticed that the `CFLAGS` where introduced by conda-forge CI. However, the core dump problem remains. I described it with all debug I got in https://github.com/conda-forge/astrometry-feedstock/issues/10
I'm testing manual override the `CFLAGS` var with more generic ISA.

**Comment by dmopalmer** [comment]
After too many hours of trying to get it installed from source on my new Mac, I decided to check whether it was an anaconda package.

I just installed the -c conda-forge version from end of March.  It just installed, and after pointing the .cfg file at my indices, it just worked.

(How should anaconda deal with getting the indices though?)

When this is all stabilized, it should definitely go into the build instructions as an easier way to do things at least on the Mac.

Thanks.

**Comment by dstndstn** [comment]
Feel free to send a pull request with the changes to the documentation.  (Personally, I prefer installing with Homebrew on Mac.)

**Comment by dmopalmer** [comment]
The anaconda build has libwcs.7.2 hard-coded in the package.  (I grep the pre-compiled binaries in the [anaconda package](https://anaconda.org/conda-forge/astrometry/0.80/download/osx-64/astrometry-0.80-py36hbccd985_0.tar.bz2) tar file and see @rpath/libwcs.7.2.dylib )

It breaks if a different version of wcslib is installed.  (Other dependencies have me stuck at libwcs.5)  Therefore it will break when libwcs.7.3 becomes an anaconda package.

I don't know the anaconda build system, but there is presumably some way to make it use any libwcs above a certain version (or failing that, pinning 7.2 as a requirement.)

**Comment by tosaric** [comment]
Hi, I installed it via conda-forge, but don't know how to run it.
I can import astrometry, but what is the syntax for running it?
I couldn't find any documentation about it.

**Comment by juliotux** [comment]
> Hi, I installed it via conda-forge, but don't know how to run it.
> I can import astrometry, but what is the syntax for running it?
> I couldn't find any documentation about it.

astrometry.net is not a python library, it is a standalone program. The documentation is in [astrometry.net readme](http://astrometry.net/doc/readme.html).

**Comment by tosaric** [comment]
Oh, I see, my bad.
I am already using astrometry.net but as I saw conda installation I thought I could install and run it as a python library.
Anyway, after installing it with conda I can use it the same way as if I did installation the usual way?
That is amazing.

**Comment by juliotux** [comment]
@dstndstn , please look at the bug https://github.com/conda-forge/astrometry-feedstock/issues/29 
For some reason, the python libraries are getting installed in the wrong place, under `lib/python` instead of `lib/python3.x`. May be using [this python path detection](https://github.com/dstndstn/astrometry.net/blob/575ad17bdc9a7f7e6ee7609073e89be1297d8251/Makefile#L186) is leading to wrong results.
What could I do to fix the problem in the package?

**Comment by dstndstn** [comment]
Yes, that's on purpose.  The python install path is set here.
https://github.com/dstndstn/astrometry.net/blob/main/util/makefile.common#L24

You can override it by setting that PY_BASE_INSTALL_DIR environment variable.

**Comment by dstndstn** [comment]
Or send a PR that builds the expected path in the Makefile.

Maybe something like
PY_BASE_INSTALL_DIR ?= $(shell $(PYTHON) -c "from sys import version_info as v; print('$(INSTALL_DIR)/lib/python%i.%i/astrometry' % (v.major,v.minor))")
would work?

**Comment by dstndstn** [comment]
Actually probably cleaner to do it in two lines,
PY_VER ?= $(shell $(PYTHON) -c "from sys import version_info as v; print('python%i.%i' % (v.major,v.minor))")
PY_BASE_INSTALL_DIR ?= $(INSTALL_DIR)/lib/$(PY_VER)/astrometry

**Comment by tosaric** [comment]
@juliotux Hi, after installing astrometry via conda forge command, I noticed that not all astrometry helper scripts gets downloaded, for example, util directory(location /opt/miniconda3/envs/astrometry/lib/python/astrometry/util
) only containes a few scripts, while it should contain many more(https://github.com/dstndstn/astrometry.net/tree/main/util).

**Comment by juliotux** [comment]
@tosaric all the building steps are used in the [recipe](https://github.com/conda-forge/astrometry-feedstock/blob/0adea309df5b8846441106665657e9d9bf6bd920/recipe/build.sh#L35). So, it should have all the same tools. What utils are you missing?

**Comment by tosaric** [comment]
Hi @juliotux, thanks for such a quick response.
For example, I am missing plotSipDistortion.py.
Here is full list of my /opt/miniconda3/envs/astrometry/lib/python/astrometry/util directory: 

EXIF.py	fix_sdss_idr.py			removelines.py			timingpool.py
__init__.py			horizons.py			resample.py			ttime.py
__pycache__			image2pnm.py			run_command.py			uniformize.py
_util.cpython-39-darwin.so	imageutils.py			shell.py			usnob_catalog.py
addpath.py			miscutils.py			siap.py				usnob_get_image.py
file.py				multiproc.py						usnob_get_region.py
filetype.py			stages.py			util.py
find_data_file.py		plotshift.py			starutil.py
fits.py				plotutils.py			starutil_numpy.py

**Comment by tosaric** [comment]
@juliotux I updated astrometry from 0.89 to 0.9 via conda-forge, but the utils are still missing

**Comment by juliotux** [comment]
@tosaric trying locally the installation I found that the astrometry.net make procedure only install these utils that you list. So, there is no missing file in the package compared to a default system install.

**Comment by tosaric** [comment]
@juliotux Thanks for your help. I can open another issue regarding those util files.
