### ISSUE TITLE
Website is out

### ISSUE THREAD

**Issue by mrprompt** [dstndstn/astrometry.net#139]
astronometry.net host is show `Connection Refused` error.

**Comment by dstndstn** [comment]
thanks for the report -- we're investigating.  Looks like a failed hard drive.

**Comment by jamessynge** [comment]
It was working for a while since being reopened, but is now failing again. Clearly I need to create a cache for my travis-ci builds to read from.

**Comment by yumoraby** [comment]
Is there an ETA for when this service will be back again? Seems a bit long for just a failed Hard Drive

**Comment by dstndstn** [comment]
The nova.astrometry.net service is back.

The data.astrometry.net site has been migrated to new hardware.

The astrometry.net web site will be down for some time.
