### ISSUE TITLE
Security Risk Host error

### ISSUE THREAD

**Issue by mrprompt** [dstndstn/astrometry.net#140]
http://nova.astrometry.net/upload showing Security Risk error

**Comment by rrgupta** [comment]
FYI, emailing the NYU IT desk (AskIT@nyu.edu) as the page suggests does *not* help and results in the following friendly response:

> Since you're not on our network and that you are accessing a service that is not ours. 

> We have no control of this service, it is not owned by NYU. we are now closing this ticket as we are unable to assist. 

:persevere:

**Comment by dstndstn** [comment]
I'm working on it
