### ISSUE TITLE
client.py malforms FITS file if run in Python 3

### ISSUE THREAD

**Issue by ppapadeas** [dstndstn/astrometry.net#147]
This is the same fits uploaded via client.py running in Python 2:
http://nova.astrometry.net/user_images/2520401#original

and in Python 3:
http://nova.astrometry.net/user_images/2520393#original

There seems to be some malformity introduced when running client.py in Python 3

**Comment by dstndstn** [comment]
fixed in 5500c7291c3710ce1c65476beefd03b5bd91bad0
