### ISSUE TITLE
Time to switch to Python 3 as default?

### ISSUE THREAD

**Issue by olebole** [dstndstn/astrometry.net#148]
Hi Dustin,

as a continuation of #87, it may be a good idea to switch to Python 3 as default at some point. The reason is, that Python 2 get less supported anymore, and the tail of dependent packages now starts to break: For Python 2, one is limited to use astropy 2.0.X, which is now going to be limited to pytest <3.10 (see astropy/astropy#8173). And since Debian now has upgraded to pytest 3.10 (and probably may go to pytest 4 soon, see [Debian#914592](https://bugs.debian.org/914592)), we would be forced to leave astropy untested there, which will lower its quality.
The Python package of astrometry.net that we ship is however still Python 2, and is one of the very few packages where we don't have a Python 3 pendant; and I also don't want to start building both.
Therefore, I will switch that package to Python 3 soon. Probably, it is mainly replacing the bang path `#!/usr/bin/env python` to `python3`, right? Once I have tested the change, I could provide an PR.

**Comment by dstndstn** [comment]
Hi Ole,

In my world:
```
> python --version
Python 3.7.0
```
so I'm fine with this :)

If you run:
```
make install PYTHON_SCRIPT=/usr/bin/env python3
```
it will replace all the bang paths on install.

**Comment by dstndstn** [comment]
PS, if you want to replace the bang paths in the scripts, please also change util/makefile.common : PYTHON_SCRIPT_DEFAULT so that users can still revert to plain old `python` using the PYTHON_SCRIPT trick above.
thanks!

**Comment by lupinix** [comment]
Just for info: We made that step in Fedora packaging starting with Fedora 29 without any issues so far :)

**Comment by olebole** [comment]
@lupinix if you already have a patch, feel free to take over ;-)

**Comment by ppapadeas** [comment]
Be advised that there are some issues like #147 that might be blocking transition to Python3

**Comment by olebole** [comment]
@ppapadeas Can you give a specific command or input that failed?

**Comment by ppapadeas** [comment]
@olebole Running client.py for submitting images with python 2.x works perfectly. Running it on python 3.x does not fail locally, but the submitted image is malformed. See #147 for the image links.

**Comment by DerPit** [comment]
> If you run:
> 
> ```
> make install PYTHON_SCRIPT=/usr/bin/env python3
> ```
> it will replace all the bang paths on install.

This is what I finally found when having issues on my openSUSE Tumbleweed  (It still has 2.7 as default, but no longer supplies astropy for this version).
Everything works indeed, however not all paths are replaced.  bin/plotann.py is a symbolic link to ../lib/python/astrometry/blind/plotann.py, and that file is not changed, so it would still contain "/usr/bin/env python" and thus run python2.7

**Comment by ppapadeas** [comment]
@olebole did you have a chance to check #147 ?

**Comment by wtgee** [comment]
It would be nice to get the actual default switched to Python3 so that the various OSes will have a python3 packaged version in time for the EOL.  For instance, it would be great to have a python3 version in Ubuntu 19.10.  Currently I'm building some Ubuntu 19.04 docker images and would like to just use the system astrometry.net but that pulls in a whole bunch of python2 dependencies that cause bloat.

While the above method works for one-off installs the default really needs to be switched at some point in the next 6 months, ideally sooner.

@dstndstn I'm still a bit confused as to what would actually be required to switch it to python3 at this point. Happy to try and hep if we can get an overview of what needs to be done. Otherwise I'll try to dive in at some point (but have been saying that for months...)

**Comment by olebole** [comment]
@ppapadeas I didn't; mainly because I am not familiar with the upload/processing of images to nova.a.n, we deliver astrometry.net on Debian for local processing.
And there is no `client.py` in the sources, and also not in (my) installed version.
For Debian/Ubuntu, we switched to Python 3 in last November (for Debian Buster), and did not get a bug report so far.

**Comment by ppapadeas** [comment]
@olebole This is the code in the sources:
https://github.com/dstndstn/astrometry.net/blob/master/net/client/client.py

And unfortunately it still does not work for python 3 (malforming the uploaded files)

**Comment by olebole** [comment]
That is at least not part of the tarballs, which are used to create a local installation (and for the Debian and probably other OS's packages).

**Comment by dstndstn** [comment]
@wtgee I don't really know, but I guess a couple of the scripts start with
`#! /usr/bin/env python`
and one would set them to `python3` instead?

Personally, python=python3;

> python --version
Python 3.7.2

**Comment by dstndstn** [comment]
#147 is fixed.

**Comment by dstndstn** [comment]
I also just did a sweep through and changed all the "/usr/bin/env python"s to python3.  We'll see what breaks...

**Comment by dstndstn** [comment]
Travis build is working again, though the coverage of that test suite is not high.

Closing this issue for now, assuming that the switch to Python3 as the default Just Worked.
