### ISSUE TITLE
Allow for compressed (fz) file upload

### ISSUE THREAD

**Issue by wtgee** [dstndstn/astrometry.net#149]
Would be great if I could send fpacked files to nova.astrometry.net. I was going to just submit a PR but I'm having a hard time finding the `process_submissions.py` file that is referred to. TBH, I'm not even sure if this is the correct repo. 

If you can point me in the direction I can work on a PR. Thanks!

**Comment by dstndstn** [comment]
It should be in net/process_submissions.py in the astrometry.net repo

**Comment by wtgee** [comment]
> It should be in net/process_submissions.py in the astrometry.net repo

Thanks. I've spent some time trying to track this down and think that ultimately the problem comes from a bad call to [`fitsio.read_header()`](https://github.com/esheldon/fitsio/blob/master/fitsio/fitslib.py#L109) from inside the [`uncompress_file`](https://github.com/dstndstn/astrometry.net/blob/588ccb289983b615f0b784354114e7d7550c8e45/util/image2pnm.py#L98) method. `read_header()` doesn't actually allow for `ext=None` to be called (note that [`fitsio.read()`](https://github.com/esheldon/fitsio/blob/master/fitsio/fitslib.py#L40) does allow this) but `uncompress_file` is just silently dropping this exception (as far as I can tell).

There's a couple of possible solutions for detecting what the correct `extension` would be but I'll admit I'm confused as to _where_ that should happen. Easiest would be to alter the [`get_cmd`](https://github.com/dstndstn/astrometry.net/blob/588ccb289983b615f0b784354114e7d7550c8e45/util/image2pnm.py#L88) directly above this to properly distinguish between a regular FITS file and an fpacked file, but I'm unsure if that is the best place because I'm having a hard time tracing all the pathways to `uncompress_file`. Any pointers would be appreciated.  Thanks!

**Comment by dstndstn** [comment]
finally done in 2d7d29ac6c70f1b308f70bf14d56f79796e06d2d
