### ISSUE TITLE
basic implementation problem?

### ISSUE THREAD

**Issue by ssspun** [dstndstn/astrometry.net#153]
greetings,

i'm awful with software installation, but i'm trying to install astrometry.net software on my mac, running Sierra and with Python 2.7.15 and numpy 1.16.1.  i have no problems using numpy for my python algorithms...  i tried installing astrometry.net software using homebrew.  i don't think there were any problems with its installation...:

> brew reinstall astrometry-net
> ==> Reinstalling astrometry-net 
> ==> Downloading https://homebrew.bintray.com/bottles/astrometry-net-0.76_2.sierra.bottle.tar.gz
> Already downloaded: /Users/hurricane/Library/Caches/Homebrew/downloads/a04f4a74af4f1eeaf32966982ca1f6b307dd6aa299dcb570978049a2931eac17--astrometry-net-0.76_2.sierra.bottle.tar.gz
> =º  /usr/local/Cellar/astrometry-net/0.76_2: 823 files, 31.8MB
> 

but when i try to implement the software, i get this message:

> Reading input file 1 of 1: "/Users/hurricane/combc7361t0302o00.fits"...
> Extracting sources...
> simplexy: found 218 sources.
> Traceback (most recent call last):
>   File "/usr/local/opt/numpy/lib/python3.7/site-packages/numpy/core/__init__.py", line 16, in <module>
>     from . import multiarray
>   File "/usr/local/opt/numpy/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
>     from . import overrides
>   File "/usr/local/opt/numpy/lib/python3.7/site-packages/numpy/core/overrides.py", line 6, in <module>
>     from numpy.core._multiarray_umath import (
> ImportError: dlopen(/usr/local/opt/numpy/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Symbol not found: ___addtf3
>   Referenced from: /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/removelines", line 14, in <module>
>     from astrometry.util.removelines import main
>   File "/usr/local/Cellar/astrometry-net/0.76_2/libexec/lib/python3.7/site-packages/astrometry/util/removelines.py", line 10, in <module>
>     import numpy as np
>   File "/usr/local/opt/numpy/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
>     from . import core
>   File "/usr/local/opt/numpy/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
>     raise ImportError(msg)
> ImportError: 
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the multiarray numpy extension module failed.  Most
> likely you are trying to import a failed build of numpy.
> Here is how to proceed:
> - If you're working with a numpy git repository, try `git clean -xdf`
>   (removes all files not under version control) and rebuild numpy.
> - If you are simply trying to use the numpy version that you have installed:
>   your installation is broken - please reinstall numpy.
> - If you have already reinstalled and that did not fix the problem, then:
>   1. Check that you are using the Python you expect (you're using /usr/local/Cellar/astrometry-net/0.76_2/libexec/bin/python3),
>      and that you have no directories in your PATH or PYTHONPATH that can
>      interfere with the Python and numpy versions you're trying to use.
>   2. If (1) looks fine, you can open a new issue at

>      https://github.com/numpy/numpy/issues.  Please include details on:
>      - how you installed Python
>      - how you installed numpy
>      - your operating system
>      - whether or not you have multiple versions of Python installed
>      - if you built from source, your compiler versions and ideally a build log
> 
>      Note: this error has many possible causes, so please don't comment on
>      an existing issue about this - open a new one instead.
> 
> Original error was: dlopen(/usr/local/opt/numpy/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Symbol not found: ___addtf3
>   Referenced from: /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
> 
> augment-xylist.c:589:backtick Failed to run command: /usr/local/bin/removelines /tmp/tmp.xyls.VOgvwl /tmp/tmp.removelines.MB7eWl
>  ioutils.c:567:run_command_get_outputs Command failed: return value 1
> 

within python, here are my paths:

> >>> import sys

> >>> print '\n'.join(sys.path)
> 
> /usr/local/bin
> /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
> /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7
> /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
> /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
> /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
> /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
> /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
> /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
> /usr/local/lib/python2.7/site-packages
> /usr/local/lib/python2.7/site-packages/virtualenv-15.1.0-py2.7.egg
> /usr/local/lib/python2.7/site-packages/ATpy-0.9.7-py2.7.egg
> >>> np.__file__
> '/usr/local/lib/python2.7/site-packages/numpy/__init__.pyc'

help?

**Comment by ssspun** [comment]
thank you for the quick response!  you're right, i did get about the same error message when trying the print command you suggested.  i tried the brew commands after, but i still get the same error message when trying to use the "solve-field" command.  i tried uploading the image into the online version of astrometry.net and got a reasonable solution, so i don't think that's the problem...

**Comment by dstndstn** [comment]
Yeah, this definitely looks like a problem with the way our homebrew
formula is using python / numpy, rather than an actual problem in the
astrometry.net code.

So, could you please try homebrew installing python3, and seeing if a
brewed python3 can import numpy?

Thanks

**Comment by ssspun** [comment]
i'm a little hesitant to try installing a different version of python because my research group uses 2.7...  would homebrew installing python3 write over my default python version?

**Comment by dstndstn** [comment]
I *believe* Homebrew does *not* overwrite python; for python3 you have to run "python3".

Python2 is being phased out very quickly....

**Comment by ssspun** [comment]
it looks like python3 is already on my machine:
```
> brew install python3
Warning: python 3.7.2_1 is already installed and up-to-date
To reinstall 3.7.2_1, run `brew reinstall python`

```
i called it with "python3" and was able to import numpy - the version is 1.16.1

**Comment by ssspun** [comment]
hmm... tried that just now and got the following:

```
Total CPU time limit reached!
Field 1 did not solve (index index-4202-06.fits, field objects 81-90).
Field: combc7361t0302o00.fits
Did not solve (or no WCS file was written).

```

**Comment by dstndstn** [comment]
Did you say you submitted this image to the web service?  Could you please
send a link to that?

You might consider trying the Gaia-based "5000-series" index files, here,
http://data.astrometry.net/5000/

What is the full command line you were using?

**Comment by ssspun** [comment]
sure, here's the link: [http://nova.astrometry.net/user_images/2647298#redgreen](url)

and the command:

`solve-field --uniformize 0 --no-remove-lines --scale-units arcsecperpix --scale-low 0.4 --scale-high 0.5 combc7361t0302o00.fits`

**Comment by dstndstn** [comment]
And which index files do you have?  I saw 4206 mentioned.  You might want
to also get the "05" ones (4205 or 5005).

**Comment by dstndstn** [comment]
Oh, and check the source extraction image (is there a *-objs.png plot?), or
try "--downsample 2", which is the default in the web service.

**Comment by ssspun** [comment]
i only have the 4205 index files, not the 50* series.  

tried the downsampling and...  huzzah!!  success!  

```
Field 1: solved with index index-4206-05.fits.
Field 1 solved: writing to file ./combc7361t0302o00.solved to indicate this.
Field: combc7361t0302o00.fits
Field center: (RA,Dec) = (100.435372, 29.115939) deg.
Field center: (RA H:M:S, Dec D:M:S) = (06:41:44.489, +29:06:57.381).
Field size: 29.0437 x 29.0478 arcminutes
Field rotation angle: up is 0.637352 degrees E of N
Field parity: neg
Creating new FITS file "./combc7361t0302o00.new"...
Creating index object overlay plot...
Creating annotation plot...

```
i checked that it worked on a different image and in a different directory, and all looks well.  thank you so much!

**Comment by dstndstn** [comment]
Glad to hear it -- sorry for the roundabout tour to get there!
