### ISSUE TITLE
removelines.py: 0 * NaN if 1 star in a row

### ISSUE THREAD

**Issue by dstndstn** [dstndstn/astrometry.net#165]
/usr/local/astrometry/lib/python/astrometry/util/removelines.py:25: RuntimeWarning: divide by zero encountered in log
  logpoisson = k*np.log(mean) - mean - np.array([sum(np.arange(kk)) for kk in k])
/usr/local/astrometry/lib/python/astrometry/util/removelines.py:25: RuntimeWarning: invalid value encountered in multiply
  logpoisson = k*np.log(mean) - mean - np.array([sum(np.arange(kk)) for kk in k])
/usr/local/astrometry/lib/python/astrometry/util/removelines.py:26: RuntimeWarning: invalid value encountered in less
  badbins = occupied[logpoisson < logcut]

**Comment by mdhoney** [comment]
I am seeing this as well, using a FITS catalogue generated by text2fits.  Do you have idea what may be causing it?  All of my x/y/flux values are > 0.

**Comment by dstndstn** [comment]
finally fixed in 08f63b78]
