### ISSUE TITLE
MInimum install needed to access API - through client

### ISSUE THREAD

**Issue by TFT-Ben** [dstndstn/astrometry.net#167]
Hi,
Looking into implementing nova.astrometry.net, ideally through the client.py module 
Do I only need this module to access the API through it or is there a more complex install required?  Not looking to do any solving locally.
Cheers

**Comment by dstndstn** [comment]
client.py is intentionally independent of everything else.

**Comment by TFT-Ben** [comment]
Excellent, I will drop that in in its own folder and see where I get to.  Thank you!
