### ISSUE TITLE
How to resolve Polaris in 3 seconds

### ISSUE THREAD

**Issue by supermyc** [dstndstn/astrometry.net#169]
Hi，How to resolve Polaris in 3 seconds？I know that the analytic image is near the North Star，This is my parsing process：

solve-field -p -O -U none -B none -R none -M none -N none -C cancel -d 1-10 --downsample 2 --scale-units arcsecperpix --scale-low 30 camera.jpg
Reading input file 1 of 1: "camera.jpg"...===>4ms
Extracting sources...===>1252ms
Downsampling by 2...===>1267ms
simplexy: found 212 sources.===>3070ms
Solving...===>4365ms
Reading file "./camera.axy"...===>4449ms
mo field stars:===>4452ms
  star 2; field_xy 1248.0,121.1, field_orig 1248.0,121.1===>4453ms
  star 0; field_xy 348.2,574.6, field_orig 348.2,574.6===>4453ms
  star 1; field_xy 785.0,415.3, field_orig 785.0,415.3===>4453ms
  log-odds ratio 52.7089 (7.78353e+22), 7 match, 0 conflict, 31 distractors, 11 index.===>4454ms
  RA,Dec = (270.529,87.9002), pixel scale 30.7316 arcsec/pix.===>4454ms
  Hit/miss:   Hit/miss: +-+--++++----------------------------+(best)--------------------------------------------------------------===>4455ms
Field 1: solved with index index-4116.fits.===>5094ms
Field 1 solved: writing to file ./camera.solved to indicate this.===>5095ms
Field: camera.jpg===>5164ms
Field center: (RA,Dec) = (270.608286, 87.890078) deg.===>5166ms
Field center: (RA H:M:S, Dec D:M:S) = (18:02:25.989, +87:53:24.280).===>5169ms
Field size: 10.9046 x 8.18569 degrees===>5170ms
Field rotation angle: up is 71.7962 degrees E of N===>5170ms
Field parity: neg===>5170ms

**Comment by dstndstn** [comment]
Are you saying that you want to get the whole thing running in 3 seconds?

.... buy a faster computer?

Just detecting stars is taking 3 seconds, so you could try --downsample 4 and see if that works.  It should be a bit faster.

You can add --scale-high 40, but that's only going to help the solving part, which is only taking 2 seconds here.

**Comment by dstndstn** [comment]
Also, the speed will depend a great deal on caching.  The first time, it has to read the index files into memory, and then when you run again, it will use the cache.

**Comment by supermyc** [comment]
Yes, I run solve-field on raspberry pie.I want to parse for a short time，I want to parse the short time, I guess it is not a problem with my running command.
I use the solve-field command, is it necessary to cache every time you run the solve-field command? how to use the command to load only the cache once.

**Comment by supermyc** [comment]
I am running the command in Raspberry Pi 3b+, so I guess it is faster for me to use other parameters, for example the parameter: use-sextractor, but I will not use this parameter.
