### ISSUE TITLE
Windows port of Astrometry.net ?

### ISSUE THREAD

**Issue by laheller** [dstndstn/astrometry.net#173]
Actually this in not an issue, just a question?
Do you plan to port astrometry.net to Windows ( **MSYS2** / [MinGW](https://en.wikipedia.org/wiki/MinGW) ) platform?

**Comment by dstndstn** [comment]
I have no plan to do that; haven't owned a Windows machine in years.  The code works on POSIX machines including BSD and Solaris.  No idea how that translates to window-y platforms.

**Comment by laheller** [comment]
Can somebody (also using Windows) to take a look at MSYS2/MinGW ?
What packages are needed, etc.

**Comment by spake** [comment]
I was playing around with getting a Cygwin package built the other week, this might be helpful: https://github.com/spake/astrometry.net-cygwin

**Comment by Aster-the-Med-Stu** [comment]
Well, if you have Windows 10 installed I would recommend enabling WSL and getting Ubuntu from the Microsoft Store. Then you could use the same script to deploy on it.

**Comment by laheller** [comment]
> Well, if you have Windows 10 installed I would recommend enabling WSL and getting Ubuntu from the Microsoft Store. Then you could use the same script to deploy on it.

What do you mean by same script and to deploy?
--------------------------------------------------------------

@dstndstn 
@spake 
@Aster-the-Med-Stu 
I can confirm, that astrometry.net is fully buildable on **Cygwin64** enviroment and works like a charm! Fortunately **all** required packages are available in Cygwin repositories.

All the solving and plotting function wors for me on Windows 10 / Cygwin64!
