### ISSUE TITLE
How to use the WCS header without this software?

### ISSUE THREAD

**Issue by xiange1022** [dstndstn/astrometry.net#175]
I used astrometry soft in local, and processed images sucessfully, but I met a question to use the WCS header(mat_CD, mat_A, mat_B, mat_AP, mat_BP) form xylist to radec by myself without this soft. I don't know how to use the mats in WCS header, is there any papers or  introduction?

**Comment by dstndstn** [comment]
Check this page
https://fits.gsfc.nasa.gov/fits_wcs.html

"Paper II" contains the definitions, but it's not very readable.

If you are using Python, check out the Astropy documentation about WCS.

cheers,
--dustin
