### ISSUE TITLE
Installation problem: Manjaro and libkd

### ISSUE THREAD

**Issue by rmgreve** [dstndstn/astrometry.net#178]
Hello everybody and a happy new year!

I have got the following problem during the installation:
System: Manjaro, x86_64
Linux i7 4.14.160-1-MANJARO #1 SMP PREEMPT

I will try:
1) yaourt -Ss
aur/astrometry.net 0.78-3 (5) (0,00)
Automatic recognition of astronomical images

but
2) yaourt -S astrometry.net

i will get the info:

at the beginning:

==> Erstelle und installiere Paket
==> Erstelle Paket: astrometry.net 0.78-3 (Do 02 Jan 2020 07:49:26 CET)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> Lade astrometry.net-0.78.tar.gz herunter...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.9M  100 10.9M    0     0  4173k      0  0:00:02  0:00:02 --:--:-- 4171k
==> Überprüfe source Dateien mit md5sums...
    astrometry.net-0.78.tar.gz ... Durchgelaufen
==> Entpacke Quellen...
  -> Entpacke astrometry.net-0.78.tar.gz mit bsdtar
==> Beginne prepare()...
==> Beginne build()...
make -C util config
make -C qfits-an
make -C sdss
echo "__version__ = '0.78'" > __init__.py
make -C libkd pyspherematch
make -C util cairoutils.o
make[1]: Verzeichnis „/tmp/yaourt-tmp-rmgreve/aur-astrometry.net/src/astrometry.net-0.78/qfits-an“ wird betreten
make[1]: Verzeichnis „/tmp/yaourt-tmp-rmgreve/aur-astrometry.net/src/astrometry.net-0.78/util“ wird betreten
make[1]: Verzeichnis „/tmp/yaourt-tmp-rmgreve/aur-astrometry.net/src/astrometry.net-0.78/sdss“ wird betreten
make[1]: Verzeichnis „/tmp/yaourt-tmp-rmgreve/aur-astrometry.net/src/astrometry.net-0.78/libkd“ wird betreten
make[1]: Verzeichnis „/tmp/yaourt-tmp-rmgreve/aur-astrometry.net/src/astrometry.net-0.78/util“ wird betreten

#######################################################################################
at the end:

make[1]: Verzeichnis „/tmp/yaourt-tmp-rmgreve/aur-astrometry.net/src/astrometry.net-0.78/util“ wird verlassen
make[1]: Verzeichnis „/tmp/yaourt-tmp-rmgreve/aur-astrometry.net/src/astrometry.net-0.78/libkd“ wird verlassen
make: *** [Makefile:116: libkd-spherematch] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
==> FEHLER:Makepkg konnte astrometry.net nicht erstellen.
==> Erstellen von astrometry.net neu starten?[j/N]

It looks like libkd-spherematch is the problem...

What is going wrong?

Thank you very much !

Matthias

**Comment by dstndstn** [comment]
You need to show more of the error.  Please send the whole log.

**Comment by pozar87** [comment]
Hi!
I have a similar (if not the same) issue. Here are logs form my [build](https://github.com/dstndstn/astrometry.net/files/4269190/build.log)
Best Regards!

**Comment by dstndstn** [comment]
Is it trying to do a parallel build?  The Astrometry.net makefiles do NOT work reliably with "make -j8" etc

**Comment by pozar87** [comment]
Hi thanks for quick answer!
It doesn't seem so - the full script used by Arch/Manjaro to build the package is available here:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=astrometry.net
I've tried pass `-j1` to the make command but the problem persists.

**Comment by dstndstn** [comment]
You are certain of that?  In your build.log I see:

"""
---- Error messages in the next few commands are not necessarily bugs ----
     (we're checking how things works on your computer)
---- Error messages in the next few commands are not necessarily bugs ----
...
     (we're checking how things works on your computer)
"""

which looks like two processes both trying to build os-features-config.log
, and then

"""
--------------- End of expected error messages -----------------

mv ../include/astrometry/os-features-config.h.tmp
../include/astrometry/os-features-config.h

...

mv ../include/astrometry/os-features-config.h.tmp
../include/astrometry/os-features-config.h
mv: nie można wykonać stat na
'../include/astrometry/os-features-config.h.tmp': Nie ma takiego pliku ani
katalogu
"""

which definitely looks like two processes racing to rename the output file.

Maybe MAKEFLAGS is getting set?


cheers,
--dustin

**Comment by pozar87** [comment]
Indeed! I valuate closely when and how **MAKEFLAGS** is set in Manjaro and found that default form `/etc/makepkg.conf` is set to number of processors + 1 
```
MAKEFLAGS="-j$(($(nproc)+1))"
```
So I added `export MAKEFLAGS="-j 1"` to build file as a workaround and retry building. Error has changed and now its complaining about **qsort_r** as well as redefinition of **HAVE_NETPBM**: [build.log](https://github.com/dstndstn/astrometry.net/files/4271715/build.log)

**Comment by dstndstn** [comment]
No, look at the log, it's still building in parallel.

make -C util config
make -C qfits-an
make -C sdss
echo "__version__ = '0.79'" > __init__.py
make -C libkd pyspherematch
make[1]: Wejście do katalogu '/home/pozar/.cache/yay/
astrometry.net/src/astrometry.net-0.79/util'
make[1]: Wejście do katalogu '/home/pozar/.cache/yay/
astrometry.net/src/astrometry.net-0.79/qfits-an'
make[1]: Wejście do katalogu '/home/pozar/.cache/yay/
astrometry.net/src/astrometry.net-0.79/sdss'

**Comment by pozar87** [comment]
You are right again - there are two `make` commend invocations in the `PKGBUILD` and I missed one of them... With `-j 1` it builds like a charm. I'll let maintainer of **astrometry.net** Arch package  know that single-threaded build is required.
Thanks for your support!

**Comment by dstndstn** [comment]
Thank you!

**Comment by oldherl** [comment]
Is there a plan to support parallel build?

**Comment by dstndstn** [comment]
my plan is
(1) find someone who cares
(2) get them to fix it
:)
