### ISSUE TITLE
Running astrometry on Raspberry: ImportError: numpy.core.multiarray failed to import 

### ISSUE THREAD

**Issue by DanielRichart** [dstndstn/astrometry.net#180]
Hello,
I downloaded astrometry.net on my PC and it worked perfectly. 

Now, i downloaded it on a Raspbery Pi, using the same procedures, and when i run '/usr/local/astrometry/bin/solve-field validation1-M44.jpg --no-plots --overwrite --config /home/pi/astrometry.net-0.78/etc/astrometry.cfg --use-sextractor --sextractor-path /usr/bin/sextractor -v', the program start to run, but gives the error '**ImportError: numpy.core.multiarray failed to import**
'. I tried to reinstall python and numpy a couple of times, but the error keep occuring...

Thank you,
Daniel

**Comment by dstndstn** [comment]
Does 'python -c "import numpy"' work on the command line?

To avoid using python, you can add to your solve-field args:
--no-fits2fits
--uniformize 0

**Comment by DanielRichart** [comment]
Hi, thank you for the quick answer!
python -c "import numpy works fine on the command line.
I added the arguments to solve-field and the error still occurs

I will delete all of python form the Raspberry and reinstall it. Maybe is some version conflict

Thank you,
Daniel

**Comment by dstndstn** [comment]
Ohh, actually we run python3 by default, so what about
python3 -c "import numpy"

**Comment by DanielRichart** [comment]
it works too. i will try to rebuild astrometry to try again
Thanks

**Comment by dstndstn** [comment]
ok -- can you also send the full log when you run solve-field with the "-v"
(verbose) flag?  I just want to see where it's failing.

There is very little magic in the way we run python programs.

cheers,
--dustin

**Comment by DanielRichart** [comment]
Hi Dustin,
I'm sorry but i don't have the full log, because i deleted astrometry to rebuild it. When i run 'make py', it tries to build it with python2.7. There is a way to do it with python 3.7?
If it works i can test again and send the full log.

Thanks,
Daniel

**Comment by dstndstn** [comment]
Hi,
I hadn't noticed that you were using version 0.78.  We made python3 the
default in 0.79.  For 0.78, go

export PYTHON=python3
export PYTHON_SCRIPT="/usr/bin/env python3"
make clean
make py

cheers,
--dustin

**Comment by DanielRichart** [comment]
I've built it with python3 and now works perfectly.

Thanks for the support!

**Comment by dstndstn** [comment]
Great, thanks for the note!

**Comment by DanielRichart** [comment]
Hi again dustin,

Im running **solve-field img.jpg --no-plots --overwrite --config /home/pi/astrometry.net-0.78/etc/astrometry.cfg --use-sextractor -v** on the raspberry, but it takes forever to finish.

I'm using it only to get RA and DEC coordinates from the picture. There are any ways or arguments to make it run faster?

Thanks a lot,
Daniel

**Comment by dstndstn** [comment]
Yes, giving it limits on the image scale are the most useful -- see
--scale-low, --scale-high, --scale-units
if you know the camera you're dealing with.

If source detection is taking significant time, you can drop the
--use-sextractor and try using, eg, "--downsample 2"

cheers,
--dstn

**Comment by DanielRichart** [comment]
I'm using the raspberry camera, or using images form the internet to run tests.

I'll look into this arguments and try it.

The sextractor run quickly, the problem is on running the indexes.

There are any way to make it run only to discover WCS?

thanks, 
Daniel

**Comment by dstndstn** [comment]
Discovering the WCS is most of the work.

In addition to scale, you can also test the --parity option.

You can turn off some of the additional output files with
--new-fits none
--match none
--rdls none
--corr none

cheers,
--dustin

**Comment by DanielRichart** [comment]
Ok, i'll try them out.

Thank you very much!
