### ISSUE TITLE
Plot-Constellations is Failing to Overlay

### ISSUE THREAD

**Issue by jlibermann** [dstndstn/astrometry.net#187]
I'm running the `plot-constellations` function from the Linux CLI, and it's failing to overlay the RA/DEC grid on top of my original image. The function is instead outputting a labelled grid on a white background. The exact input I used was: `plot-constellations -w Documents/pole_canon01.fits -G 60 -B -b 10 -g 0.4:0.2:0.2 -f 30 -o output1.png`.

**Comment by dstndstn** [comment]
You have to give it a PPM-format input image via the "-i ppm" argument.  Otherwise where do you think it's getting the image pixels from?

You might consider trying the "plotann.py" script, which is more powerful & flexible.

**Comment by jlibermann** [comment]
Thank you. This resolved my issue.

**Comment by wtgee** [comment]
@dstndstn, just to confirm, `plotann.py` is only available when installed from source but not the package (or, e.g., `apt`), right?  Any reason not to include it if it's a better option than `plot-constellations`?

**Comment by dstndstn** [comment]
I assume packagers would include plotann.py -- probably in the python install tree.  The astrometry.net codebase doesn't have a script for it in bin/ -- I should probably add one, since then it would get the PYTHON_SCRIPT customization, etc, and end up installed somewhere in the $PATH...
