### ISSUE TITLE
plotann.py fails on Ubuntu 20.04/python3

### ISSUE THREAD

**Issue by hronellenfitsch** [dstndstn/astrometry.net#189]
Hello.

I recently installed astrometry-latest (0.80) on Ubuntu 20.04 with setting the python executable to python3 (which is the default on 20.04).
Following this, plotann.py failed with an AttributeError:

    AttributeError: 'plot_args' object has no attribute '__getattr__'

This seems to be an issue with the plot_args object and SWIG. It turns out that it can be fixed by
changing line 62 in plotstuff.py from

    return self.pargs.__getattr__(name)

to

    return getattr(self.pargs, name)

I hope this report helps others with the same issue.

**Comment by dstndstn** [comment]
Would you be able to send a Pull Request with this change?

**Comment by hronellenfitsch** [comment]
Thanks, I created a pull request. If it somehow does not adhere to the standards of this project, please let me know.

**Comment by dstndstn** [comment]
Thanks again!
