### ISSUE TITLE
Update docs: Docker and client.py

### ISSUE THREAD

**Issue by dstndstn** [dstndstn/astrometry.net#191]

**Comment by Sevelantis** [comment]
Hello.
This sem to be my first post. Sorry if I am in a wrong place, but I find it less chaotic than creating new issue. Since I could not find any solution in opened or closed issues. Is is possible to work with Astrometry.net using only Docker?

Whenever i build docker webservice:
```
docker build -t astrometry-webservice:first .
```
In Step 11/14: RUN git stash && git pull I get exit code not equal to zero which is bad. Output:
```bash
Step 11/14 : RUN git stash && git pull
 ---> Running in f61872990a3c
Saved working directory and index state WIP on master: a83f9e26 Merge branch 'master' of github.com:dstndstn/astrometry.net
warning: redirecting to https://github.com/dstndstn/astrometry.net.git/
From http://github.com/dstndstn/astrometry.net
 * [new branch]        main       -> origin/main
 * [new tag]           0.81       -> 0.81
 * [new tag]           0.82       -> 0.82
 * [new tag]           0.83       -> 0.83
 * [new tag]           0.84       -> 0.84
 * [new tag]           0.85       -> 0.85
 * [new tag]           0.86       -> 0.86
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
The command '/bin/sh -c git stash && git pull' returned a non-zero code: 1
mir@miron:/usr/local/astrometry/source/docker/webservice$ 
```

I feel like this can be github main/master naming issue. Are we able to do anything? Maybe there could be simple workaround?

Thank you,
Miron

**Comment by dstndstn** [comment]
Ahh yes, thank you, that is the problem.  I am rebuilding the 'astrometrynet/latest' image...

**Comment by dstndstn** [comment]
Okay, I pushed a new astrometrynet/latest Dockerhub image -- can you please try again?

**Comment by Sevelantis** [comment]
Works like a charm! Thank you. And one more 'general' question:
Is this possible to work with `.FITS` files with Astrometry.net, just using Docker? I am really hard stuck with local Astrometry.net configuration and I am trying to migrate to Docker. What do you think about this idea? Maybe you could help me with my issue? I can tell.

**Comment by dstndstn** [comment]
Yes, fits files should work fine.

And sure, I can try to help with the local Astrometry.net config issue you're having.

**Comment by Sevelantis** [comment]
OK. Starting this up on my Linux-Mint-20.
I have a local copy of all .fits file listed in this URL - broiler.astrometry.net/~dstn/4200/

- Those FITS files are in:

`/home/mir/Desktop/data`

- Astrometry install path on my device:

`/usr/local/astrometry/`

- Config file:

`/usr/local/astrometry/etc/astrometry.cfg`
Its content:
```c++
add_path /home/mir/Desktop/data
autoindex
```

- Commands outputs on some random (but official, from given URL ) `.FITS` files:

1.  `mir@miron:~/Desktop/data$ solve-field --no-plots -v -O -D out index-4203-26.fits`
```bash
  (not xyls because: Missing required columns: X, Y)
qfits: error: NAXIS = 0 in file index-4203-26.fits ext 0
an-fitstopnm.c:224:main: Failed to load pixels.
Command failed: /usr/local/astrometry/bin/an-fitstopnm -i index-4203-26.fits > /tmp/tmpl__cbpfa.pnm
augment-xylist.c:590:backtick Failed to run command: /usr/local/astrometry/bin/image2pnm --infile index-4203-26.fits --uncompressed-outfile /tmp/tmp.uncompressed.hTOSmj --outfile /tmp/tmp.ppm.2hAOTj --ppm --mydir /usr/local/astrometry/bin/solve-field
 ioutils.c:568:run_command_get_outputs Command failed: return value 255
```

- For different kind of `.FITS` files that I work with:

2. `mir@miron:/usr/local/astrometry/data$ solve-field --no-plots -v -O -D out FILE.fits`
First fails (until now everything was clear):
```bash
  (not xyls because: FITS file does not have any extensions)
Failed to find (5x5) centroid of peak 22, subpeak 0 at (1343,340)
Failed to find (5x5) centroid of peak 65, subpeak 0 at (1117,1187)
Failed to find (5x5) centroid of peak 96, subpeak 0 at (1692,1793)
kdtree_fits_io.c:274:kdtree_fits_read_tree: Kdtree header was not found in file /usr/local/astrometry/data/FILE.fits
starkd.c:259:my_open: Failed to read kdtree from file "/usr/local/astrometry/data/FILE.fits"
...
Failed to add index "/usr/local/astrometry/data/FILE-.fits".
```


I tried a lot of FITS files, installed prerequisites like: netpbm, cfitsio ... Can we do ?

Thank you very much for your time,
Miron

**Comment by dstndstn** [comment]
Hi,

If you have all the index-*.fits files in /usr/local/astrometry/data, then
remove the "add_path /home/mir/Desktop/data" line from the config file.

The config file *only* points to index files, NOT to images you are going to solve.

cheers,
--dustin

**Comment by dstndstn** [comment]
Oh, and *don't* put any other FITS files in the /usr/local/astrometry/data directory.  That is, don't mix index files with your FITS images you are trying to solve.  That is confusing solve-field.

**Comment by Sevelantis** [comment]
I will try this solution tomorrow morning.

Miron

**Comment by Sevelantis** [comment]
> Oh, and _don't_ put any other FITS files in the /usr/local/astrometry/data directory. That is, don't mix index files with your FITS images you are trying to solve. That is confusing solve-field.

So what is the difference between `index files` and `FITS images` ?

**Comment by Sevelantis** [comment]
I mean if you give any example of proper usage, I would be good to go!

**Comment by dstndstn** [comment]
Hi,

The index-*.fits files are pre-computed maps of the sky.  They are not images, they are data files.

They go in /usr/local/astrometry/data

Nothing else goes in /usr/local/astrometry/data

You tell the solve-field command about those files by listing that directory in the astrometry.cfg file.

When you have a new image to solve -- a JPEG or FITS image -- that is what you pass to the solve-field command.

cheers,
--dustin

**Comment by Sevelantis** [comment]
OK. What I did not know was: a group of index file is kind of database that stores 'idea' or 'near ideal' examples of stars and whenever you run `solve-field` those index files are being searched for astrological dependencies such as: triangles, magnitudes, brightness, centroids etc...

argument of `solve-field` is simply eg. `.FITS`. file that is filtered through different criterias comparing to every single `index file` and overall, we are given the name of an `index file`. Those on your site are just examples,  but the bigger and more reliable the database, the better the solution.

`By the way, if anybody works only via docker using astrometry.net, try to take some time and show your workgin examples, here.`

Thank you very much for help Dustin, no more questions from me at the moment.
