### ISSUE TITLE
Compile astrometry-net on Sipeed Maix Dock board

### ISSUE THREAD

**Issue by DanielRichart** [dstndstn/astrometry.net#192]
Hi,

I am developing a project using the astrometry-net code and so far i am using a raspberry pi. I followed the installation instructions of the astrometry website and managed to run it successfully. 

Now, on a new phase of the project, i am trying to compile the code on a Sipeed Maix Dock board, with risc-v architecture. I've already tried using cmake to cross compile the project using the riscv-toolchain, but unsuccessfully. 
Do you have any idea if i can compile astrometry in riscv, and how to do it?

Thanks a lot,
Daniel Richart

**Comment by dstndstn** [comment]
No idea -- you might want to try posting on the forum (
https://groups.google.com/forum/#!forum/astrometry) in case anyone there
has some experience there.

If you have a compile error, I can try looking into it.  The code is known
to work on a variety of POSIX platforms with different CPUs, but I'm not
familiar with this board.  What OS does it run?

**Comment by DanielRichart** [comment]
I've posted on the forum, thanks! Hope someone there has experience with this board.

The Sipeed Maix Dock board has a K210 microcontroller, and a RISC-v 64bit CPU. 
It has an IDE in which is possible to write in micropython, and binary files can be flashed in its memory.
I think that is also possible to run a linux 0.11 in it.
The board can also be programmed in the arduino IDE. I was trying to use it with the astrometry code, but it had a ton of include errors. I guess the folders of the astrometry project and the dependencies between its files weren't included correctly. 

Cheers,
Daniel

**Comment by dstndstn** [comment]
Okay, I'm going to close this issue for now; let's have the conversation on the forum, at
https://groups.google.com/forum/#!topic/astrometry/6I_aV8iEXt0
