### ISSUE TITLE
tan_xyzarr2iwc: why rad2deg at the end ????

### ISSUE THREAD

**Issue by jean-eric** [dstndstn/astrometry.net#20]
Hello,

In the process of (ra,dec) to pixel coordinates transform (in a tan transform) there is a step where the 3d unit vector defined by (ra,dec)-direction is projected on tangent plane. Fine in principle, but in the tan_xyzarr2iwc function after projection (ie. star_coords function), there is a step that I do not anderstand at all, why the intermediate coordinate (iwc) should be transfomed rad2deg ??????

JE
<code>
anbool tan_xyzarr2iwc(const tan_t* tan, const double* xyz,
					double* iwcx, double* iwcy) {

	double xyzcrval[3];
	// FIXME be robust near the poles
	// Calculate intermediate world coordinates (x,y) on the tangent plane
	radecdeg2xyzarr(tan->crval[0], tan->crval[1], xyzcrval);

	if (!star_coords(xyz, xyzcrval, !tan->sin, iwcx, iwcy))
		return FALSE;

	*iwcx = rad2deg(*iwcx);
	*iwcy = rad2deg(*iwcy);
	return TRUE;
}
</code>

**Comment by dstndstn** [comment]
the star_coords function returns the projection in radians.  All the Astrometry.net routines work in degrees.  Hence rad2deg.
