### ISSUE TITLE
AttributeError in plotstuff.py

### ISSUE THREAD

**Issue by gvnnlgl** [dstndstn/astrometry.net#200]
While using plotann.py (version 0.80), I am getting an attribute error for line 62 of plotstuff.py (final line of def __getattr__ in Plotstuff class:

return self.pargs.__getattr__(name)

However I get both solve-field and plot-constellations generate annotated images correctly...
I am not enough expert in python to understand if there is a problem with the use of __getattr__ or is this a symptom of incomplete installation?

**Comment by gvnnlgl** [comment]
Here is the complete test output:

 ... :~/code/static $ export PYTHONPATH=${PYTHONPATH}:/usr/local/astrometry/lib/python                    
 ... :~/code/static $ sudo python3 /usr/local/astrometry/bin/plotann.py shoot_lyr.new shoot_lyr.jpg shoot_lyr-ann.png -v

Traceback (most recent call last):
  File "/usr/local/astrometry/bin/plotann.py", line 368, in <module>
    anns = get_annotations(plot.wcs, opt)
  File "/usr/local/astrometry/lib/python/astrometry/blind/plotstuff.py", line 62, in __getattr__
    return self.pargs.__getattr__(name)
AttributeError: 'plot_args' object has no attribute '__getattr__'

**Comment by dstndstn** [comment]
This is fixed in the 0.82 release.

**Comment by gvnnlgl** [comment]
Thanks, I will upgrade then...  Please point me to update instructions if any, I couldn't find... Or maybe I just delete all /usr/local/astrometry and roll make, make py, make extra, make install again

**Comment by dstndstn** [comment]
Yep, it should work fine to just delete /usr/local/astrometry and reinstall.  (Move any index or config files you might have in /usr/local/astrometry/data or etc)
