### ISSUE TITLE
nova.astrometry.net makes mistakes if option "CRPIX" in center is used.

### ISSUE THREAD

**Issue by han-k59** [dstndstn/astrometry.net#201]
If in nova.astrometry.net  the advanced option CRPIX in "center" is used, a wrong angle is reported and the new-image.fits contains a  wrong solution:

[quote]
Upload without an option
http://nova.astrometry.net/user_images/4051947#annotated
Center (RA, Dec): | (298.003, 73.139)
Center (RA, hms): | 19h 52m 00.769s
Center (Dec, dms): | +73° 08' 21.471"
Orientation: | Up is -1.87 degrees
CRVAL1  =         295.53221757 / RA  of reference point                         
CRVAL2  =        71.3823963067 / DEC of reference point                         

Same image uploaded with option CRPIX in center:
http://nova.astrometry.net/user_images/4054548#annotated
Center (RA, Dec): | (297.845, 73.093)       ???not very accurate
Center (RA, hms): | 19h 51m 22.813s      ???not very accurate
Center (Dec, dms): | +73° 05' 35.531"
Orientation: | Up is -13.6 degrees                ??????????????????
CRVAL1  =        283.049391707 / RA  of reference point           ???????????????????????? Very wrong              
CRVAL2  =        69.0211942745 / DEC of reference point          ???????????????????????? Very wrong             
CRPIX1  =                    0 / X reference pixel                              ????????????????????? Should be 3690.5
CRPIX2  =                    0 / Y reference pixel                             ??????????????????????? Should be 2454.5
[/quote]

As comparison
ASTAP solution:
CRVAL1  =  2.980104696514E+002 / RA  of reference point                         
CRVAL2  =  7.314186520962E+001 / DEC of reference point 
CRPIX1  =  3.690500000000E+003 / X reference pixel                              
CRPIX2  =  2.454500000000E+003 / Y reference pixel                              
CROTA1  =  4.978703101753E-001 / Image twist of X axis        (deg)             
CROTA2  =  4.937158410148E-001 / Image twist of Y axis        (deg)             
                        

---Han

**Comment by dstndstn** [comment]
Thanks for this bug report.

Turns out, this was solved in https://github.com/dstndstn/astrometry.net/issues/174

BUT, a couple of releases ago I renamed the 'blind' directory to 'solver', and Nova was still pointing to the old executable!

Should be fixed now.  (You'll have to resubmit images to get them re-run though.)

**Comment by han-k59** [comment]
Yes it works now as expected.
