### ISSUE TITLE
SIP distorsions: sip.c  function sip_calc_distortion

### ISSUE THREAD

**Issue by jean-eric** [dstndstn/astrometry.net#21]
Hi,
Looking at sip_calc_distortion in sip.c file here is a part of the code

<code>
	for (p=0; p<=sip->a_order; p++)

		for (q=0; q<=sip->a_order; q++)

			//if ((p+q > 0) && (p+q <= sip->a_order))

			if (p+q <= sip->a_order)

				fuv += sip->a[p][q] * powu[p] * powv[q];

	for (p=0; p<=sip->b_order; p++) 

		for (q=0; q<=sip->b_order; q++) 

			//if ((p+q > 0) && (p+q <= sip->b_order))

			if (p+q <= sip->b_order)

				guv += sip->b[p][q] * powu[p] * powv[q];

</code>

In fact it uses constant and linear terms which are both not used for the Foward distortion computattions by SIP conventions 
http://fits.gsfc.nasa.gov/registry/sip/SIP_distortion_v1_0.pdf

One can simply modify for instance the 'A' part as followed
<code>
  for (p=0; p<=sip->a_order; p++)

    for (q=0; (p+q)<=sip->a_order; q++){

      if(p+q < 1) continue; //constant term

      if(drop_linear && (p+q <2)) continue; //linear terms

      fuv +=  sip->a[p][q] * powu[p] * powv[q];

    }
</code>
idem for the 'B' part.
The "drop_linear" variable is a boolean that by default is TRUE (cf. SIP conventions) but in case of other application can be switched to FLASE and then all coeff are used.

JE

**Comment by dstndstn** [comment]
the polynomial arrays are zeroed out at the beginning of sip_read_header, so I don't think this is an issue.
