### ISSUE TITLE
error during installation of astrometry.net 0.82 on Ubuntu

### ISSUE THREAD

**Issue by svalenti** [dstndstn/astrometry.net#214]
I have an issue installing it on my computer. I downloaded the last version following these steps:

wget http://astrometry.net/downloads/astrometry.net-latest.tar.gz
tar xvzf astrometry.net-latest.tar.gz
cd astrometry.net-*
make
make py
make extra
make install  # to put it in /usr/local/astrometry

I don't see any issue during the installation but then when i run it I get the following error:

Extracting sources...
simplexy: found 319 sources.
Traceback (most recent call last):
  File "/usr/local/astrometry/bin/removelines", line 15, in <module>
    sys.exit(main())
  File "/usr/local/astrometry/lib/python/astrometry/util/removelines.py", line 78, in main
    cut=opt.cut, ext=opt.ext)
  File "/usr/local/astrometry/lib/python/astrometry/util/removelines.py", line 40, in removelines
    T = fits_table(infile, lower=False)
  File "/usr/local/astrometry/lib/python/astrometry/util/fits.py", line 676, in fits_table
    pf = pyfits.open(dataorfn, memmap=mmap)
AttributeError: 'NoPyfits' object has no attribute 'open'
augment-xylist.c:590:backtick Failed to run command: /usr/local/astrometry/bin/removelines /tmp/tmp.xyls.Thhgem /tmp/tmp.removelines.ECnWMa
 ioutils.c:568:run_command_get_outputs Command failed: return value 1

If i install the version .7 using apt-get it get installed correctly, but i need the version 0.82 

thanks

**Comment by dstndstn** [comment]
You need to 'pip install fitsio' or 'pip install astropy'.
Or set --no-remove-lines --uniformize 0
