### ISSUE TITLE
DoesNotExist User matching query does not exist

### ISSUE THREAD

**Issue by charettemtb** [dstndstn/astrometry.net#215]
Hello,

First of all thank you for this project.
I'm working for having my own instance of nova server on my computer (local install with sqlite database).

For that I've followed http://astrometry.net/doc/net/orientation.html#web-local documentation, and after:
1. I have created the folder appsecrets inside net folder.
2. I have created \__init__.py.
3. I have created django_db.py (
> DATABASE_USER = ''
> DATABASE_PASSWORD = ''
> DATABASE_HOST = ''
> DATABASE_PORT = ''
4. I have created auth.py (empty file, I didn't find what to define inside)

When I connect to the portal, I got this error message : 
`DoesNotExist
User matching query does not exist.`

Coul'd you help me ?
Thanks !

**Comment by dstndstn** [comment]
I think you need to do these steps,
https://github.com/dstndstn/astrometry.net/blob/master/docker/webservice/Dockerfile#L31

**Comment by charettemtb** [comment]
Great It work !
Great performance inside all in one VirtualBox machine.
THANKS
