### ISSUE TITLE
image2pnm fails

### ISSUE THREAD

**Issue by avilqu** [dstndstn/astrometry.net#216]
The solve-field command fails with the following output:

```
tan@bobby ~/Astro/science/WASP-41/20210311 RC8 ST402 $ solve-field calibrated/wasp-41_Light_L_150_secs_2021-03-08T02-32-59_033.fits 
Reading input file 1 of 1: "calibrated/wasp-41_Light_L_150_secs_2021-03-08T02-32-59_033.fits"...
Traceback (most recent call last):
  File "/usr/bin/image2pnm", line 14, in <module>
    from astrometry.util.image2pnm import main
ModuleNotFoundError: No module named 'astrometry'
augment-xylist.c:590:backtick Failed to run command: /usr/bin/image2pnm --infile calibrated/wasp-41_Light_L_150_secs_2021-03-08T02-32-59_033.fits --uncompressed-outfile /tmp/tmp.uncompressed.KYTAW0 --outfile /tmp/tmp.ppm.0PmHld --ppm --mydir /usr/bin/solve-field
 ioutils.c:568:run_command_get_outputs Command failed: return value 1
```

I have installed the AUR package astrometry.net. The version is "Revision 0.82, date Thu_Jul_16_16:26:35_2020_-0400." (as seen with solve-field --help).

I don't know much about Python environments but it seems that could be the issue here? I use python 3.9.2 and I have installed anaconda too which I use for some image calibration work.

**Comment by dstndstn** [comment]
Yeah, like the error message says, it's not finding the 'astrometry' python
package.  The PYTHONPATH environment variable has to be set so that it
contains the python 'astrometry' directory (containing the __init__.py
file, util/ directory, etc).  I don't know anything about AUR so I can't
speak to where they chose to install files.
cheers,
--dustin

**Comment by avilqu** [comment]
Thanks for your answer. The PYTHONPATH variable didn't exist on my system so I created it in my .bashrc with the following value:

**Comment by avilqu** [comment]
Alright sorry I had misunderstood the way PYTHONPATH works. I solved it by having only '/usr/lib/pyton/site-packages' as my PYTHONPATH.

Thanks for your help.
