### ISSUE TITLE
Different behavior between nova and local installation

### ISSUE THREAD

**Issue by charettemtb** [dstndstn/astrometry.net#218]
Hello,

I'm working on a self hosted astrometry solder. 
For this submission : [nova.astrometry.net/user_images/4511672#annotated](https://nova.astrometry.net/user_images/4511672#annotated)
On my self hosted environment, the same job succeeded but not showing HD 21332 annotation.
Could you explain me why ?
Thanks a lot

**Comment by dstndstn** [comment]
Hi,

I think you need to grab the Hipparcos data file to get those annotations:

http://data.astrometry.net/hip.fits

Check the astrometry/net/settings.py file to set the path to that file.

**Comment by charettemtb** [comment]
It works !
Thanks
