### ISSUE TITLE
Astrometry.net python package location

### ISSUE THREAD

**Issue by laheller** [dstndstn/astrometry.net#220]
Is there a way to tell to build system (make install) to put astrometry.net Python package to **custom location**?
It seems that it always puts hardcoded under _/usr/lib/python_ folder,
 but on most systems there is only _/usr/lib/python3_.

**Comment by laheller** [comment]
@dstndstn  thank you!

**Comment by dstndstn** [comment]
My mistake, the variable is
PY_BASE_INSTALL_DIR
and should have an 'astrometry/' suffix; eg,

make install INSTALL_DIR=/usr PYTHON_SCRIPT="/usr/bin/python3" PY_BASE_INSTALL_DIR="/usr/lib/python3/astrometry"

**Comment by laheller** [comment]
@dstndstn 
Thanks again, now it works as expected!
