### ISSUE TITLE
When Pinpoint WCS solution is overwritten the proprietary distortion parms TR_i_j remain.

### ISSUE THREAD

**Issue by clkotnik** [dstndstn/astrometry.net#227]
Pinpoint WCS solutions use CTYPE[12] RA---TAN.  However, proprietary distortion parameters for the form TRi_j are added to the FITS header.  When overriding the Pinpoint WCS DFITS header, Astrometry.net does comment out the standard entried Pinpoint adds, but leaves the TRi_j in place.  These should be commented out as well.

**Comment by dstndstn** [comment]
fixed in 7d7754f
