### ISSUE TITLE
Unable to find index files

### ISSUE THREAD

**Issue by hamed-AM** [dstndstn/astrometry.net#231]
Dear Dustin,

Hope you are doing well.

I have installed astrometry.net on my ubuntu 20 virtual machin, but I have trouble solving my fields: It compies there are no index files. I'm sure I have copied at least one of them into /usr/loca/astrometry/data directory, and edited the config file within /usr/local/astrometry/etc accordingly.

Here are some shots of what is happening:

![1](https://user-images.githubusercontent.com/43694263/129308708-6f98a642-758c-41cc-b387-e807e63cd3d3.JPG)

![2](https://user-images.githubusercontent.com/43694263/129308735-430c9dc4-c0e4-4e6a-a608-6d9023b81733.JPG)

![3](https://user-images.githubusercontent.com/43694263/129308744-91669a04-75c5-4a8d-8d08-db3b124eee0d.JPG)

I have tried installing from the source on another Ubuntu installation, but the same problem does exist.

Your help would be highly appreciated.

Thanks
Hamed

**Comment by dstndstn** [comment]
Notice in the last screenshot that it says it's reading the config file `/etc/astrometry.cfg`  (not `/usr/local/astrometry/etc/astrometry.cfg`)

You can tell `solve-field` to use a specific config file with the `--config <filename>` option.

**Comment by hamed-AM** [comment]
Thanks, Dustin ... Solved!

So, you see my solve-filed command goes very long as I add many options. Is there a way to save all the required options in a file and load a single file to tell about the options (rather than typing one by one)?

Thanks
Hamed

**Comment by dstndstn** [comment]
No, I'm afraid not.
You could always define a shell alias -- eg if you use bash, put in your ~/.bashrc file

alias my-solve-field='solve-field --config /usr/local/astrometry/etc/astrometry.cfg'

and then run "my-solve-field" instead of "solve-field"

**Comment by hamed-AM** [comment]
Dear Dustin,
Thank you again...Very helpful.

Could you please have a look at two of the images I want to solve?

![2s](https://user-images.githubusercontent.com/43694263/129441591-f1de6ce7-df5e-480d-8b73-b68680a80e42.jpeg)
![5s](https://user-images.githubusercontent.com/43694263/129441703-16f5f2bd-d314-474f-973b-93e7b55ed80f.jpeg)

I do astrometry on these images using (for example)
solve-field light.jpec --scale-units arcsecperpix --scale-low 0.40 --scale-high 0.50 --sigma=2.5 --overwrite --continue --downsample 2 --nsigma=5

 by the way, I would like to know the best values for options to perform a more accurate and fast job. Could you please advise on these?

Bests
Hamed

**Comment by dstndstn** [comment]
Those options seem fine.
To make source detection a bit faster, you can add "--no-remove-lines" and "--uniformize 0".
To make the matching faster, you can figure out which parity to use: "--parity pos" or "--parity neg" (try both and see which one results in a solution).
If you know the approximate RA,Dec, you can include that with "--ra", "--dec" and "--radius".
You could tighten up the scale range a bit (as small as maybe +- 2%).
