### ISSUE TITLE
Why CDi_j matrix are prefered to PCi_j?

### ISSUE THREAD

**Issue by lock042** [dstndstn/astrometry.net#235]
When doing astrometry with astrometry.net (online), FITS header is filled with CDi_j matrix and some distorsion parameters. In Sect. 2.1.2 of WCS Paper I, it is clearly recommended to prefer PC_ij matrix (with CDELTi) because CDi_j becomes highly problematic when used in conjunction with sequent distortion functions (i.e. those following the linear transformation matrix). I had some discussion with Mark Calabretta, the author of WCS, and he deeply regrets that CDi_j persists for these reasons.

Could we imagine that Astrometry.net uses the PCi_j in the future as Astrometry.net has kind of set the standard.?

Regards,

**Comment by dstndstn** [comment]
I don't see Astrometry.net switching from the CD matrix elements.  They are very very widely deployed and understood.  And they work very well with the SIP distortion parameterization, which in my view occurs at the right place -- it converts between distorted pixels and undistorted pixels, which then go through CD and projection as usual.
