### ISSUE TITLE
WCS parameters meaning

### ISSUE THREAD

**Issue by lkosz** [dstndstn/astrometry.net#236]
Hello

Is there a documentation explaining the meaning of the parameters in wcs files?

**Comment by dstndstn** [comment]
Hi,

The standards documents are here,
  https://fits.gsfc.nasa.gov/fits_wcs.html

Short version: we use a TAN WCS projection, ie, a tangent-plane projection.
CRPIX tells you where on the image the projection is centered
CRVAL tells you the RA,Dec of that point.
the CD matrix tells you how pixels project into the directions of RA and
Dec; those vectors ("intermediate world coordinates") get projected back
onto the sphere to give RA,Dec.

cheers,
--dustin
