### ISSUE TITLE
Call solve-field within a python script

### ISSUE THREAD

**Issue by hamed-AM** [dstndstn/astrometry.net#247]
Hi Dustin,

Could you please advise on this:

I would like to call solve-field (e.g. solve-field my_image.fits --overwrite --downsample 2) within a line of my python code. 
Using "subprocess" method I can call "solve-field" alone, and can not specify an image, some parameters and so on.

Thanks
Hamed

**Comment by dstndstn** [comment]
What does your code look like?  You should be able to do
```
import subprocess
subprocess.call(['solve-field', 'image.fits'])
```
ie, pass a list of strings containing the command-line arguments.
