### ISSUE TITLE
Readme seems out fo date

### ISSUE THREAD

**Issue by knservis** [dstndstn/astrometry.net#267]
Hi @dstndstn,

I have been looking through the docs in search for some tools that I need (to avoid writing them myself) and I think some utils that are mentioned in the readme e.g. xylist2fits in https://github.com/dstndstn/astrometry.net/blame/main/doc/readme.rst#L558
no longer exist. OTOH text2fits (which I am guessing is the replacement for the above), is not mentioned.

**Comment by dstndstn** [comment]
Thanks, I just made a few updates -- would you mind reading through again and flagging anything else that seems inaccurate?

**Comment by knservis** [comment]
If I see something I will let you know! Thanks @dstndstn
