### ISSUE TITLE
`--tweak-order 0` gives the same results as `--tweak-order 2` for `solve-field` function

### ISSUE THREAD

**Issue by prajwel** [dstndstn/astrometry.net#275]
Keeping `--tweak-order 0` as an argument to the `solve-field` function gives the same result as `--tweak-order 2`.

**Comment by dstndstn** [comment]
Yes, "--tweak-order 0" doesn't make any sense.  You can do "--no-tweak" to
turn it off, or "--tweak-order 1" to only do linear order.
