### ISSUE TITLE
--verify seems not to accept any input files

### ISSUE THREAD

**Issue by alexw-im** [dstndstn/astrometry.net#278]
Maybe I'm missing something simple but I tried to read through the README and I can't seem to get the -V/--verify option to work, trying to more deeply analyze some solves i've got.

for instance,
```
$ solve-field --verify 45.wcs
ERROR: You didn't specify any files to process.
This program is part of the Astrometry.net suite.
For details, visit http://astrometry.net.
Git URL https://github.com/dstndstn/astrometry.net
Revision 0.94, date Mon_May_1_11:19:51_2023_-0400.
```
If I reverse the order, i.e. `solve-field 45.wcs --verify`, or if I use the original .jpg as input, same behavior. 

This is true for both .93 that I had been using, and .94 I just updated to.

**Comment by alexw-im** [comment]
I've actually just noticed this additional oddness:
```
$ solve-field 45.wcs --verify --overwrite
Reading input file 1 of 1: "45.wcs"...
Output file already exists: "./45.axy".
Use the --overwrite flag to overwrite existing files,
 or the --continue  flag to not overwrite existing files but still try solving.
Continuing to next input file.
```

**Comment by dstndstn** [comment]
When using --verify, you must still provide the image file.  --verify provides the WCS header file to verify.

**Comment by alexw-im** [comment]
Oh I see, thanks! 

The first time I retried that, I did `solve-field --overwrite 200.png --verify 200.wcs` which failed with

```
augment-xylist.c:1360:augment_xylist Failed to parse WCS header from file "50ms-200.wcs" ext 0
 sip_qfits.c:267:read_header_file Failed to read FITS header from file "50ms-200.wcs" extension 0
 qfits:errfunc error: Failed to read FITS file "50ms-200.wcs" to extension 0
```
I had to run the initial solve first, then copy the .wcs output under a new name, then

`solve-field --overwrite 200.png --verify 200.keep.wcs`

which seems to have done the trick.
