### ISSUE TITLE
Typos in ReadMe

### ISSUE THREAD

**Issue by RichStevenson** [dstndstn/astrometry.net#279]
I believe there are 2 typos in the readme for the index files. First, this line, "Referring to the table below, you should grab index files 5203 through 5209." I think should read, "Referring to the table below, you should grab index files 5203 through 5206 and 4107-4109." Second I think the file listed in the table, index-4107-*.fits should not have the -* and should read index-4107.fits.
[https://github.com/dstndstn/astrometry.net/blob/main/doc/readme.rst](url)

**Comment by RichStevenson** [comment]
Yep. Just submitted.

**Comment by dstndstn** [comment]
Awesome!  closed via #280
