### ISSUE TITLE
sip_cal_inv_distortion: p+q <= AP_ORDER  ???

### ISSUE THREAD

**Issue by jean-eric** [dstndstn/astrometry.net#28]
Hi Dustin
Look at the code I have copied from sip.c file. Why for instance the loop
for (q=0; q<=sip->ap_order; q++)
is not
 for (q=0; (p+q)<=sip->ap_order; q++){
as
even for an inverse SIP transform p+q <= AP_ORDER (for the U -> u part) as described
in the 2008 Shupe & Hook paper? 
Does this means that you have extended their paper ?

JE

void sip_calc_inv_distortion(const sip_t* sip, double U, double V, double* u, double *v) {
	int p, q;
	double fUV=0.;
	double gUV=0.;

    // avoid using pow() function
    double powu[SIP_MAXORDER];
    double powv[SIP_MAXORDER];
    powu[0] = 1.0;
    powu[1] = U;
    powv[0] = 1.0;
    powv[1] = V;
	for (p=2; p <= MAX(sip->ap_order, sip->bp_order); p++) {
        powu[p] = powu[p-1] * U;
        powv[p] = powv[p-1] * V;
    }

	for (p=0; p<=sip->ap_order; p++)
		for (q=0; q<=sip->ap_order; q++)
			//fUV += sip->ap[p][q] * pow(U,p) * pow(V,q);
			fUV += sip->ap[p][q] * powu[p] * powv[q];
	for (p=0; p<=sip->bp_order; p++) 
		for (q=0; q<=sip->bp_order; q++) 
			//gUV += sip->bp[p][q] * pow(U,p) * pow(V,q);
            gUV += sip->bp[p][q] * powu[p] * powv[q];

	*u = U + fUV;
	*v = V + gUV;
}

**Comment by dstndstn** [comment]
Fixed in c999935
Thanks!
