### ISSUE TITLE
Request: command line option for indexes path

### ISSUE THREAD

**Issue by juliotux** [dstndstn/astrometry.net#281]
A nice to have feature that is still not present in the astrometry.net is a command line option to set the indexes folder directly in solve-field. So, I would like to request this feature, if possible.

**Comment by grapeot** [comment]
Probably you already know about this, but a potential get around is to specify the config file path in the command line, and specify the index folder there. Something like
```
cp /usr/local/etc/astrometry.cfg tmp.cfg
echo "add_path /your/path/to/data" >> tmp.cfg
<solve-field business>
rm tmp.cfg
```

**Comment by dstndstn** [comment]
Added in d8ce3cbb
