### ISSUE TITLE
Python 3.12 build error

### ISSUE THREAD

**Issue by juliotux** [dstndstn/astrometry.net#286]
`astrometry.net` is currently not compatible with Python 3.12, due to the deprecation of distutils [PEP 632](https://peps.python.org/pep-0632/). So, the conda-forge package for `astrometry.net` cannot be merged (see [build status](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=799304&view=logs&j=e9afaa34-1a0f-534e-78fc-fae528ccd915&t=869ab379-d63c-50ae-655f-69018fb07995&l=1802)).

An alternative is to migrate to [setuptools](https://pypi.org/project/setuptools/) package.

**Comment by mattiaverga** [comment]
This is probably fixed by https://github.com/dstndstn/astrometry.net/commit/7fff04d4b9f2e8bd0a2b2b567541a543a7a733dd waiting for a new release.

BTW, in Fedora 39 with Python 3.12 astrometry 0.94 builds fine, but we're starting to see failures with Python 3.13 prerelease.

**Comment by juliotux** [comment]
I don't think that 7fff04d currently fixes the problem. A [quick search](https://github.com/search?q=repo%3Adstndstn%2Fastrometry.net%20distutils&type=code) in the code shows `distutils` is yet being used in 10 files.

**Comment by mattiaverga** [comment]
In #289 I have removed all remaining calls to `numpy.distutils`.
Other `distutils` calls can still work by ensuring `setuptools` is installed in the build environment. That's only a quick fix, though, as astrometry.net should migrate to a more modern build system.

**Comment by sassy-asjp** [comment]
Is there any reason blocking the migration to `setuptools`? It looks pretty straightforward to me and I could probably poke around at doing it some time if no one else is already working on it.

**Comment by dstndstn** [comment]
Some of the modules are built using swig, and they need to get library paths from the Makefile... so go ahead, if you can manage that need.

**Comment by sassy-asjp** [comment]
@juliotux I opened merge request #293 to hopefully fix this issue. Could you check whether it works for you?

**Comment by juliotux** [comment]
@sassy-asjp your review is installing fine on Python 3.12

**Comment by oldherl** [comment]
Could you please tag a new release to include the fix for Python 3.12?

**Comment by dstndstn** [comment]
Done, https://github.com/dstndstn/astrometry.net/releases/tag/0.95
