### ISSUE TITLE
Issue when trying to constrain pixel scale

### ISSUE THREAD

**Issue by astrofrog** [dstndstn/astrometry.net#287]
I am trying to speed up solving by specifying a pixel scale range. I am using a FITS binary table of positions as input. If I do:

```
 /usr/local/astrometry/bin/solve-field -X xcentroid -Y ycentroid -w 2000 -e 2000 --overwrite /tmp/sources.fits
```

Then things work fine and I get the following in the solution:

```
  RA,Dec = (173.876,-25.612), pixel scale 0.69815 arcsec/pix.
```

However, if I constrain the pixel scale using:

```
 /usr/local/astrometry/bin/solve-field -X xcentroid -Y ycentroid -w 2000 -e 2000 -U app -L 0.5 -H 1.0 --overwrite /tmp/sources.fits
```

Then the solving fails even though 0.69 is in the range 0.5 to 1.0. What could be causing this?

[link to sources.fits](https://www.dropbox.com/s/533ael3f5asbrzz/sources.fits?dl=1)

**Comment by dstndstn** [comment]
The `--scale-units` argument is `-u` (lower-case), while you've got `-U app` ... which is requesting an output file named `app` :)

**Comment by astrofrog** [comment]
:man_facepalming:

Thanks!

**Comment by dstndstn** [comment]
Apologies for the infinite number of command-line arguments ;)
