### ISSUE TITLE
doc/install_astrometry_on_linux.sh downloads questionable index choice

### ISSUE THREAD

**Issue by sassy-asjp** [dstndstn/astrometry.net#290]
As per data.astrometry.net, index 4100 and 5200 LITE are recommended for most users, however the `doc/install_astrometry_on_linux.sh` script downloads 4100 and **5000**.

Is there a motivation for this?

Otherwise it's a simple one line change to either remove the download for 5000 or replace it with a download for 5200 LITE.

**Comment by dstndstn** [comment]
Thanks for this comment!  Done in 7c2928bba2facec5ef9eaea36f9b88a7c4fe44eb
