### ISSUE TITLE
What is the license for index files?

### ISSUE THREAD

**Issue by knyipab** [dstndstn/astrometry.net#294]
The [astrometry.net README](https://astrometry.net/doc/readme.html) says `The index files come with their own license conditions. See the file GETTING-INDEXES for details.` but I could not find any `GETTING-INDEXES` file. What exactly is the license for the indexes file such as the 4100 series and 5200 series?  Thank you!

**Comment by dstndstn** [comment]
Oh, that's a good question!

That text is old - the 200-series files were derived from the USNO-B1.0 catalog, which has funny licensing rules that meant we could not make the 200-series files cleanly open-source.

I *think* later files should be fine to license under some open license.  But someone would have to check.  The catalogs in question are Tycho-2 and Gaia DR2.

**Comment by knyipab** [comment]
Really appreciate your prompt answer!

Indeed, I am trying to bundle 4115-4119 index files as a distro pacakge (https://github.com/termux-user-repository/tur/pull/850), but I have to fill in the license file. 

* Gaia seems to come with quite open license: https://www.cosmos.esa.int/web/gaia-users/license 
* There does not seem to be license info for Tycho-2

**Comment by knyipab** [comment]
It seems that license related to Vizier is available at https://cds.u-strasbg.fr/vizier-org/licences_vizier.html but still quite vague. 

I understand it is hard to tell the data license from academic paper. I think I may simply take reference to https://github.com/lupinix/astrometry-tycho2/blob/master/LICENSE.txt and make a license file like this: 

```
Copyright 2000 Hog E., Fabricius C., Makarov V.V., Urban S., Corbin T., Wycoff G., Bastian U., Schwekendiek P., Wicenec A. (Tycho-2 catalogue)

Copyright 2006-2015 Michael Blanton, David W. Hogg, Dustin Lang, Keir Mierle and Sam Roweis (scripts to generate 4100-series index files)
```

See if the second part about astrometry looks good to you. Thanks

**Comment by dstndstn** [comment]
It sounds like Ole went to the effort of contacting the Tycho-2 author directly and got his confirmation, so I think you are good to go.

For the Astrometry.net team, we only claim copyright on the software that we wrote, not on any of the resulting data files.  That copyright statement is fine, I think; you may want to state that the license flows from the Tycho-2 catalog, rather than from the Astrometry.net software.

Thanks for putting in this effort!

**Comment by dstndstn** [comment]
Looks great!  If you want, you could add,
```
The Astrometry.net team claims copyright on the script to generate 4100-series index files (but not on the resulting index files):
```
