### ISSUE TITLE
Version empty when not building from git

### ISSUE THREAD

**Issue by juliotux** [dstndstn/astrometry.net#296]
Astrometry.net uses git to get the `AN_GIT_REVISION` variable. However, when building from the zip downloaded from the Github releases tab (`https://github.com/dstndstn/astrometry.net/archive/refs/tags/{tag}.zip`), the `.git` folder is not present and a version cannot be determined. So, `solve-filed --version` command returns a empty string. Since there is already a manual version set in `__init__.py` file, this could be used to determine a version if git is not present.

**Comment by dstndstn** [comment]
Don't use the .zip link, there's a specially created tarball for each release.

**Comment by dstndstn** [comment]
Or, you could manually set AN_GIT_REVISION=0.95 when building.

But if you wanted to modify the Makefile (util/makefile.common) so that AN_GIT_REVISION grabs the version out of __init__.py if git is not available, that would be a useful improvement!

**Comment by juliotux** [comment]
The .tar.gz link doesn't contain the .git folder too. Needed to set the version manually.

**Comment by dstndstn** [comment]
Oh, yes, of course you are right!!!  Sorry!

**Comment by juliotux** [comment]
Sorry, my fault. The .tar.gz already replaced the version
```
AN_GIT_REVISION := 0.95
AN_GIT_DATE := Mon_May_6_18:41:28_2024_-0400
AN_GIT_URL := https://github.com/dstndstn/astrometry.net
```

No need to set manualy.

**Comment by dstndstn** [comment]
Okay, I forgot about that :)
