### ISSUE TITLE
conda version for macos arm64 chip

### ISSUE THREAD

**Issue by jeremyneveu** [dstndstn/astrometry.net#306]
Hi,

the conda version of astrometry.net is very useful. Now that macbooks are switching to arm64 chips, is it possible to add a macos arm64 recipe to the astrometry conda repo?

Thanks :)

**Comment by dstndstn** [comment]
I don't know who created the conda recipes, but it's not me!

**Comment by dstndstn** [comment]
You want to look at https://github.com/conda-forge/astrometry-feedstock

**Comment by dstndstn** [comment]
I'm closing this issue since it must be reported to the repo above instead.
