### ISSUE TITLE
New release for Numpy 2.0?

### ISSUE THREAD

**Issue by juliotux** [dstndstn/astrometry.net#308]
Since adding support for numpy 2.0 is an important new feature, is it time for a new release?

This is needed to unblock the conda-forge building agin. https://github.com/conda-forge/astrometry-feedstock/pull/50

**Comment by dstndstn** [comment]
Sure... do you know if `main` currently works?

**Comment by juliotux** [comment]
Yes! I tested now.

**Comment by dstndstn** [comment]
Thank you -- I'll cut a release!

**Comment by dstndstn** [comment]
https://github.com/dstndstn/astrometry.net/releases/tag/0.96
