### ISSUE TITLE
Conflicting files installation with cfitsio

### ISSUE THREAD

**Issue by mattiaverga** [dstndstn/astrometry.net#310]
Some files installed by astrometry (fitscopy, fitsverify, imcopy) are conflicting with files provided by cfitsio system's package.
Would it be possible to avoid bundling them and properly link to cfitsio provided headers? Or, at least, rename them so to discriminate from cfitsio provided ones?

**Comment by dstndstn** [comment]
For the longest time, the cfitsio package did not install those binaries.  Does it do that now?

**Comment by mattiaverga** [comment]
It seems so.
I'm packaging astrometry in Fedora Linux and I got a report from the other maintainer of the cfitsio package about those conflicting files.
From what I see, they're now manually excluding installing some files to avoid conflicts:
```
make DESTDIR=%{buildroot} install
#
rm %{buildroot}/%{_bindir}/cookbook
rm %{buildroot}/%{_bindir}/fitsverify
rm %{buildroot}/%{_bindir}/fitscopy
rm %{buildroot}/%{_bindir}/imcopy
rm %{buildroot}/%{_bindir}/smem
rm %{buildroot}/%{_bindir}/speed
```

The plan is to move those programs under a cfitsio-utils subpackage to provide them by "official" upstream. I could just remove the astrometry generated files in the astrometry RPM, if this is something you prefer to not "fix" upstream.

**Comment by dstndstn** [comment]
(We do already use the cfitsio header and library; it's just that cfitsio used to not install those very useful "example" programs.)
