### ISSUE TITLE
Index Error - Not readable

### ISSUE THREAD

**Issue by mashbudj** [dstndstn/astrometry.net#43]
Hi, this is my question:
I am new to using the astrometry.net software. It has been installed in my /user/local/ directory, with the build directory astrometry.net-0.50 off my home directory. I downloaded several indexes (all labeled index-42XX-YY.fits) that say “are built from the 2MASS catalog,” and then moved them into my /user/local/astrometry/data directory. Here is what I get when I try to solve a field or perform astrometry from my home directory, 

archos:~ mashbudj$ /usr/local/astrometry/bin/solve-field --scale-low 10 --overwrite ~/photometry/LFC/PSRJ1622/g_band/restart/dnpccd.068.1.fits
Reading input file 1 of 1: "/Users/mashbudj/photometry/LFC/PSRJ1622/g_band/restart/dnpccd.068.1.fits"...
Header has 107 cards
/usr/local/astrometry/lib/python/astrometry/util/fits2fits.py:49: PyfitsDeprecationWarning: The ascard function is deprecated as of version 3.1 and may be removed in a future version.

        Use the `.cards` attribute instead.
  for c in hdr.ascard:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyfits/card.py:70: PyfitsDeprecationWarning: The CardList class has been deprecated; all its former functionality has been subsumed by the Header class, so CardList objects should not be directly created.  See the PyFITS 3.1.0 CHANGELOG for more details.
  PyfitsDeprecationWarning)
Extracting sources...
simplexy: found 648 sources.
Solving...
index.c:154:index_is_file_index: Index file /usr/local/astrometry/data/index-4107.quad.fits is not readable.
index.c:154:index_is_file_index: Index file /usr/local/astrometry/data/index-4107.quad.fits is not readable.
fitsbin.c:580:fitsbin_open: Failed to open file "/usr/local/astrometry/data/index-4107.skdt.fits"
starkd.c:257:my_open: Failed to open FITS file "/usr/local/astrometry/data/index-4107.skdt.fits"
index.c:414:index_reload: Failed to read star kdtree from file /usr/local/astrometry/data/index-4107.skdt.fits
engine.c:211:engine_add_index: Failed to load index from path /usr/local/astrometry/data/index-4107
Failed to add index "/usr/local/astrometry/data/index-4107".
index.c:154:index_is_file_index: Index file /usr/local/astrometry/data/index-4205-07.fits.quad.fits is not readable.
fitsbin.c:580:fitsbin_open: Failed to open file "/usr/local/astrometry/data/index-4205-07.fits.skdt.fits"
starkd.c:257:my_open: Failed to open FITS file "/usr/local/astrometry/data/index-4205-07.fits.skdt.fits"
index.c:414:index_reload: Failed to read star kdtree from file /usr/local/astrometry/data/index-4205-07.fits.skdt.fits
engine.c:211:engine_add_index: Failed to load index from path /usr/local/astrometry/data/index-4205-07.fits
Failed to add index "/usr/local/astrometry/data/index-4205-07.fits".
index.c:154:index_is_file_index: Index file /usr/local/astrometry/data/index-4204-29.fits.quad.fits is not readable.
fitsbin.c:580:fitsbin_open: Failed to open file "/usr/local/astrometry/data/index-4204-29.fits.skdt.fits"
starkd.c:257:my_open: Failed to open FITS file "/usr/local/astrometry/data/index-4204-29.fits.skdt.fits"
index.c:414:index_reload: Failed to read star kdtree from file /usr/local/astrometry/data/index-4204-29.fits.skdt.fits
engine.c:211:engine_add_index: Failed to load index from path /usr/local/astrometry/data/index-4204-29.fits
Failed to add index "/usr/local/astrometry/data/index-4204-29.fits".
index.c:154:index_is_file_index: Index file /usr/local/astrometry/data/index-4203-29.fits.quad.fits is not readable.
fitsbin.c:580:fitsbin_open: Failed to open file "/usr/local/astrometry/data/index-4203-29.fits.skdt.fits"
starkd.c:257:my_open: Failed to open FITS file "/usr/local/astrometry/data/index-4203-29.fits.skdt.fits"
index.c:414:index_reload: Failed to read star kdtree from file /usr/local/astrometry/data/index-4203-29.fits.skdt.fits
engine.c:211:engine_add_index: Failed to load index from path /usr/local/astrometry/data/index-4203-29.fits
Failed to add index "/usr/local/astrometry/data/index-4203-29.fits".
index.c:154:index_is_file_index: Index file /usr/local/astrometry/data/index-4202-29.fits.quad.fits is not readable.
fitsbin.c:580:fitsbin_open: Failed to open file "/usr/local/astrometry/data/index-4202-29.fits.skdt.fits"
starkd.c:257:my_open: Failed to open FITS file "/usr/local/astrometry/data/index-4202-29.fits.skdt.fits"
index.c:414:index_reload: Failed to read star kdtree from file /usr/local/astrometry/data/index-4202-29.fits.skdt.fits
engine.c:211:engine_add_index: Failed to load index from path /usr/local/astrometry/data/index-4202-29.fits
Failed to add index "/usr/local/astrometry/data/index-4202-29.fits".
index.c:154:index_is_file_index: Index file /usr/local/astrometry/data/index-4201-29.fits.quad.fits is not readable.
fitsbin.c:580:fitsbin_open: Failed to open file "/usr/local/astrometry/data/index-4201-29.fits.skdt.fits"
starkd.c:257:my_open: Failed to open FITS file "/usr/local/astrometry/data/index-4201-29.fits.skdt.fits"
index.c:414:index_reload: Failed to read star kdtree from file /usr/local/astrometry/data/index-4201-29.fits.skdt.fits
engine.c:211:engine_add_index: Failed to load index from path /usr/local/astrometry/data/index-4201-29.fits
Failed to add index "/usr/local/astrometry/data/index-4201-29.fits".

---------------------------------------------------------------------
You must list at least one index in the config file (/usr/local/astrometry/bin/../etc/astrometry.cfg)

See http://astrometry.net/use.html about how to get some index files.
---------------------------------------------------------------------

solve-field.c:529:run_engine engine failed.  Command that failed was:
  /usr/local/astrometry/bin/astrometry-engine /Users/mashbudj/photometry/LFC/PSRJ1622/g_band/restart/dnpccd.068.1.axy
 ioutils.c:569:run_command_get_outputs Command failed: return value 255

Strangely, it continues to look for indexes that are no longer in /usr/local/astrometry/data/, (I have these below)
index-4203-29.fits	
index-4201-29.fits	index-4204-29.fits
index-4202-29.fits	index-4205-07.fits
How do I get the program to recognize these files?

I only find astrometry.net-0.50/etc/astrometry.cfg in the build directory (adding names there did not work either). And there is no command called ‘install-indexes’ that I can find, does this mean I built it wrong? 

I don't have any *skdt.fits or *quad.fits files; should these be downloaded, or am I supposed to create them? If so, how do I do that?

Thank you.
Daniel Mashburn
Physics Department
University WI-Milwaukee

**Comment by dstndstn** [comment]
Hi,

I would have expected the config file to get copied to /usr/local/astrometry/etc/astrometry.cfg

It should contain something like,

add_path /usr/local/astrometry/data
autoindex

and solve-field should just then try opening all files in /usr/local/astrometry/data .

Could you please send the results of running:

find /usr/local/astrometry


Don't worry about the *.skdt.fits, *.code.fits complaints -- way back in the olden days, the index files were split into three files; now they're merged together in one file.

There is no install-indexes command, it's just a makefile target to copy index files to /usr/local/astrometry/data.

cheers,
--dustin

**Comment by mashbudj** [comment]
Hi, dustin
This is what it finds, even the indexes:
archos:~ mashbudj$ find /usr/local/astrometry/
/usr/local/astrometry/
/usr/local/astrometry//bin
/usr/local/astrometry//bin/an-fitstopnm
/usr/local/astrometry//bin/an-pnmtofits
/usr/local/astrometry//bin/astrometry-engine
/usr/local/astrometry//bin/build-astrometry-index
/usr/local/astrometry//bin/degtohms.py
/usr/local/astrometry//bin/downsample-fits
/usr/local/astrometry//bin/fit-wcs
/usr/local/astrometry//bin/fits-column-merge
/usr/local/astrometry//bin/fits-flip-endian
/usr/local/astrometry//bin/fits-guess-scale
/usr/local/astrometry//bin/fits2fits.py
/usr/local/astrometry//bin/fitscopy
/usr/local/astrometry//bin/fitsgetext
/usr/local/astrometry//bin/get-healpix
/usr/local/astrometry//bin/get-wcs
/usr/local/astrometry//bin/hmstodeg.py
/usr/local/astrometry//bin/hpsplit
/usr/local/astrometry//bin/image2pnm.py
/usr/local/astrometry//bin/image2xy
/usr/local/astrometry//bin/imarith
/usr/local/astrometry//bin/imcopy
/usr/local/astrometry//bin/imstat
/usr/local/astrometry//bin/listhead
/usr/local/astrometry//bin/liststruc
/usr/local/astrometry//bin/merge-columns.py
/usr/local/astrometry//bin/modhead
/usr/local/astrometry//bin/new-wcs
/usr/local/astrometry//bin/pad-file
/usr/local/astrometry//bin/plot-constellations
/usr/local/astrometry//bin/plotann.py
/usr/local/astrometry//bin/plotquad
/usr/local/astrometry//bin/plotstuff
/usr/local/astrometry//bin/plotxy
/usr/local/astrometry//bin/query-starkd
/usr/local/astrometry//bin/removelines.py
/usr/local/astrometry//bin/search-index
/usr/local/astrometry//bin/solve-field
/usr/local/astrometry//bin/subtable
/usr/local/astrometry//bin/tablist
/usr/local/astrometry//bin/tabmerge
/usr/local/astrometry//bin/tabsort
/usr/local/astrometry//bin/text2fits.py
/usr/local/astrometry//bin/uniformize.py
/usr/local/astrometry//bin/votabletofits.py
/usr/local/astrometry//bin/wcs-grab
/usr/local/astrometry//bin/wcs-rd2xy
/usr/local/astrometry//bin/wcs-resample
/usr/local/astrometry//bin/wcs-to-tan
/usr/local/astrometry//bin/wcs-xy2rd
/usr/local/astrometry//bin/wcsinfo
/usr/local/astrometry//data
/usr/local/astrometry//data/index-4201-29.fits
/usr/local/astrometry//data/index-4202-29.fits
/usr/local/astrometry//data/index-4203-29.fits
/usr/local/astrometry//data/index-4204-29.fits
/usr/local/astrometry//data/index-4205-07.fits
/usr/local/astrometry//data/Index.py
/usr/local/astrometry//data/orig
/usr/local/astrometry//doc
/usr/local/astrometry//doc/CREDITS
/usr/local/astrometry//doc/LICENSE
/usr/local/astrometry//doc/README.md
/usr/local/astrometry//doc/report.txt
/usr/local/astrometry//etc
/usr/local/astrometry//etc/astrometry.cfg
/usr/local/astrometry//etc/astrometry.cfg~
/usr/local/astrometry//examples
/usr/local/astrometry//examples/apod1.jpg
/usr/local/astrometry//examples/apod1.xyls
/usr/local/astrometry//examples/apod2.jpg
/usr/local/astrometry//examples/apod2.xyls
/usr/local/astrometry//examples/apod3.jpg
/usr/local/astrometry//examples/apod3.xyls
/usr/local/astrometry//examples/apod4.jpg
/usr/local/astrometry//examples/apod4.xyls
/usr/local/astrometry//examples/apod5.jpg
/usr/local/astrometry//examples/apod5.xyls
/usr/local/astrometry//examples/CREDITS
/usr/local/astrometry//examples/m44-1910-04-01.jpg
/usr/local/astrometry//examples/m44-1975-01-18.jpg
/usr/local/astrometry//examples/sdss.jpg
/usr/local/astrometry//examples/sdss.xyls
/usr/local/astrometry//include
/usr/local/astrometry//include/astrometry
/usr/local/astrometry//include/astrometry/2mass-fits.h
/usr/local/astrometry//include/astrometry/2mass.h
/usr/local/astrometry//include/astrometry/allquads.h
/usr/local/astrometry//include/astrometry/an-bool.h
/usr/local/astrometry//include/astrometry/an-endian.h
/usr/local/astrometry//include/astrometry/an-opts.h
/usr/local/astrometry//include/astrometry/an-thread-pthreads.h
/usr/local/astrometry//include/astrometry/an-thread.h
/usr/local/astrometry//include/astrometry/anqfits.h
/usr/local/astrometry//include/astrometry/anwcs.h
/usr/local/astrometry//include/astrometry/augment-xylist.h
/usr/local/astrometry//include/astrometry/axyfile.h
/usr/local/astrometry//include/astrometry/bl-nl.h
/usr/local/astrometry//include/astrometry/bl-nl.inc
/usr/local/astrometry//include/astrometry/bl-nl.ph
/usr/local/astrometry//include/astrometry/bl-sort.h
/usr/local/astrometry//include/astrometry/bl.h
/usr/local/astrometry//include/astrometry/bl.inc
/usr/local/astrometry//include/astrometry/bl.ph
/usr/local/astrometry//include/astrometry/blind.h
/usr/local/astrometry//include/astrometry/blindutils.h
/usr/local/astrometry//include/astrometry/brightstars.h
/usr/local/astrometry//include/astrometry/bt.h
/usr/local/astrometry//include/astrometry/build-index.h
/usr/local/astrometry//include/astrometry/cairoutils.h
/usr/local/astrometry//include/astrometry/catalog.h
/usr/local/astrometry//include/astrometry/coadd.h
/usr/local/astrometry//include/astrometry/codefile.h
/usr/local/astrometry//include/astrometry/codekd.h
/usr/local/astrometry//include/astrometry/codetree.h
/usr/local/astrometry//include/astrometry/constellations.h
/usr/local/astrometry//include/astrometry/convolve-image.h
/usr/local/astrometry//include/astrometry/ctmf.h
/usr/local/astrometry//include/astrometry/dimage.h
/usr/local/astrometry//include/astrometry/dualtree.h
/usr/local/astrometry//include/astrometry/dualtree_nearestneighbour.h
/usr/local/astrometry//include/astrometry/dualtree_rangesearch.h
/usr/local/astrometry//include/astrometry/engine.h
/usr/local/astrometry//include/astrometry/errors.h
/usr/local/astrometry//include/astrometry/fileutils.h
/usr/local/astrometry//include/astrometry/fit-wcs.h
/usr/local/astrometry//include/astrometry/fits-guess-scale.h
/usr/local/astrometry//include/astrometry/fitsbin.h
/usr/local/astrometry//include/astrometry/fitsfile.h
/usr/local/astrometry//include/astrometry/fitsioutils.h
/usr/local/astrometry//include/astrometry/fitstable.h
/usr/local/astrometry//include/astrometry/gslutils.h
/usr/local/astrometry//include/astrometry/hd.h
/usr/local/astrometry//include/astrometry/healpix-utils.h
/usr/local/astrometry//include/astrometry/healpix.h
/usr/local/astrometry//include/astrometry/hpquads.h
/usr/local/astrometry//include/astrometry/image2xy-files.h
/usr/local/astrometry//include/astrometry/image2xy.h
/usr/local/astrometry//include/astrometry/index.h
/usr/local/astrometry//include/astrometry/intmap.h
/usr/local/astrometry//include/astrometry/ioutils.h
/usr/local/astrometry//include/astrometry/kdtree.h
/usr/local/astrometry//include/astrometry/kdtree_fits_io.h
/usr/local/astrometry//include/astrometry/keywords.h
/usr/local/astrometry//include/astrometry/log.h
/usr/local/astrometry//include/astrometry/matchfile.h
/usr/local/astrometry//include/astrometry/matchobj.h
/usr/local/astrometry//include/astrometry/mathutil.h
/usr/local/astrometry//include/astrometry/merge-index.h
/usr/local/astrometry//include/astrometry/multiindex.h
/usr/local/astrometry//include/astrometry/new-wcs.h
/usr/local/astrometry//include/astrometry/ngc2000.h
/usr/local/astrometry//include/astrometry/ngcic-accurate.h
/usr/local/astrometry//include/astrometry/nomad-fits.h
/usr/local/astrometry//include/astrometry/nomad.h
/usr/local/astrometry//include/astrometry/os-features-config.h
/usr/local/astrometry//include/astrometry/os-features.h
/usr/local/astrometry//include/astrometry/permutedsort.h
/usr/local/astrometry//include/astrometry/plotannotations.h
/usr/local/astrometry//include/astrometry/plotfill.h
/usr/local/astrometry//include/astrometry/plotgrid.h
/usr/local/astrometry//include/astrometry/plotimage.h
/usr/local/astrometry//include/astrometry/plotoutline.h
/usr/local/astrometry//include/astrometry/plotstuff.h
/usr/local/astrometry//include/astrometry/plotxy.h
/usr/local/astrometry//include/astrometry/qfits_byteswap.h
/usr/local/astrometry//include/astrometry/qfits_card.h
/usr/local/astrometry//include/astrometry/qfits_convert.h
/usr/local/astrometry//include/astrometry/qfits_error.h
/usr/local/astrometry//include/astrometry/qfits_float.h
/usr/local/astrometry//include/astrometry/qfits_header.h
/usr/local/astrometry//include/astrometry/qfits_image.h
/usr/local/astrometry//include/astrometry/qfits_keywords.h
/usr/local/astrometry//include/astrometry/qfits_md5.h
/usr/local/astrometry//include/astrometry/qfits_memory.h
/usr/local/astrometry//include/astrometry/qfits_rw.h
/usr/local/astrometry//include/astrometry/qfits_std.h
/usr/local/astrometry//include/astrometry/qfits_table.h
/usr/local/astrometry//include/astrometry/qfits_time.h
/usr/local/astrometry//include/astrometry/qfits_tools.h
/usr/local/astrometry//include/astrometry/qidxfile.h
/usr/local/astrometry//include/astrometry/quad-builder.h
/usr/local/astrometry//include/astrometry/quad-utils.h
/usr/local/astrometry//include/astrometry/quadfile.h
/usr/local/astrometry//include/astrometry/radix.h
/usr/local/astrometry//include/astrometry/rdlist.h
/usr/local/astrometry//include/astrometry/resample.h
/usr/local/astrometry//include/astrometry/resort-xylist.h
/usr/local/astrometry//include/astrometry/scamp-catalog.h
/usr/local/astrometry//include/astrometry/scamp.h
/usr/local/astrometry//include/astrometry/simplexy-common.h
/usr/local/astrometry//include/astrometry/simplexy.h
/usr/local/astrometry//include/astrometry/sip-utils.h
/usr/local/astrometry//include/astrometry/sip.h
/usr/local/astrometry//include/astrometry/sip_qfits.h
/usr/local/astrometry//include/astrometry/solvedclient.h
/usr/local/astrometry//include/astrometry/solvedfile.h
/usr/local/astrometry//include/astrometry/solver.h
/usr/local/astrometry//include/astrometry/starkd.h
/usr/local/astrometry//include/astrometry/starutil.h
/usr/local/astrometry//include/astrometry/starutil.inc
/usr/local/astrometry//include/astrometry/starxy.h
/usr/local/astrometry//include/astrometry/svn.h
/usr/local/astrometry//include/astrometry/tabsort.h
/usr/local/astrometry//include/astrometry/tic.h
/usr/local/astrometry//include/astrometry/tweak.h
/usr/local/astrometry//include/astrometry/tweak2.h
/usr/local/astrometry//include/astrometry/tycho2-fits.h
/usr/local/astrometry//include/astrometry/tycho2.h
/usr/local/astrometry//include/astrometry/ucac3.h
/usr/local/astrometry//include/astrometry/ucac4.h
/usr/local/astrometry//include/astrometry/uniformize-catalog.h
/usr/local/astrometry//include/astrometry/unpermute-quads.h
/usr/local/astrometry//include/astrometry/unpermute-stars.h
/usr/local/astrometry//include/astrometry/usnob-fits.h
/usr/local/astrometry//include/astrometry/usnob.h
/usr/local/astrometry//include/astrometry/verify.h
/usr/local/astrometry//include/astrometry/wcs-rd2xy.h
/usr/local/astrometry//include/astrometry/wcs-xy2rd.h
/usr/local/astrometry//include/astrometry/xylist.h
/usr/local/astrometry//index-4107.fits
/usr/local/astrometry//lib
/usr/local/astrometry//lib/libanbase.a
/usr/local/astrometry//lib/libanfiles.a
/usr/local/astrometry//lib/libanutils.a
/usr/local/astrometry//lib/libastrometry.a
/usr/local/astrometry//lib/libastrometry.so
/usr/local/astrometry//lib/libcatalogs.a
/usr/local/astrometry//lib/libkd.a
/usr/local/astrometry//lib/libqfits.a
/usr/local/astrometry//lib/python
/usr/local/astrometry//lib/python/astrometry
/usr/local/astrometry//lib/python/astrometry/__init__.py
/usr/local/astrometry//lib/python/astrometry/blind
/usr/local/astrometry//lib/python/astrometry/blind/__init__.py
/usr/local/astrometry//lib/python/astrometry/blind/_plotstuff_c.so
/usr/local/astrometry//lib/python/astrometry/blind/plotann.py
/usr/local/astrometry//lib/python/astrometry/blind/plotstuff.py
/usr/local/astrometry//lib/python/astrometry/blind/plotstuff_c.py
/usr/local/astrometry//lib/python/astrometry/catalogs
/usr/local/astrometry//lib/python/astrometry/catalogs/__init__.py
/usr/local/astrometry//lib/python/astrometry/catalogs/ngc2000.py
/usr/local/astrometry//lib/python/astrometry/libkd
/usr/local/astrometry//lib/python/astrometry/libkd/__init__.py
/usr/local/astrometry//lib/python/astrometry/libkd/spherematch.py
/usr/local/astrometry//lib/python/astrometry/libkd/spherematch_c.so
/usr/local/astrometry//lib/python/astrometry/sdss
/usr/local/astrometry//lib/python/astrometry/sdss/__init__.py
/usr/local/astrometry//lib/python/astrometry/sdss/_cutils.so
/usr/local/astrometry//lib/python/astrometry/sdss/common.py
/usr/local/astrometry//lib/python/astrometry/sdss/cutils.py
/usr/local/astrometry//lib/python/astrometry/sdss/dr10.py
/usr/local/astrometry//lib/python/astrometry/sdss/dr7.py
/usr/local/astrometry//lib/python/astrometry/sdss/dr8.py
/usr/local/astrometry//lib/python/astrometry/sdss/dr9.py
/usr/local/astrometry//lib/python/astrometry/sdss/fields.py
/usr/local/astrometry//lib/python/astrometry/sdss/runList-dr10.par
/usr/local/astrometry//lib/python/astrometry/sdss/runList-dr8.par
/usr/local/astrometry//lib/python/astrometry/sdss/runList-dr9.par
/usr/local/astrometry//lib/python/astrometry/util
/usr/local/astrometry//lib/python/astrometry/util/__init__.py
/usr/local/astrometry//lib/python/astrometry/util/_util.so
/usr/local/astrometry//lib/python/astrometry/util/addpath.py
/usr/local/astrometry//lib/python/astrometry/util/casjobs.py
/usr/local/astrometry//lib/python/astrometry/util/degtohms.py
/usr/local/astrometry//lib/python/astrometry/util/EXIF.py
/usr/local/astrometry//lib/python/astrometry/util/file.py
/usr/local/astrometry//lib/python/astrometry/util/filetype.py
/usr/local/astrometry//lib/python/astrometry/util/find_data_file.py
/usr/local/astrometry//lib/python/astrometry/util/fits.py
/usr/local/astrometry//lib/python/astrometry/util/fits2fits.py
/usr/local/astrometry//lib/python/astrometry/util/fix_sdss_idr.py
/usr/local/astrometry//lib/python/astrometry/util/hmstodeg.py
/usr/local/astrometry//lib/python/astrometry/util/horizons.py
/usr/local/astrometry//lib/python/astrometry/util/image2pnm.py
/usr/local/astrometry//lib/python/astrometry/util/imageutils.py
/usr/local/astrometry//lib/python/astrometry/util/lsstutils.py
/usr/local/astrometry//lib/python/astrometry/util/merge-columns.py
/usr/local/astrometry//lib/python/astrometry/util/miscutils.py
/usr/local/astrometry//lib/python/astrometry/util/multiproc.py
/usr/local/astrometry//lib/python/astrometry/util/plotshift.py
/usr/local/astrometry//lib/python/astrometry/util/plotutils.py
/usr/local/astrometry//lib/python/astrometry/util/removelines.py
/usr/local/astrometry//lib/python/astrometry/util/resample.py
/usr/local/astrometry//lib/python/astrometry/util/run_command.py
/usr/local/astrometry//lib/python/astrometry/util/sdss_das.py
/usr/local/astrometry//lib/python/astrometry/util/sdss_filenames.py
/usr/local/astrometry//lib/python/astrometry/util/sdss_get_catalog.py
/usr/local/astrometry//lib/python/astrometry/util/sdss_noise.py
/usr/local/astrometry//lib/python/astrometry/util/sdss_psf.py
/usr/local/astrometry//lib/python/astrometry/util/sdss_psfield.py
/usr/local/astrometry//lib/python/astrometry/util/shell.py
/usr/local/astrometry//lib/python/astrometry/util/siap.py
/usr/local/astrometry//lib/python/astrometry/util/sqlcl.py
/usr/local/astrometry//lib/python/astrometry/util/stages.py
/usr/local/astrometry//lib/python/astrometry/util/starutil.py
/usr/local/astrometry//lib/python/astrometry/util/starutil_numpy.py
/usr/local/astrometry//lib/python/astrometry/util/text2fits.py
/usr/local/astrometry//lib/python/astrometry/util/ttime.py
/usr/local/astrometry//lib/python/astrometry/util/uniformize.py
/usr/local/astrometry//lib/python/astrometry/util/usnob_catalog.py
/usr/local/astrometry//lib/python/astrometry/util/usnob_get_image.py
/usr/local/astrometry//lib/python/astrometry/util/usnob_get_region.py
/usr/local/astrometry//lib/python/astrometry/util/util.py
/usr/local/astrometry//lib/python/astrometry/util/votabletofits.py
/usr/local/astrometry//lib/python/astrometry/util/w3c_validator.py
/usr/local/astrometry//lib/python/astrometry/util/yanny.py
/usr/local/astrometry//ups
/usr/local/astrometry//ups/astrometry_net.cfg
/usr/local/astrometry//ups/astrometry_net.table
Just can’t seem to open them, 

Had a bit of a problem with netpbm earlier, but
Might be unrelated.

You are right, there is the file 
/usr/local/astrometry//etc/astrometry.cfg
but it already has the line included:
add_path /usr/local/astrometry/data
with autoindex and my indexes listed too.

Thank you for the quick reply :) 

Cheers,
Daniel Mashburn
mashbudj@yahoo.com

**Comment by dstndstn** [comment]
Apologies for dropping the ball on this issue!

I'm going to close this issue, assuming that you have given up or solved the problem; please re-open it if not.

(And please send exact contents of the config file /usr/local/astrometry//etc/astrometry.cfg  .  You should *either* set "autoindex" or list your index files, not both.  One other thing to check is whether you can read those index files -- eg, what do you get if you run "liststruc /usr/local/astrometry/data/index-4201-29.fits"?)
