### ISSUE TITLE
Remove temp files

### ISSUE THREAD

**Issue by ppmim** [dstndstn/astrometry.net#45]
I think the temp files ( specified with --temp-dir ) are not all deleted after 'solve-field' end. I have tried the option '--no-delete-temp' and I have found the next files:

/tmp/tmp.sanitized.NvMQq7
/tmp/tmp.uncompressed.ptgyiy
/tmp/tmp.ppm.XmWfaZ
/tmp/tmp.xyls.d9lnRI
/tmp/tmp.removelines.TqXFXR
/tmp/tmp.sorted.F7SzB1
/tmp/tmp.uniform.h98kgb

However, when I remove the  '--no-delete-temp', all the temp files are deleted, except /tmp/tmp.sanitized.XXXXX (the biggest one). It could cause that after solving hundred of files, the temp-dir could be full.

(It was observed with astrometry.net-0.50)

**Comment by wtgee** [comment]
Many moons later...

I am having this same problem. How do we not generate the `tmp.sanitized.XXXX` files? (Or cleanup after). None of the options seem to work.

**Comment by dstndstn** [comment]
Try the master version of the code.  If you are still seeing temp files left behind, please quote the exact command-line and post the file you are using.  Thanks.

**Comment by wtgee** [comment]
Building now, thanks!

**Comment by wtgee** [comment]
Confirmed it properly deletes files with `0.70`. Let it run all night and I still have my 4 GB free the next morning. Thanks!
