### ISSUE TITLE
astrometry.net doesn't compile with GCC >= 5

### ISSUE THREAD

**Issue by lupinix** [dstndstn/astrometry.net#48]
astrometry.net doesn't compile with gcc 5.x, I think the reason is the different semantics for inline functions. Consult https://gcc.gnu.org/gcc-5/porting_to.html. A first solution or workaround: Add  -std=gnu89 to used compiler flags.

Best Regards,
Christian Dersch

**Comment by lupinix** [comment]
Errors I get

[  349s] gcc -o bl.o -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -g -Wall -ffinite-math-only -fno-signaling-nans -pthread -march=native -O3 -fomit-frame-pointer -DNDEBUG -fpic -Winline -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16   -I/usr/include/libpng16      -I../util -I../libkd -I../util  -I../qfits-an -I../util   -I../util  -I../qfits-an -I../util   -I. -c bl.c
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:22:19: error: redefinition of 'star_midpoint'
[  349s]  InlineDefine void star_midpoint(double* mid, const double* A, const double* B) {
[  349s]                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:22:19: note: previous definition of 'star_midpoint' was here
[  349s]  InlineDefine void star_midpoint(double* mid, const double* A, const double* B) {
[  349s]                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:37:27: error: redefinition of 'mjdtojd'
[  349s]  InlineDefine Const double mjdtojd(double mjd) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:37:27: note: previous definition of 'mjdtojd' was here
[  349s]  InlineDefine Const double mjdtojd(double mjd) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:40:27: error: redefinition of 'jdtomjd'
[  349s]  InlineDefine Const double jdtomjd(double jd) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:40:27: note: previous definition of 'jdtomjd' was here
[  349s]  InlineDefine Const double jdtomjd(double jd) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:44:24: error: redefinition of 'dimquad2dimcode'
[  349s]  InlineDefine Const int dimquad2dimcode(int dimquad) {
[  349s]                         ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:44:24: note: previous definition of 'dimquad2dimcode' was here
[  349s]  InlineDefine Const int dimquad2dimcode(int dimquad) {
[  349s]                         ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:48:27: error: redefinition of 'rad2deg'
[  349s]  InlineDefine Const double rad2deg(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:48:27: note: previous definition of 'rad2deg' was here
[  349s]  InlineDefine Const double rad2deg(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:52:27: error: redefinition of 'deg2rad'
[  349s]  InlineDefine Const double deg2rad(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:52:27: note: previous definition of 'deg2rad' was here
[  349s]  InlineDefine Const double deg2rad(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:56:27: error: redefinition of 'deg2arcmin'
[  349s]  InlineDefine Const double deg2arcmin(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:56:27: note: previous definition of 'deg2arcmin' was here
[  349s]  InlineDefine Const double deg2arcmin(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:60:27: error: redefinition of 'arcmin2deg'
[  349s]  InlineDefine Const double arcmin2deg(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:60:27: note: previous definition of 'arcmin2deg' was here
[  349s]  InlineDefine Const double arcmin2deg(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:64:27: error: redefinition of 'arcmin2arcsec'
[  349s]  InlineDefine Const double arcmin2arcsec(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:64:27: note: previous definition of 'arcmin2arcsec' was here
[  349s]  InlineDefine Const double arcmin2arcsec(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:68:27: error: redefinition of 'arcsec2arcmin'
[  349s]  InlineDefine Const double arcsec2arcmin(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:68:27: note: previous definition of 'arcsec2arcmin' was here
[  349s]  InlineDefine Const double arcsec2arcmin(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:72:27: error: redefinition of 'rad2arcmin'
[  349s]  InlineDefine Const double rad2arcmin(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:72:27: note: previous definition of 'rad2arcmin' was here
[  349s]  InlineDefine Const double rad2arcmin(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:76:27: error: redefinition of 'rad2arcsec'
[  349s]  InlineDefine Const double rad2arcsec(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:76:27: note: previous definition of 'rad2arcsec' was here
[  349s]  InlineDefine Const double rad2arcsec(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:80:27: error: redefinition of 'deg2arcsec'
[  349s]  InlineDefine Const double deg2arcsec(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:80:27: note: previous definition of 'deg2arcsec' was here
[  349s]  InlineDefine Const double deg2arcsec(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:84:27: error: redefinition of 'arcmin2rad'
[  349s]  InlineDefine Const double arcmin2rad(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:84:27: note: previous definition of 'arcmin2rad' was here
[  349s]  InlineDefine Const double arcmin2rad(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:88:27: error: redefinition of 'arcsec2rad'
[  349s]  InlineDefine Const double arcsec2rad(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:88:27: note: previous definition of 'arcsec2rad' was here
[  349s]  InlineDefine Const double arcsec2rad(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:92:27: error: redefinition of 'arcsec2deg'
[  349s]  InlineDefine Const double arcsec2deg(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:92:27: note: previous definition of 'arcsec2deg' was here
[  349s]  InlineDefine Const double arcsec2deg(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:96:27: error: redefinition of 'rad2distsq'
[  349s]  InlineDefine Const double rad2distsq(double x) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:96:27: note: previous definition of 'rad2distsq' was here
[  349s]  InlineDefine Const double rad2distsq(double x) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:101:35: error: redefinition of 'rad2dist'
[  349s]  InlineDefine Flatten Const double rad2dist(double x) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:101:35: note: previous definition of 'rad2dist' was here
[  349s]  InlineDefine Flatten Const double rad2dist(double x) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:105:35: error: redefinition of 'arcsec2distsq'
[  349s]  InlineDefine Flatten Const double arcsec2distsq(double x) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:105:35: note: previous definition of 'arcsec2distsq' was here
[  349s]  InlineDefine Flatten Const double arcsec2distsq(double x) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:109:35: error: redefinition of 'arcmin2dist'
[  349s]  InlineDefine Flatten Const double arcmin2dist(double x) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:109:35: note: previous definition of 'arcmin2dist' was here
[  349s]  InlineDefine Flatten Const double arcmin2dist(double x) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:113:35: error: redefinition of 'arcmin2distsq'
[  349s]  InlineDefine Flatten Const double arcmin2distsq(double arcmin) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:113:35: note: previous definition of 'arcmin2distsq' was here
[  349s]  InlineDefine Flatten Const double arcmin2distsq(double arcmin) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:117:27: error: redefinition of 'z2dec'
[  349s]  InlineDefine Const double z2dec(double z) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:117:27: note: previous definition of 'z2dec' was here
[  349s]  InlineDefine Const double z2dec(double z) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:121:27: error: redefinition of 'xy2ra'
[  349s]  InlineDefine Const double xy2ra(double x, double y) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:121:27: note: previous definition of 'xy2ra' was here
[  349s]  InlineDefine Const double xy2ra(double x, double y) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:128:27: error: redefinition of 'xyz2radec'
[  349s]  InlineDefine Flatten void xyz2radec(double x, double y, double z, double *ra, double *dec) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:128:27: note: previous definition of 'xyz2radec' was here
[  349s]  InlineDefine Flatten void xyz2radec(double x, double y, double z, double *ra, double *dec) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:135:27: error: redefinition of 'xyzarr2radec'
[  349s]  InlineDefine Flatten void xyzarr2radec(const double* xyz, double *ra, double *dec) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:135:27: note: previous definition of 'xyzarr2radec' was here
[  349s]  InlineDefine Flatten void xyzarr2radec(const double* xyz, double *ra, double *dec) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:139:27: error: redefinition of 'xyzarr2radecdeg'
[  349s]  InlineDefine Flatten void xyzarr2radecdeg(const double* xyz, double *ra, double *dec) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:139:27: note: previous definition of 'xyzarr2radecdeg' was here
[  349s]  InlineDefine Flatten void xyzarr2radecdeg(const double* xyz, double *ra, double *dec) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:147:27: error: redefinition of 'xyzarr2radecdegarr'
[  349s]  InlineDefine Flatten void xyzarr2radecdegarr(double* xyz, double *radec) {
[  349s]                            ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:147:27: note: previous definition of 'xyzarr2radecdegarr' was here
[  349s]  InlineDefine Flatten void xyzarr2radecdegarr(double* xyz, double *radec) {
[  349s]                            ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:151:19: error: redefinition of 'radec2xyzarr'
[  349s]  InlineDefine void radec2xyzarr(double ra, double dec, double* xyz) {
[  349s]                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:151:19: note: previous definition of 'radec2xyzarr' was here
[  349s]  InlineDefine void radec2xyzarr(double ra, double dec, double* xyz) {
[  349s]                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:158:19: error: redefinition of 'radec2xyz'
[  349s]  InlineDefine void radec2xyz(double ra, double dec,
[  349s]                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:158:19: note: previous definition of 'radec2xyz' was here
[  349s]  InlineDefine void radec2xyz(double ra, double dec,
[  349s]                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:166:19: error: redefinition of 'radecdeg2xyz'
[  349s]  InlineDefine void radecdeg2xyz(double ra, double dec,
[  349s]                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:166:19: note: previous definition of 'radecdeg2xyz' was here
[  349s]  InlineDefine void radecdeg2xyz(double ra, double dec,
[  349s]                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:171:19: error: redefinition of 'radecdeg2xyzarr'
[  349s]  InlineDefine void radecdeg2xyzarr(double ra, double dec, double* xyz) {
[  349s]                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:171:19: note: previous definition of 'radecdeg2xyzarr' was here
[  349s]  InlineDefine void radecdeg2xyzarr(double ra, double dec, double* xyz) {
[  349s]                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:175:19: error: redefinition of 'radecdegarr2xyzarr'
[  349s]  InlineDefine void radecdegarr2xyzarr(double* radec, double* xyz) {
[  349s]                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:175:19: note: previous definition of 'radecdegarr2xyzarr' was here
[  349s]  InlineDefine void radecdegarr2xyzarr(double* radec, double* xyz) {
[  349s]                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:180:19: error: redefinition of 'radec2xyzarrmany'
[  349s]  InlineDefine void radec2xyzarrmany(double *ra, double *dec, double* xyz, int n) {
[  349s]                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:180:19: note: previous definition of 'radec2xyzarrmany' was here
[  349s]  InlineDefine void radec2xyzarrmany(double *ra, double *dec, double* xyz, int n) {
[  349s]                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:187:19: error: redefinition of 'radecdeg2xyzarrmany'
[  349s]  InlineDefine void radecdeg2xyzarrmany(double *ra, double *dec, double* xyz, int n) {
[  349s]                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:187:19: note: previous definition of 'radecdeg2xyzarrmany' was here
[  349s]  InlineDefine void radecdeg2xyzarrmany(double *ra, double *dec, double* xyz, int n) {
[  349s]                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:195:8: error: redefinition of 'star_coords'
[  349s]  anbool star_coords(const double *s, const double *r,
[  349s]         ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:195:8: note: previous definition of 'star_coords' was here
[  349s]  anbool star_coords(const double *s, const double *r,
[  349s]         ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:261:35: error: redefinition of 'distsq2rad'
[  349s]  InlineDefine Flatten Const double distsq2rad(double dist2) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:261:35: note: previous definition of 'distsq2rad' was here
[  349s]  InlineDefine Flatten Const double distsq2rad(double dist2) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:272:35: error: redefinition of 'arcsec2dist'
[  349s]  InlineDefine Flatten Const double arcsec2dist(double arcInArcSec) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:272:35: note: previous definition of 'arcsec2dist' was here
[  349s]  InlineDefine Flatten Const double arcsec2dist(double arcInArcSec) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:277:35: error: redefinition of 'deg2dist'
[  349s]  InlineDefine Flatten Const double deg2dist(double arcInDegrees) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:277:35: note: previous definition of 'deg2dist' was here
[  349s]  InlineDefine Flatten Const double deg2dist(double arcInDegrees) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:281:35: error: redefinition of 'deg2distsq'
[  349s]  InlineDefine Flatten Const double deg2distsq(double d) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:281:35: note: previous definition of 'deg2distsq' was here
[  349s]  InlineDefine Flatten Const double deg2distsq(double d) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:285:35: error: redefinition of 'distsq2arcsec'
[  349s]  InlineDefine Flatten Const double distsq2arcsec(double dist2) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:285:35: note: previous definition of 'distsq2arcsec' was here
[  349s]  InlineDefine Flatten Const double distsq2arcsec(double dist2) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:289:35: error: redefinition of 'dist2arcsec'
[  349s]  InlineDefine Flatten Const double dist2arcsec(double dist) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:289:35: note: previous definition of 'dist2arcsec' was here
[  349s]  InlineDefine Flatten Const double dist2arcsec(double dist) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:293:35: error: redefinition of 'dist2deg'
[  349s]  InlineDefine Flatten Const double dist2deg(double dist) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:293:35: note: previous definition of 'dist2deg' was here
[  349s]  InlineDefine Flatten Const double dist2deg(double dist) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:298:35: error: redefinition of 'distsq2arc'
[  349s]  InlineDefine Flatten Const double distsq2arc(double dist2) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:298:35: note: previous definition of 'distsq2arc' was here
[  349s]  InlineDefine Flatten Const double distsq2arc(double dist2) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:302:35: error: redefinition of 'distsq2deg'
[  349s]  InlineDefine Flatten Const double distsq2deg(double dist2) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:302:35: note: previous definition of 'distsq2deg' was here
[  349s]  InlineDefine Flatten Const double distsq2deg(double dist2) {
[  349s]                                    ^
[  349s] In file included from starutil.c:36:0:
[  349s] starutil.inc:306:35: error: redefinition of 'dist2rad'
[  349s]  InlineDefine Flatten Const double dist2rad(double dist) {
[  349s]                                    ^
[  349s] In file included from starutil.h:230:0,
[  349s]                  from starutil.c:28:
[  349s] starutil.inc:306:35: note: previous definition of 'dist2rad' was here
[  349s]  InlineDefine Flatten Const double dist2rad(double dist) {
[  349s]                                    ^
[  349s] In file included from mathutil.c:31:0:
[  349s] mathutil.inc:21:19: error: redefinition of 'normalize'
[  349s]  InlineDefine void normalize(double* x, double* y, double* z) {
[  349s]                    ^
[  349s] In file included from mathutil.h:107:0,
[  349s]                  from mathutil.c:25:
[  349s] mathutil.inc:21:19: note: previous definition of 'normalize' was here
[  349s]  InlineDefine void normalize(double* x, double* y, double* z) {
[  349s]                    ^
[  349s] Makefile:25: recipe for target 'starutil.o' failed
[  349s] make[1]: *** [starutil.o] Error 1
[  349s] make[1]: *** Waiting for unfinished jobs....
[  349s] In file included from mathutil.c:31:0:
[  349s] mathutil.inc:28:19: error: redefinition of 'normalize_3'
[  349s]  InlineDefine void normalize_3(double* xyz) {
[  349s]                    ^
[  349s] In file included from mathutil.h:107:0,
[  349s]                  from mathutil.c:25:
[  349s] mathutil.inc:28:19: note: previous definition of 'normalize_3' was here
[  349s]  InlineDefine void normalize_3(double* xyz) {
[  349s]                    ^
[  349s] In file included from mathutil.c:31:0:
[  349s] mathutil.inc:35:19: error: redefinition of 'cross_product'
[  349s]  InlineDefine void cross_product(double* a, double* b, double* cross) {
[  349s]                    ^
[  349s] In file included from mathutil.h:107:0,
[  349s]                  from mathutil.c:25:
[  349s] mathutil.inc:35:19: note: previous definition of 'cross_product' was here
[  349s]  InlineDefine void cross_product(double* a, double* b, double* cross) {
[  349s]                    ^
[  349s] In file included from mathutil.c:31:0:
[  349s] mathutil.inc:41:18: error: redefinition of 'imax'
[  349s]  InlineDefine int imax(int a, int b) {
[  349s]                   ^
[  349s] In file included from mathutil.h:107:0,
[  349s]                  from mathutil.c:25:
[  349s] mathutil.inc:41:18: note: previous definition of 'imax' was here
[  349s]  InlineDefine int imax(int a, int b) {
[  349s]                   ^
[  349s] In file included from mathutil.c:31:0:
[  349s] mathutil.inc:45:18: error: redefinition of 'imin'
[  349s]  InlineDefine int imin(int a, int b) {
[  349s]                   ^
[  349s] In file included from mathutil.h:107:0,
[  349s]                  from mathutil.c:25:
[  349s] mathutil.inc:45:18: note: previous definition of 'imin' was here
[  349s]  InlineDefine int imin(int a, int b) {
[  349s]                   ^
[  349s] In file included from mathutil.c:31:0:
[  349s] mathutil.inc:49:21: error: redefinition of 'distsq_exceeds'
[  349s]  InlineDefine double distsq_exceeds(double* d1, double* d2, int D, double limit) {
[  349s]                      ^
[  349s] In file included from mathutil.h:107:0,
[  349s]                  from mathutil.c:25:
[  349s] mathutil.inc:49:21: note: previous definition of 'distsq_exceeds' was here
[  349s]  InlineDefine double distsq_exceeds(double* d1, double* d2, int D, double limit) {
[  349s]                      ^
[  349s] In file included from mathutil.c:31:0:
[  349s] mathutil.inc:61:21: error: redefinition of 'distsq'
[  349s]  InlineDefine double distsq(const double* d1, const double* d2, int D) {
[  349s]                      ^
[  349s] In file included from mathutil.h:107:0,
[  349s]                  from mathutil.c:25:
[  349s] mathutil.inc:61:21: note: previous definition of 'distsq' was here
[  349s]  InlineDefine double distsq(const double* d1, const double* d2, int D) {
[  349s]                      ^
[  349s] In file included from mathutil.c:31:0:
[  349s] mathutil.inc:71:21: error: redefinition of 'square'
[  349s]  InlineDefine double square(double d) {
[  349s]                      ^
[  349s] In file included from mathutil.h:107:0,
[  349s]                  from mathutil.c:25:
[  349s] mathutil.inc:71:21: note: previous definition of 'square' was here
[  349s]  InlineDefine double square(double d) {
[  349s]                      ^
[  349s] In file included from mathutil.c:31:0:
[  349s] mathutil.inc:75:18: error: redefinition of 'inrange'
[  349s]  InlineDefine int inrange(double ra, double ralow, double rahigh) {
[  349s]                   ^
[  349s] In file included from mathutil.h:107:0,
[  349s]                  from mathutil.c:25:
[  349s] mathutil.inc:75:18: note: previous definition of 'inrange' was here
[  349s]  InlineDefine int inrange(double ra, double ralow, double rahigh) {
[  349s]                   ^
[  350s] Makefile:25: recipe for target 'mathutil.o' failed
[  350s] make[1]: *** [mathutil.o] Error 1
[  350s] make[1]: *** wait: No child processes.  Stop.
[  350s] Makefile:90: recipe for target 'extra' failed
[  350s] make: *** [extra] Error 2
[  350s] error: Bad exit status from /var/tmp/rpm-tmp.XzKvt5 (%build)
[  350s] 
[  350s] 
[  350s] RPM build errors:
[  350s]     Bad exit status from /var/tmp/rpm-tmp.XzKvt5 (%build)

**Comment by lupinix** [comment]
Maybe this patch is enough? At least anet compiles without errors.

https://build.opensuse.org/source/home:lupinix-indi:fedora-bleeding/astrometry-net/0001_anet_gcc5.diff

**Comment by dstndstn** [comment]
Thanks -- could you please test master: I just pushed this commit.
https://github.com/dstndstn/astrometry.net/commit/7c65b3cefc4f33c59af90c1a40b5f246002cdf28

**Comment by lupinix** [comment]
Thank you, seems to be fine now :)
