### ISSUE TITLE
index installation patches

### ISSUE THREAD

**Issue by mkplante** [dstndstn/astrometry.net#49]
fixed against git master for a couple problems running make install-indexes

<pre>
From 7128d99f4af75d31f4d7b6fa83c37adf939200fd Mon Sep 17 00:00:00 2001
From: Michael Plante <michael.plante@gmail.com>
Date: Thu, 2 Jul 2015 14:41:19 -0400
Subject: [PATCH 1/2] Makefile: fix missing redirection for bzip2'ed indices

---
 Makefile |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

diff --git a/Makefile b/Makefile
index 879c6a0..84c1f06 100644
--- a/Makefile
+++ b/Makefile
@@ -148,7 +148,7 @@ install-indexes:
 		echo tar xvjf $$x -C '$(DATA_INSTALL_DIR)'; \
 		tar xvjf $$x -C '$(DATA_INSTALL_DIR)'; \
 	done
-	@for x in `ls index-*.bz2 | grep -v tar.bz2 2>/dev/null`; do \
+	@for x in `ls index-*.bz2 2>/dev/null | grep -v tar.bz2 2>/dev/null`; do \
 		echo Installing $$x in '$(DATA_INSTALL_DIR)'...; \
 		echo "cp $$x '$(DATA_INSTALL_DIR)' && bunzip2 --force '$(DATA_INSTALL_DIR)/'$$x;"; \
 		cp $$x '$(DATA_INSTALL_DIR)' && bunzip2 --force '$(DATA_INSTALL_DIR)/'$$x; \
-- 

From dab24076e67a1947bca8ff1ff14a58612bd2ff8e Mon Sep 17 00:00:00 2001
From: Michael Plante <michael.plante@gmail.com>
Date: Thu, 2 Jul 2015 14:41:50 -0400
Subject: [PATCH 2/2] Makefile: fix missing semicolons for uncompressed indices

---
 Makefile |    4 ++--
 1 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/Makefile b/Makefile
index 84c1f06..9e9c1d8 100644
--- a/Makefile
+++ b/Makefile
@@ -160,8 +160,8 @@ install-indexes:
 	done
 	@for x in `ls index-*.fits 2>/dev/null`; do \
 		echo Installing $$x in '$(DATA_INSTALL_DIR)'...; \
-		echo "cp $$x '$(DATA_INSTALL_DIR)'" \
-		cp $$x '$(DATA_INSTALL_DIR)' \
+		echo "cp $$x '$(DATA_INSTALL_DIR)'"; \
+		cp $$x '$(DATA_INSTALL_DIR)'; \
 	done
 
 reconfig:
-- 
</pre>

**Comment by dstndstn** [comment]
Would you mind sending this as a Pull Request?
thanks,
--dustin

**Comment by dstndstn** [comment]
It appears this patch got applied at some point.  Thank you!
