### ISSUE TITLE
Increasing precision output of degree Field center (RA, Dec)

### ISSUE THREAD

**Issue by tstibor** [dstndstn/astrometry.net#59]
Hi Dustin,

I integrated in my code solve-field via popen(...) for solving dslr images and sending the ra,dec values to the Celestron mount for
automatically align the mount/telescope. For that I parsed, the output line (here the apod1.jpg example):

>solve-field --overwrite --downsample 2 -L 6 -H 7 -u arcsecperpix apod1.jpg

...
Field: apod1.jpg
** => Field center: (RA,Dec) = (100.2, 9.832) deg. **<=
Field center: (RA H:M:S, Dec D:M:S) = (06:40:51.759, +09:49:53.843).
...

The RA,Dec degree output is limit to four digits:
logmsg("Field center: (RA,Dec) = (%.4g, %.4g) deg.\n", ra, dec);

How about changing the output to:

logmsg("Field center: (RA,Dec) = (%3.6f, %3.6f) deg.\n", ra, dec);
This would result in:
** =>Field center: (RA,Dec) = (100.215663, 9.831623) deg. **<=

The Celestron library I am using wants the values in degrees.
It is not a big deal to parse for RA H:M:S, ... and convert the values to degrees. How about
increasing in general the precision output:

--               logmsg("Field center: (RA,Dec) = (%.4g, %.4g) deg.\n", ra, dec);
++               logmsg("Field center: (RA,Dec) = (%3.6f, %3.6f) deg.\n", ra, dec);

Cheers
 Thomas

**Comment by dstndstn** [comment]
done in f3b6069
