### ISSUE TITLE
Relative imports breaking command-line version

### ISSUE THREAD

**Issue by TallFurryMan** [dstndstn/astrometry.net#91]
Hello,
It seems that commit c5871ac9 breaks the command-line version. I get errors such as:

> $ time solve-field -v --overwrite --scale-units arcsecperpix --scale-low 2.35 --scale-high 2.55 -3 271 -4 -24 -5 3 IMAGE_035.fits | tee IMAGE_035.astrometry-bleeding.log
> Reading input file 1 of 1: "IMAGE_035.fits"...
> Base: "./IMAGE_035", basefile "IMAGE_035.fits", basedir ".", suffix "fits"
> Checking if file "IMAGE_035.fits" ext 0 is xylist or image: image
>   (not xyls because: FITS file does not have any extensions)
> Running: /usr/local/astrometry/bin/image2pnm.py --sanitized-fits-outfile /tmp/tmp.sanitized.L8d19T --fix-sdss --infile IMAGE_035.fits --uncompressed-outfile /tmp/tmp.uncompressed.i7OMED --outfile /tmp/tmp.ppm.Rk0y9m --ppm
> Traceback (most recent call last):
>   File "/usr/local/astrometry/bin/image2pnm.py", line 16, in <module>
>     from . import addpath
> ValueError: Attempted relative import in non-package
> augment-xylist.c:593:backtick Failed to run command: /usr/local/astrometry/bin/image2pnm.py --sanitized-fits-outfile /tmp/tmp.sanitized.L8d19T --fix-sdss --infile IMAGE_035.fits --uncompressed-outfile /tmp/tmp.uncompressed.i7OMED --outfile /tmp/tmp.ppm.Rk0y9m --ppm
>  ioutils.c:569:run_command_get_outputs Command failed: return value 1

I tried to work around the issue with [those explanations](http://stackoverflow.com/questions/11536764/how-to-fix-attempted-relative-import-in-non-package-even-with-init-py) but I'm not sure I got the problem clear myself :) It seems those relative imports were implemented for the web version of astrometry. Any insight?

**Comment by dstndstn** [comment]
Yes, sorry about this.  I accepted https://github.com/dstndstn/astrometry.net/pull/89 without enough scrutiny.  Fixing it is on my list...

**Comment by TallFurryMan** [comment]
Thanks for confirming. I'll try to come up with a solution, perhaps removing relative imports from top-level scripts.

**Comment by dstndstn** [comment]
I was thinking about possibly reorganizing the scripts a little (as suggested in the thread of #89) to create new executables that would load modules.  Perhaps create a top-level 'bin' directory in the repo to put those scripts in?

**Comment by dstndstn** [comment]
Do you need a new feature from 'master' since the last release?  Could always just branch from the last tagged release...
