### ISSUE TITLE
Crash when building index files

### ISSUE THREAD

**Issue by olebole** [dstndstn/astrometry.net#96]
Hi,

for Debian, I build the tycho2 index from the original Tycho2 catalog. Currently, this however fails on this step:

```
$ build-astrometry-index -i tyc2.fits -o index-tycho2-07.littleendian.fits -d 4 -P 07 \
    -S MAG_VT -B 0.1 -s 0 -r 1 -M
Warning: you should set the unique-id for this index (with -I).
Reading tyc2.fits...
Got 2557501 stars
Sweep 1: 288620 stars
Sweep 2: 277300 stars
Sweep 3: 255884 stars
Sweep 4: 227392 stars
Sweep 5: 196847 stars
Sweep 6: 167790 stars
Sweep 7: 142673 stars
Sweep 8: 121485 stars
Sweep 9: 103932 stars
Sweep 10: 89088 stars
Total: 1871011 stars
Writing output...
First RA,Dec: 219.92,-60.8351
First x,y,z: -0.373747,-0.312727,-0.873221
Treetype: 0x10404
After kdtree_build:
kdtree:
  type 0x10404
  lr 0x55a45b009610
  perm 0x55a45a8e6370
  bb (nil)
  nbb 0
  split 0x55a45b089620
  splitdim (nil)
  dimbits 2
  dimmask 0x3
  splitmask 0xfffffffc
  data 0x55a45b2aa410
  free data 1
  range [-1, 1] [-1, 1] [-1, 1]
  scale 2.14748e+09
  invscale 4.65661e-10
  Ndata 1871011
  Ndim 3
  Nnodes 262143
  Nbottom 131072
  Ninterior 131071
  Nlevels 18
  has_linear_lr 0
  name stars
First data elements in tree: 7.83661e-51,4.48779e-41,3.08841e-53
Nside=156.  Nside^2=24336.  Number of healpixes=292032.  Healpix side length ~ 22.5509 arcmin.
Star tree contains 1871011 objects.
Healpix radius 956.752 arcsec, quad scale 899.998 arcsec, total 1875.32 arcsec
Pass 1 of 16.
Trying 292032 healpixes.
...............................................................................
Made 287778 quads (out of 292032 healpixes) this pass.
[...]
Made 10204 quads (out of 260311 healpixes) this pass.
Writing quads...
Used 200.424 s user, 0.124 s system (200.548 s total), 224.444 s wall time since last check
Done.
Building code kdtree from 4422373 codes
dim: 4
Building tree...
Done
Unpermute-stars...
Writing quads...
...............................................................................
Unpermute-quads...
Writing to file index-tycho2-07.littleendian.fits
*** Error in `build-astrometry-index': corrupted double-linked list: 0x000055a45c813bb0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bcb)[0x7f1ed4251bcb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fa6)[0x7f1ed4257fa6]
/lib/x86_64-linux-gnu/libc.so.6(+0x77f7f)[0x7f1ed4258f7f]
/usr/lib/x86_64-linux-gnu/libastrometry.so.0(kdtree_free+0x71)[0x7f1ed5533de1]
/usr/lib/x86_64-linux-gnu/libastrometry.so.0(startree_close+0x45)[0x7f1ed552c955]
/usr/lib/x86_64-linux-gnu/libastrometry.so.0(index_unload+0x12)[0x7f1ed552b7b2]
/usr/lib/x86_64-linux-gnu/libastrometry.so.0(index_close+0x5e)[0x7f1ed552b98e]
/usr/lib/x86_64-linux-gnu/libastrometry.so.0(build_index_files+0x124)[0x7f1ed5516cb4]
build-astrometry-index(+0x12a5)[0x55a456e782a5]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f1ed42012b1]
build-astrometry-index(+0x147a)[0x55a456e7847a]
======= Memory map: ========
55a456e77000-55a456e7a000 r-xp 00000000 08:02 438333                     /usr/bin/build-astrometry-index
55a457079000-55a45707a000 r--p 00002000 08:02 438333                     /usr/bin/build-astrometry-index
55a45707a000-55a45707b000 rw-p 00003000 08:02 438333                     /usr/bin/build-astrometry-index
55a4580f8000-55a46d898000 rw-p 00000000 00:00 0                          [heap]
7f1ec4000000-7f1ec4021000 rw-p 00000000 00:00 0 
7f1ec4021000-7f1ec8000000 ---p 00000000 00:00 0 
7f1ec9018000-7f1ecd393000 rw-p 00000000 00:00 0 
7f1ed14f7000-7f1ed150d000 r-xp 00000000 08:02 1442937                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f1ed150d000-7f1ed170c000 ---p 00016000 08:02 1442937                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f1ed170c000-7f1ed170d000 r--p 00015000 08:02 1442937                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f1ed170d000-7f1ed170e000 rw-p 00016000 08:02 1442937                    /lib/x86_64-linux-gnu/libgcc_s.so.1
[...]
```
The corresponsing fits file tyc2.fits may be downloaded [here (30 MB)](https://ole.ath.cx/tyc2.fits).
Previous versions of astrometry.net worked; this was found by a test rebuild with the current version  and reported as a [Debian Bug](https://bugs.debian.org/848505). It seems that this appeared with version 0.69.

**Comment by lupinix** [comment]
I've tested it with 0.69 and Fedora using my playground. Builds succeded https://copr.fedorainfracloud.org/coprs/lupinix/astrometry/build/491886/

I'm also building Tycho-2 by myself, so maybe you can find differences here to locate the issue: https://github.com/lupinix/astrometry-tycho2

**Comment by lupinix** [comment]
Logs are here https://copr-be.cloud.fedoraproject.org/results/lupinix/Astronomy/fedora-25-x86_64/00473776-astrometry-tycho2/

**Comment by olebole** [comment]
Can you try with my fits file? Then I would know whether the difference is the Fits or the astrometry.net build.
One difference in the build could be that we use some additional (or different) measures in glibc to find memory corruption; I am not sure how this is for Fedora.

**Comment by dstndstn** [comment]
Dear Ole,

I confirm a crash with 0.69, but it runs to completion in HEAD.

One of the ~9 commits between 0.69 and HEAD is this one, which looks like it would do it.  I have not looked into the history of that line.

https://github.com/dstndstn/astrometry.net/commit/a1f14fc1e141a4869112138d068c9c35b886d5e8

Would you like me to issue a 0.70 release with that fix?

--dstn

**Comment by lupinix** [comment]
@olebole With your fits it also crashes here.

**Comment by lupinix** [comment]
Also crashes locally with my stuff (link above was wrong btw, this one links to the 0.69 build: https://copr-be.cloud.fedoraproject.org/results/lupinix/astrometry/fedora-25-x86_64/00491886-astrometry-tycho2/ ), don't understand yet why it is building in Fedoras virtual machines.

@dstndstn 0.70 with a fix would be nice, yes :)

**Comment by olebole** [comment]
I am already happy with the patch; having a new version would fix this however for everyone :-) So, 0.70 would be probably the best solution.

**Comment by dstndstn** [comment]
As you wish!
https://github.com/dstndstn/astrometry.net/releases/tag/0.70

**Comment by dstndstn** [comment]
PS, @olebole, thank you for the excellent bug report!  Exact command line, link to input data, and regression history.  Makes it so much easier to track down!

**Comment by lupinix** [comment]
I can confirm: No more crashes here with 0.70 on Fedora. Thank you very much!

**Comment by olebole** [comment]
@dstndstn Thank you very much for the quick reaction! I uploaded the new version. Locally I didn't see the crashes anymore, so probably everything is fine.
